<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions name='ProcessConditionInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:wsa='http://www.w3.org/2005/08/addressing' xmlns:tjsr='urn:riv:processdevelopment:infections:ProcessConditionResponder:1' xmlns:tjsi='urn:riv:processdevelopment:infections:ProcessConditionInitiator:1' xmlns:tns='urn:riv:processdevelopment:infections:ProcessCondition:1:rivtabp20' targetNamespace='urn:riv:processdevelopment:infections:ProcessCondition:1:rivtabp20'>
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: ProcessConditionInteraction
			 Beskrivning: 
			   Submission of condition information to Infektionsverktyget
			 Revisioner: 
			 Tjänstedomän: processdevelopment:infections
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP20
			 Förvaltas av: xxx
			 </xs:documentation>
  </xs:annotation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:processdevelopment:infections:ProcessConditionResponder:1:rivtabp20'>
      <xs:import schemaLocation='ProcessConditionResponder_1.0.xsd' namespace='urn:riv:processdevelopment:infections:ProcessConditionResponder:1' />
    </xs:schema>
    <xs:schema targetNamespace='http://www.w3.org/2005/08/addressing'>
      <xs:import schemaLocation='../../core_components/ws-addressing-1.0.xsd' namespace='http://www.w3.org/2005/08/addressing' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='ProcessConditionRequest'>
    <wsdl:part name='LogicalAddress' element='wsa:To'>
      <xs:annotation>
        <xs:documentation>The HSAId for Vårdgivare</xs:documentation>
      </xs:annotation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:ProcessCondition' />
  </wsdl:message>
  <wsdl:message name='ProcessConditionResponse'>
    <wsdl:part name='parameters' element='tjsr:ProcessConditionResponse' />
  </wsdl:message>
  <wsdl:portType name='ProcessConditionResponderInterface'>
    <wsdl:operation name='ProcessCondition'>
      <wsdl:input message='tns:ProcessConditionRequest' />
      <wsdl:output message='tns:ProcessConditionResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='ProcessConditionResponderBinding' type='tns:ProcessConditionResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='ProcessCondition'>
      <soap:operation soapAction='urn:riv:processdevelopment:infections:ProcessConditionResponder:1:ProcessCondition' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:ProcessConditionRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='ProcessConditionResponderService'>
    <wsdl:port name='ProcessConditionResponderPort' binding='tns:ProcessConditionResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>