<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Sveriges Kommuner och Landsting licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions 
	name='GetFormDataInteraction' 
	xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
	xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
	xmlns:xs='http://www.w3.org/2001/XMLSchema' 
	xmlns:tjsr='urn:riv:followup:qualityregistry:nkrr:GetFormDataResponder:1' 
	xmlns:tjsi='urn:riv:followup:qualityregistry:nkrr:GetFormDataInitiator:1' 
	xmlns:tns='urn:riv:followup:qualityregistry:nkrr:GetFormData:1:rivtabp21' 
	targetNamespace='urn:riv:followup:qualityregistry:nkrr:GetFormData:1:rivtabp21' 
	xmlns:itr='urn:riv:itintegration:registry:1'>

  <wsdl:documentation>
      Tjänsteinteraktionens namn: GetFormDataInteraction
      Beskrivning: Hämtning av förifyllnadsunderlag  till kvalitetsregister
      Revisioner: 2022-05-02 Version 1.2
      Tjänstedomän: followup:qualityregistry:nkrr
      Tjänsteinteraktionstyp: Fråga-Svar
      RIV Teknisk Anvisning: RIVTABP21
      Förvaltas av: Sveriges Kommuner och Landsting
 </wsdl:documentation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:followup:qualityregistry:nkrr:GetFormData:1:rivtabp21'>
      <xs:import schemaLocation='GetFormDataResponder_1.2.xsd' namespace='urn:riv:followup:qualityregistry:nkrr:GetFormDataResponder:1' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='GetFormDataRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
      <wsdl:documentation>Den logiska adressen i anropet ska innehålla informationsägande enhets HSA-Id.</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:GetFormData' />
  </wsdl:message>
  <wsdl:message name='GetFormDataResponse'>
    <wsdl:part name='parameters' element='tjsr:GetFormDataResponse' />
  </wsdl:message>
  <wsdl:portType name='GetFormDataResponderInterface'>
    <wsdl:operation name='GetFormData'>
      <wsdl:input message='tns:GetFormDataRequest' />
      <wsdl:output message='tns:GetFormDataResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='GetFormDataResponderBinding' type='tns:GetFormDataResponderInterface'>
    <wsdl:documentation>Tjänsten tillämpar verksamhetsbaserad adressering. Det innebär att den logiska adressen i anropet ska innehålla informationsägande enhets HSA-Id. </wsdl:documentation>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetFormData'>
      <soap:operation soapAction='urn:riv:followup:qualityregistry:nkrr:GetFormDataResponder:1:GetFormData' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetFormDataRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='GetFormDataResponderService'>
    <wsdl:port name='GetFormDataResponderPort' binding='tns:GetFormDataResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>