// Genererad från TKB clinicalprocess:activity:request v2.2
// Kontrakt: ProcessRequest v2.2
// Genererad: 2026-09-26

Invariant: processrequest-vr-intermediary
Description: "Om versionsorsak är VR (vidareskickad remiss) måste intermediaryParticipant anges (schematron Verify intermediaryParticipant)"
Expression: "reasonForVersion.typeOfReason = 'VR' implies intermediaryParticipant.exists()"
Severity: #error

Logical: ProcessRequest
Id: processrequest
Title: "ProcessRequest — Remiss (begäran)"
Description: """
  Logisk modell för begäran i ProcessRequest (RIV-TA urn:riv:clinicalprocess:activity:request:ProcessRequestResponder:2, element request av typen RequestType). Remittenten skickar en allmänremiss till remissmottagaren. Svaret är enbart ett resultat, se ProcessResult.
"""
Characteristics: #can-be-target
* obeys processrequest-vr-intermediary
* requestId 1..1 string "Remiss id" "Remissens identitet. Format Källsystem-Id(HSA-ID)#lokalt-id, mönster (.*)#(.*), maxlängd 256 tecken."
* typeOfRequest 1..1 code "Remisstyp" "Typ av remiss. I denna version är enda giltiga kod 4 = allmänremiss."
* typeOfRequest from RequestTypeVS (required)
* versionTimeStamp 1..1 dateTime "Versionstidpunkt" "Tidpunkt då versionen skapades (ÅÅÅÅMMDDttmmss). Kan skilja sig från tidpunkten då remissen skickas."
* versionNumber 1..1 positiveInt "Versionsnummer" "Remissens versionsnummer. Startar på 1 och räknas upp vid ändrad remiss, vidareskickad remiss och ändrat betalningsansvar. XSD-mönster (0*[1-9]+|[1-9])\\d*."
* reasonForVersion 1..1 BackboneElement "Versionsorsak" "Anger varför en ny version skapats."
  * typeOfReason 1..1 code "Versionsorsak kod" "Kv e-remiss versionsorsak [R5]: NR, AR, VR, AB. RIV-TA: typeOfReason.code."
  * typeOfReason from VersionReasonVS (required)
* careResponsibilityRemains 1..1 boolean "Vårdansvar kvarstår" "true = vårdansvar kvarstår hos remitterande enhet; false = begäran om övertagande av vårdansvar."
* patient 1..1 BackboneElement "Patient" "Patient (PatientType)."
  * personId 1..1 Identifier "Person id" "Patientens identitet. value = personidentifierare (12 tecken utan skiljetecken för personnummer, samordningsnummer och nationellt reservId); system = OID för typ av personidentifierare: 1.2.752.129.2.1.3.1 (personnummer), 1.2.752.129.2.1.3.3 (samordningsnummer), 1.2.752.74.9.1 (nationellt reservId). RIV-TA: personId.extension/root."
  * address 0..1 BackboneElement "Tillfällig adress" "Används endast om tillfällig adress behöver anges, ej folkbokförd adress. Avsedd för kallelse; format enligt Skatteverkets Navet."
    * careOf 0..1 string "Care of" "Maxlängd 35 tecken."
    * streetName1 1..1 string "Utdelningsadress1" "Maxlängd 35 tecken."
    * streetName2 0..1 string "Utdelningsadress2" "Maxlängd 35 tecken."
    * postalCode 1..1 string "Postnummer" "Fem siffror utan blanksteg, t.ex. 12345."
    * postalCity 1..1 string "Postort" "Maxlängd 27 tecken."
    * postBox 0..1 string "Postbox" "Maxlängd 9 tecken."
  * telecom 0..2 BackboneElement "Telefon" "Telefonnummer till patienten."
    * typeOfTelecom 1..1 code "Telefon typ" "H = hemtelefon, MC = mobil."
    * typeOfTelecom from TelecomTypeVS (required)
    * number 1..1 string "Telefonnummer" "Maxlängd 200 tecken."
  * patientName 0..1 string "Namn" "Personnamn enligt formatet \"Mellannamn Efternamn, Förnamn\". Maxlängd 216 tecken. RIV-TA: patient.name."
  * gender 0..1 code "Kön" "Administrativt kön enligt Skatteverket (OID 1.2.752.129.2.2.1.1): 0 okänt, 1 man, 2 kvinna, 9 ej tillämpligt."
  * gender from GenderVS (required)
  * dateOfBirth 0..1 date "Födelsetidpunkt" "Anges när patientens identitet är av annan typ än personnummer (ÅÅÅÅMMDD)."
* requestOrganisation 1..1 BackboneElement "Organisatorisk enhet" "Ursprunglig remitterande organisatorisk enhet. Svaret adresseras till denna enhet som logisk adress."
  * careUnitId 1..1 Identifier "Enhet id" "HSA-id för enheten. Maxlängd 64 tecken."
  * careUnitName 0..1 string "Enhet namn" "Namn på enhet. Maxlängd 64 tecken."
  * careUnitTelephone 0..1 string "Enhet telefon" "Telefon till enhet."
  * careUnitEmail 0..1 string "Enhet epost" "E-post till enhet."
  * careUnitAddress 0..1 string "Enhet adress" "Adress till enhet."
  * careUnitLocation 0..1 string "Enhet plats" "Namnet på plats eller ort för enhetens fysiska placering."
* author 1..1 BackboneElement "Remittent" "Remittent (person och organisation)."
  * date 1..1 date "Remissdatum" "Datum då remissen skapades (ÅÅÅÅMMDD)."
  * healthcareProfessional 1..1 BackboneElement "Hälso- och sjukvårdspersonal" "Hälso- och sjukvårdspersonal (HealthcareProfessionalType)."
    * healthcareProfessionalId 0..1 Identifier "Personal id" "HSA-id för personen. Maxlängd 64 tecken. RIV-TA: healthcareProfessional.id."
    * healthcareProfessionalName 1..1 string "Personal namn" "Namn, valfri formatering. Maxlängd 64 tecken. RIV-TA: healthcareProfessional.name."
  * typeOfHealthcareProfessional 0..1 CodeableConcept "Typ av hälso- och sjukvårdspersonal" "Yrkestitel från Snomed CT: urval_legitimerade_yrken (codeSystem 1.2.752.129.5.1.70) eller yrken_i_halso-_och_sjukvarden_ej_legitimerade (codeSystem 1.2.752.129.7.1.5). Urvalen kan kompletteras utan ny kontraktsversion."
  * healthcareProfessionalOrganisation 1..1 BackboneElement "Organisatorisk enhet" "Enhet (jmf. PDL) som ansvarar för informationen."
    * careUnitId 1..1 Identifier "Enhet id" "HSA-id för enheten. Maxlängd 64 tecken."
* recipient 1..1 BackboneElement "Mottagare" "Remissmottagande organisation."
  * organisation 1..1 BackboneElement "Organisatorisk enhet" "Mottagande enhet; HSA-id används som logisk adress."
    * careUnitId 1..1 Identifier "Enhet id" "HSA-id för enheten. Maxlängd 64 tecken."
* intermediaryParticipant 0..* BackboneElement "Vidareskickare" "Hälso- och sjukvårdspersonalen som vidareskickar remissen."
  * healthcareProfessionalOrganisation 1..1 BackboneElement "Organisatorisk enhet" "Remissmottagande enhet som vidareskickat remissen."
    * careUnitId 1..1 Identifier "Enhet id" "HSA-id för enheten. Maxlängd 64 tecken."
  * time 1..1 dateTime "Tidpunkt" "Tidpunkt då versionen skapades för vidareskickning (ÅÅÅÅMMDDttmmss)."
* additionalInformation 0..1 BackboneElement "Tilläggsinformation" "Tilläggsinformation."
  * desiredRequestRecipient 0..1 string "Önskemål om remissmottagare" "Enhet, person, yrkesroll eller fritext. Maxlängd 200 tecken."
  * administrativeInformation 0..1 string "Kompletterande administrativ information" "T.ex. akutärende, bortrest patient, SVF-patient och datum för välgrundad misstanke."
  * interpreterRequirement 0..1 string "Kommentar tolkbehov" "Maxlängd 200 tecken."
* awarenessInformation 0..1 BackboneElement "Uppmärksamhetsinformation" "Uppmärksamhetsinformation om patient."
  * awarenessText 1..1 string "Uppmärksamhetstext" "Av betydelse för denna remiss; mottagande system bör inte automatiskt föra in den i egen uppmärksamhetshantering. Maxlängd 8192 tecken. RIV-TA: awarenessInformation.text."
* questionFormulation 1..1 BackboneElement "Frågeställning" "Remissens frågeställning."
  * questionText 1..1 string "Frågeställning text" "Maxlängd 8192 tecken. RIV-TA: questionFormulation.text."
  * clinicalInformation 0..1 BackboneElement "Anamnes" "Underbyggande klinisk information för frågeställningen."
    * clinicalInformationText 1..1 string "Beskrivning" "Maxlängd 8192 tecken. RIV-TA: clinicalInformation.text."
  * condition 0..* BackboneElement "Kliniskt tillstånd" "Kliniskt tillstånd (ConditionType). Antingen text eller kod, inte båda."
    * obeys activity-request-condition-code-or-text
    * conditionText 0..1 string "Kliniskt tillstånd beskrivning" "Diagnosbeskrivning i fritext. Maxlängd 8192 tecken. RIV-TA: condition.text."
    * conditionCode 0..1 CodeableConcept "Kliniskt tillståndskod" "Kod enligt ICD-10-SE (codeSystem 1.2.752.116.1.1.1). RIV-TA: condition.code."
  * desiredActivity 0..* BackboneElement "Önskad åtgärd" "Önskad åtgärd (ActivityType). Antingen text eller kod, inte båda."
    * obeys activity-request-activity-code-or-text
    * activityId 0..1 string "Åtgärd id" "Unikt id i form av löpnummer för åtgärden. RIV-TA: id."
    * activityText 0..1 string "Åtgärd beskrivning" "Fritext. Maxlängd 8192 tecken. RIV-TA: text."
    * activityCode 0..1 Coding "Åtgärd typ" "Åtgärd enligt kodsystem: KVÅ (1.2.752.116.1.3.2.1.4, obligatoriskt att hantera) eller Snomed CT. Okänt kodverk ger APPLICATION_ERROR. RIV-TA: code.code/codeSystem."
* paymentCommitment 0..1 BackboneElement "Betalningsförbindelse" "Hur remissmottagande vårdgivare ersätts av remitterande vårdgivare; aktuellt vid regionsöverskridande remissflöde (Riksavtalet)."
  * obeys activity-request-commitmenttype-chapter
  * paymentCommitmentId 0..1 string "Betalningsförbindelse id" "Format requestId#betfor#löpnummer."
  * commitmentType 1..1 CodeableConcept "Betalningsförbindelse-typ avtal" "kv_betalningsförbindelsetyp avtal, codeSystem 1.2.752.129.2.2.2.44."
  * commitmentTypeChapter 0..1 CodeableConcept "Betalningsförbindelse-typ kapitel" "Riksavtalets kapitel, codeSystem 1.2.752.129.5.1.37. Obligatoriskt då commitmentType = 1."
  * validity 1..1 Period "Giltighetstid" "ÅÅÅÅMMDD. Antingen start (low) eller slut (high) måste finnas."
  * clinicalResponsibilityDescription 0..1 string "Klinisk ansvarsbeskrivning" "Maxlängd 8192 tecken."
  * administrativeResponsibilityDescription 0..1 string "Administrativ ansvarsbeskrivning" "Maxlängd 8192 tecken."
  * validOnlyForOutpatientCare 1..1 boolean "Gäller endast öppenvård" "true om betalningsförbindelsen enbart gäller öppenvård."
  * liableCountyCouncil 1..1 CodeableConcept "Betalningsansvarig region" "kv_län (SCB), codeSystem 1.2.752.129.2.2.1.18."
  * dateOfApproval 0..1 dateTime "Datum för godkännande" "ÅÅÅÅMMDDttmmss med minst precision ÅÅÅÅMMDD."
  * issuedInConsultationWith 0..1 string "Utfärdad i samråd med" "Namn på ekonomisk beslutsfattare. Maxlängd 64 tecken."
  * costCenter 0..1 string "Kostnadsställe" "Remittentens kostnadsställe. Maxlängd 64 tecken."
  * reimbursementInformation 0..1 BackboneElement "Ersättningsinformation" "Obligatorisk vid remiss till privat vårdgivare."
    * reimbursementType 1..1 CodeableConcept "Ersättningstyp" "kv_betalningsförbindelse ersättningstyp, codeSystem 1.2.752.129.5.1.36."
    * ownerOfInvokedContract 1..1 CodeableConcept "Ägare av åberopat kontrakt" "Region enligt kv_län (SCB), codeSystem 1.2.752.129.2.2.1.18."
  * approvedBy 0..1 BackboneElement "Godkänns av" "Person hos remittenten som godkänt betalningsförbindelsen."
    * healthcareProfessionalId 0..1 Identifier "Personal id" "HSA-id för person. RIV-TA: approvedBy.id."
    * healthcareProfessionalName 1..1 string "Personal namn" "Maxlängd 64 tecken. RIV-TA: approvedBy.name."
* attachment 0..* BackboneElement "Bilaga" "Bilaga (MultimediaType) i något av de tillåtna formaten. Totala meddelandestorleken får inte överstiga 10 MB."
  * attachmentId 0..1 string "Bilaga id" "Identitet på bilagan, format requestId#löpnummer. Obligatoriskt för inbäddade bilagor. Maxlängd 256 tecken. RIV-TA: attachment.id."
  * mediaType 1..1 CodeableConcept "Multimediatyp" "Filformat enligt urval_mediatyper_elektronisk_remiss (codeSystem 1.2.752.129.5.1.59): pdf, jpeg, png, html, txt, gif, bmp."
  * attachmentValue 0..1 base64Binary "Binärdata" "Inbäddad bilaga kodad enligt base64. Obligatoriskt när referens inte används. RIV-TA: attachment.value."
  * reference 0..0 uri "Referens" "URL för refererad bilaga. Används inte i denna version."
  * description 0..1 string "Beskrivning" "Beskrivning av bilaga. Maxlängd 256 tecken."
* careProcessId 0..1 string "Vårdprocess id" "Identifierar den individanpassade vårdprocess som remissen är en del av."
