// Genererad från XSD för informationsecurity.authorization.consent v2.0.4 (Genererad ur scheman i riv.informationsecurity.authorization.consent, tagg 2.0.4; scripts/xsd_to_ig.py)
// Kontrakt: GetExtendedConsentsForPatient v2.0
// Genererad: 2026-09-26

Logical: GetExtendedConsentsForPatient
Id: getextendedconsentsforpatient
Title: "GetExtendedConsentsForPatient — Response"
Description: """
  Logisk modell för svaret i GetExtendedConsentsForPatient
  (urn:riv:informationsecurity:authorization:consent:GetExtendedConsentsForPatientResponder:2, GetExtendedConsentsForPatientResponseType).
"""
Characteristics: #can-be-target
* getExtendedConsentsResult 1..1 BackboneElement "getExtendedConsentsResult" "Datatyp som innehåller resultatet från en hämtning av samtyckesintyg enligt det utökade formatet tillsammans med hämtade samtyckesintyg. Datatypen utökar datatypen Result."
  * result 1..1 BackboneElement "result" "Datatyp som returneras som ett generellt svar från alla förändrande tjänster, t.ex. skapa, radera, etc. En tjänstekonsument skall alltid kontrollera att resultatkoden inte innehåller fel för att på så sätt veta om anropet lyckades. Alla svarskoder förutom OK och INFO betyder att åtgärden inte genomfördes."
    * resultCode 1..1 code "resultCode" "resultCode"
    * resultCode from ResultCodeVS (required)
    * resultText 0..1 string "resultText" "resultText"
  * pdlAssertions 0..* BackboneElement "pdlAssertions" "Datatyp som representerar ett samtycke med ett utökat format. Innehåller information vem som har begärt respektive registrerat samtycket, samt om och när samtycket är återkallat eller makulerat. Datatypen utökar datatypen PDLAssertion."
    * pDLAssertion 1..1 BackboneElement "pDLAssertion" "Datatyp som representerar ett intyg som ger direktåtkomst till andra vårdgivares information enligt PDL. Datatypen beskriver grundformatet för ett intyg."
      * assertionId 1..1 string "assertionId" "assertionId"
      * assertionType 1..1 code "assertionType" "assertionType"
      * assertionType from AssertionTypeVS (required)
      * scope 1..1 code "scope" "scope"
      * scope from ScopeVS (required)
      * careProviderId 1..1 string "careProviderId" "careProviderId"
      * careUnitId 1..1 string "careUnitId" "careUnitId"
      * employeeId 0..1 string "employeeId" "employeeId"
      * startDate 1..1 dateTime "startDate" "startDate"
      * endDate 0..1 dateTime "endDate" "endDate"
      * ownerId 0..1 string "ownerId" "ownerId"
      * patientId 1..1 BackboneElement "patientId" "En universellt unik identifierare."
        * root 1..1 string "root" "root"
        * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * representedBy 0..1 BackboneElement "representedBy" "En universellt unik identifierare."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * registrationInfo 1..1 BackboneElement "registrationInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
      * requestDate 1..1 dateTime "requestDate" "requestDate"
      * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
      * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * reasonText 0..1 string "reasonText" "reasonText"
    * cancellationInfo 0..1 BackboneElement "cancellationInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
      * requestDate 1..1 dateTime "requestDate" "requestDate"
      * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
      * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * reasonText 0..1 string "reasonText" "reasonText"
    * deletionInfo 0..1 BackboneElement "deletionInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
      * requestDate 1..1 dateTime "requestDate" "requestDate"
      * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
      * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * reasonText 0..1 string "reasonText" "reasonText"
