// Genererad från XSD för informationsecurity.auditing.log v2.0.8 (Genererad ur scheman i riv.informationsecurity.auditing.log, tagg 2.0.8; scripts/xsd_to_ig.py)
// Kontrakt: GetLogs v2.0
// Genererad: 2026-09-26

Logical: GetLogs
Id: getlogs
Title: "GetLogs — Response"
Description: """
  Logisk modell för svaret i GetLogs
  (urn:riv:informationsecurity:auditing:log:GetLogsResponder:2, GetLogsResponseType).
"""
Characteristics: #can-be-target
* logsResult 1..1 BackboneElement "logsResult" "Datatyp som returneras av tjänst. logs är ej satt vid eventuella fel."
  * reportResult 1..1 BackboneElement "reportResult" "reportResult"
    * result 1..1 BackboneElement "result" "Datatyp som returneras som ett generellt svar från alla förändrande tjänster, t.ex. skapa, radera, etc. En anropande klient skall alltid kontrollera att resultatkoden inte innehåller fel för att på så sätt veta om anropet lyckades. Alla svarskoder förutom OK och INFO betyder att åtgärden inte genomfördes."
      * resultCode 1..1 code "resultCode" "resultCode"
      * resultCode from ResultCodeVS (required)
      * resultText 0..1 string "resultText" "resultText"
    * startInterval 0..1 dateTime "startInterval" "startInterval"
    * endInterval 0..1 dateTime "endInterval" "endInterval"
    * queuedReportId 0..1 string "queuedReportId" "queuedReportId"
    * queueTime 0..1 integer "queueTime" "queueTime"
  * logs 0..1 BackboneElement "logs" "Datatyp som håller lista med loggposter. Kan vara en tom lista"
    * log 0..* BackboneElement "log" "Datatyp som representerar en loggpost enligt PDL. Datatypen beskriver grundformatet för en loggpost."
      * logId 1..1 string "logId" "logId"
      * system 1..1 BackboneElement "system" "Datatyp som representerar ett system i loggposten. Det system som skapar loggposten."
        * systemId 1..1 string "systemId" "systemId"
        * systemName 0..1 string "systemName" "systemName"
      * activity 1..1 BackboneElement "activity" "Datatyp som representerar vilken typ av aktivitet som utförts, på vilken nivå, tidpunkt samt syftet med aktiviteten."
        * activityType 1..1 string "activityType" "activityType"
        * activityLevel 0..1 string "activityLevel" "activityLevel"
        * activityArgs 0..1 string "activityArgs" "activityArgs"
        * startDate 1..1 dateTime "startDate" "startDate"
        * purpose 1..1 string "purpose" "purpose"
      * user 1..1 BackboneElement "user" "Datatyp som representerar användaren som utfört aktivitet, tillika ägare av loggpost."
        * userId 1..1 string "userId" "userId"
        * userName 0..1 string "userName" "userName Heter name i schemat."
        * personId 0..1 BackboneElement "personId" "En universellt unik identifierare."
          * root 1..1 string "root" "root"
          * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
        * assignment 0..1 string "assignment" "assignment"
        * title 0..1 string "title" "title"
        * careProvider 1..1 BackboneElement "careProvider" "Datatyp som representerar en vårdgivare."
          * careProviderId 1..1 string "careProviderId" "careProviderId"
          * careProviderName 0..1 string "careProviderName" "careProviderName"
        * careUnit 1..1 BackboneElement "careUnit" "Datatyp som representerar en vårdenhet."
          * careUnitId 1..1 string "careUnitId" "careUnitId"
          * careUnitName 0..1 string "careUnitName" "careUnitName"
      * resources 1..1 BackboneElement "resources" "Information om aktuella resurser. En loggpost kan hålla en eller flera resurser."
        * resource 1..* BackboneElement "resource" "Datatyp som representerar en resurs i loggposten."
          * resourceType 1..1 string "resourceType" "resourceType"
          * patient 0..1 BackboneElement "patient" "Datatyp som representerar en patient i en resurs."
            * patientId 1..1 BackboneElement "patientId" "En universellt unik identifierare."
              * root 1..1 string "root" "root"
              * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
            * patientName 0..1 string "patientName" "patientName"
          * careProvider 1..1 BackboneElement "careProvider" "Datatyp som representerar en vårdgivare."
            * careProviderId 1..1 string "careProviderId" "careProviderId"
            * careProviderName 0..1 string "careProviderName" "careProviderName"
          * careUnit 0..1 BackboneElement "careUnit" "Datatyp som representerar en vårdenhet."
            * careUnitId 1..1 string "careUnitId" "careUnitId"
            * careUnitName 0..1 string "careUnitName" "careUnitName"
