// Genererad från TKB ehr:blocking v3.2.2
// Kontrakt: GetExtendedBlocksForPatient v2.0 (administration)
// Genererad: 2026-04-09

Logical: GetExtendedBlocksForPatient
Id: getextendedblockforpatient
Title: "GetExtendedBlocksForPatient"
Description: """
  Logisk modell för tjänstekontraktet GetExtendedBlocksForPatient
  (RIV-TA urn:riv:ehr:blocking:administration:GetExtendedBlocksForPatientResponder:2).
  Läser spärrar för en viss patient med utökad information inklusive aktörsinformation,
  historik och makulerade spärrar. Representerar responsens informationsstruktur.
"""
Characteristics: #can-be-target

* result 1..1 BackboneElement "Resultat av anropet"
  * resultCode 1..1 code "Svarskod"
  * resultCode from ResultCodeVS (required)
  * resultText 0..1 string "Beskrivande text till svarskoden"
* blocks 0..* BackboneElement "Lista med utökad spärrinformation (inkl. makulerade och hävda spärrar)"
  * blockId 1..1 string "Unik identifierare för spärren (UUID)"
  * blockType 1..1 code "Typ av spärr"
  * blockType from BlockTypeVS (required)
  * patientId 1..1 string "Patientens personnummer eller samordningsnummer"
  * informationStartDate 0..1 dateTime "Startdatum för vilken information spärren gäller"
  * informationEndDate 0..1 dateTime "Slutdatum för vilken information spärren gäller"
  * informationCareUnitId 0..1 string "HSA-id för vårdenhet (vid inre spärr)"
  * informationCareProviderId 1..1 string "HSA-id för vårdgivare"
  * excludedInformationTypes 0..* BackboneElement "Informationstyper undantagna från spärren"
    * infoTypeId 1..1 string "ID för informationstypen"
    * infoTypeDescription 1..1 string "Beskrivning av informationstypen"
  * registrationInfo 1..1 BackboneElement "Aktörsinfo för registrering av spärren"
    * requestDate 1..1 dateTime "Datum när spärren begärdes"
    * requestedBy 1..1 BackboneElement "Aktören som begärde spärren"
      * employeeId 1..1 string "HSA-id för anställd"
      * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
      * assignmentName 0..1 string "Namn på medarbetaruppdrag"
    * registrationDate 1..1 dateTime "Datum när spärren registrerades"
    * registeredBy 1..1 BackboneElement "Aktören som registrerade spärren"
      * employeeId 1..1 string "HSA-id för anställd"
      * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
      * assignmentName 0..1 string "Namn på medarbetaruppdrag"
    * reasonText 0..1 string "Orsak till spärren (max 1024 tecken)"
  * permanentRevokedInfo 0..1 BackboneElement "Aktörsinfo vid permanent hävning (om spärren hävts)"
    * requestDate 1..1 dateTime "Datum när hävning begärdes"
    * requestedBy 1..1 BackboneElement "Aktören som begärde hävningen"
      * employeeId 1..1 string "HSA-id för anställd"
      * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
      * assignmentName 0..1 string "Namn på medarbetaruppdrag"
    * registrationDate 1..1 dateTime "Datum när hävningen registrerades"
    * registeredBy 1..1 BackboneElement "Aktören som registrerade hävningen"
      * employeeId 1..1 string "HSA-id för anställd"
      * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
      * assignmentName 0..1 string "Namn på medarbetaruppdrag"
    * reasonText 0..1 string "Orsak till hävningen"
  * deletionInfo 0..1 BackboneElement "Aktörsinfo vid makulering (om spärren makulerats)"
    * requestDate 1..1 dateTime "Datum när makulering begärdes"
    * requestedBy 1..1 BackboneElement "Aktören som begärde makuleringen"
      * employeeId 1..1 string "HSA-id för anställd"
      * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
      * assignmentName 0..1 string "Namn på medarbetaruppdrag"
    * registrationDate 1..1 dateTime "Datum när makuleringen registrerades"
    * registeredBy 1..1 BackboneElement "Aktören som registrerade makuleringen"
      * employeeId 1..1 string "HSA-id för anställd"
      * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
      * assignmentName 0..1 string "Namn på medarbetaruppdrag"
    * reasonText 0..1 string "Orsak till makuleringen"
  * temporaryRevokes 0..* BackboneElement "Tillfälliga hävningar (inkl. historik)"
    * temporaryRevokeId 1..1 string "Unik ID för tillfällig hävning"
    * endDate 1..1 dateTime "Datum när hävningen upphör"
    * revokedForCareUnitId 1..1 string "HSA-id för vårdenhet"
    * revokedForEmployeeId 0..1 string "HSA-id för enskild medarbetare"
    * reason 1..1 code "Orsak till tillfällig hävning"
    * reason from TemporaryRevokeReasonVS (required)
    * registrationInfo 1..1 BackboneElement "Aktörsinfo för registrering av hävningen"
      * requestDate 1..1 dateTime "Datum när hävningen begärdes"
      * requestedBy 1..1 BackboneElement "Aktören som begärde hävningen"
        * employeeId 1..1 string "HSA-id för anställd"
        * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
        * assignmentName 0..1 string "Namn på medarbetaruppdrag"
      * registrationDate 1..1 dateTime "Datum när hävningen registrerades"
      * registeredBy 1..1 BackboneElement "Aktören som registrerade hävningen"
        * employeeId 1..1 string "HSA-id för anställd"
        * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
        * assignmentName 0..1 string "Namn på medarbetaruppdrag"
      * reasonText 0..1 string "Fritext-orsak"
    * cancellationInfo 0..1 BackboneElement "Aktörsinfo om hävningen har återkallats"
      * requestDate 1..1 dateTime "Datum när återkallning begärdes"
      * requestedBy 1..1 BackboneElement "Aktören som begärde återkallningen"
        * employeeId 1..1 string "HSA-id för anställd"
        * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
        * assignmentName 0..1 string "Namn på medarbetaruppdrag"
      * registrationDate 1..1 dateTime "Datum när återkallningen registrerades"
      * registeredBy 1..1 BackboneElement "Aktören som registrerade återkallningen"
        * employeeId 1..1 string "HSA-id för anställd"
        * assignmentId 0..1 string "HSA-id för medarbetaruppdrag"
        * assignmentName 0..1 string "Namn på medarbetaruppdrag"
      * reasonText 0..1 string "Fritext-orsak"
