// Genererad från XSD för informationsecurity.authorization.blocking v4.0.4 (Genererad ur scheman i riv.informationsecurity.authorization.blocking, tagg 4.0.4; scripts/xsd_to_ig.py)
// Kontrakt: GetExtendedBlocksForPatient v4.0
// Genererad: 2026-09-26

Logical: GetExtendedBlocksForPatient
Id: getextendedblocksforpatient
Title: "GetExtendedBlocksForPatient — Response"
Description: """
  Logisk modell för svaret i GetExtendedBlocksForPatient
  (urn:riv:informationsecurity:authorization:blocking:GetExtendedBlocksForPatientResponder:4, GetExtendedBlocksForPatientResponseType).
"""
Characteristics: #can-be-target
* getExtendedBlocksResult 1..1 BackboneElement "getExtendedBlocksResult" "Datatyp som innehåller resultatet från tjänsten GetExtendedBlocksForPatient. Datatypen utökar datatypen Result."
  * result 1..1 BackboneElement "result" "Datatyp som returneras som ett generellt svar från alla förändrande tjänster, t.ex. skapa, radera, etc. En tjänstekonsument skall alltid kontrollera att resultatkoden inte innehåller fel för att på så sätt veta om anropet lyckades. Alla svarskoder förutom OK och INFO betyder att åtgärden inte genomfördes."
    * resultCode 1..1 code "resultCode" "resultCode"
    * resultCode from ResultCodeVS (required)
    * resultText 0..1 string "resultText" "resultText"
  * blocks 0..* BackboneElement "blocks" "Datatyp som representerar en spärr enligt det utökade formatet."
    * blockId 1..1 string "blockId" "blockId"
    * blockType 1..1 code "blockType" "blockType"
    * blockType from BlockTypeVS (required)
    * informationStartDate 0..1 dateTime "informationStartDate" "informationStartDate"
    * informationEndDate 0..1 dateTime "informationEndDate" "informationEndDate"
    * informationCareUnitId 0..1 string "informationCareUnitId" "informationCareUnitId"
    * informationCareProviderId 1..1 string "informationCareProviderId" "informationCareProviderId"
    * patientId 1..1 BackboneElement "patientId" "En universellt unik identifierare."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * excludedInformationTypes 0..* BackboneElement "excludedInformationTypes" "Datatyp som representerar de Informationstyper som kan undantas från att spärras. En spärr gäller normalt alla informationstyper. Denna lista utgör de informationstyper som kan undantas från att spärras. Om försök görs att registrera en spärr innehållandes en okänd informationstyp skall spärrtjänsten att neka detta. lak Läkemedel - Ordination/förskrivning upp Uppmärksamhetsinformation"
      * infoTypeId 1..1 string "infoTypeId" "infoTypeId"
      * infoTypeDescription 1..1 string "infoTypeDescription" "infoTypeDescription"
    * registrationInfo 1..1 BackboneElement "registrationInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
      * requestDate 1..1 dateTime "requestDate" "requestDate"
      * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
      * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * reasonText 0..1 string "reasonText" "reasonText"
    * permanentRevokedInfo 0..1 BackboneElement "permanentRevokedInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
      * requestDate 1..1 dateTime "requestDate" "requestDate"
      * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
      * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * reasonText 0..1 string "reasonText" "reasonText"
    * deletionInfo 0..1 BackboneElement "deletionInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
      * requestDate 1..1 dateTime "requestDate" "requestDate"
      * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
      * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
        * employeeId 1..1 string "employeeId" "employeeId"
        * assignmentId 0..1 string "assignmentId" "assignmentId"
        * assignmentName 0..1 string "assignmentName" "assignmentName"
      * reasonText 0..1 string "reasonText" "reasonText"
    * temporaryRevokes 0..* BackboneElement "temporaryRevokes" "Datatyp som representerar en tillfällig hävning enligt det utökade formatet."
      * temporaryRevokeId 1..1 string "temporaryRevokeId" "temporaryRevokeId"
      * endDate 1..1 dateTime "endDate" "endDate"
      * revokedForCareUnitId 1..1 string "revokedForCareUnitId" "revokedForCareUnitId"
      * revokedForEmployeeId 0..1 string "revokedForEmployeeId" "revokedForEmployeeId"
      * revocationReason 0..1 code "revocationReason" "revocationReason"
      * revocationReason from TemporaryRevokeReasonVS (required)
      * revocationReasonText 0..1 string "revocationReasonText" "revocationReasonText"
      * registrationInfo 1..1 BackboneElement "registrationInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
        * requestDate 1..1 dateTime "requestDate" "requestDate"
        * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
          * employeeId 1..1 string "employeeId" "employeeId"
          * assignmentId 0..1 string "assignmentId" "assignmentId"
          * assignmentName 0..1 string "assignmentName" "assignmentName"
        * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
        * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
          * employeeId 1..1 string "employeeId" "employeeId"
          * assignmentId 0..1 string "assignmentId" "assignmentId"
          * assignmentName 0..1 string "assignmentName" "assignmentName"
        * reasonText 0..1 string "reasonText" "reasonText"
      * cancellationInfo 0..1 BackboneElement "cancellationInfo" "Datatyp som representerar den eller de aktörer/personer som begärt och/eller utfört en åtgärd med en möjlig orsak/anledning angivet som fritext."
        * requestDate 1..1 dateTime "requestDate" "requestDate"
        * requestedBy 1..1 BackboneElement "requestedBy" "Datatyp som identifierar en medarbetare/person."
          * employeeId 1..1 string "employeeId" "employeeId"
          * assignmentId 0..1 string "assignmentId" "assignmentId"
          * assignmentName 0..1 string "assignmentName" "assignmentName"
        * registrationDate 1..1 dateTime "registrationDate" "registrationDate"
        * registeredBy 1..1 BackboneElement "registeredBy" "Datatyp som identifierar en medarbetare/person."
          * employeeId 1..1 string "employeeId" "employeeId"
          * assignmentId 0..1 string "assignmentId" "assignmentId"
          * assignmentName 0..1 string "assignmentName" "assignmentName"
        * reasonText 0..1 string "reasonText" "reasonText"
      * ownerId 0..1 string "ownerId" "ownerId"
    * ownerId 0..1 string "ownerId" "ownerId"
    * locallyCreated 1..1 boolean "locallyCreated" "locallyCreated"
