// Genererad från XSD för orgmaster.hsa v1.0.0 (fält ur XSD, se TKB avsnitt 3–7; scripts/xsd_to_ig.py)
// Kontrakt: GetHsaPerson v1.0
// Genererad: 2026-09-26

Logical: GetHsaPerson
Id: gethsaperson
Title: "GetHsaPerson — Response"
Description: """
  Logisk modell för svaret i GetHsaPerson
  (urn:riv:orgmaster:hsa:GetHsaPersonResponder:1, GetHsaPersonResponseType).
"""
Characteristics: #can-be-target
* userInformations 0..1 BackboneElement "userInformations" "userInformations"
  * userInformation 0..* BackboneElement "userInformation" "userInformation"
    * personalPrescriptionCode 0..1 string "personalPrescriptionCode" "personalPrescriptionCode"
    * description 0..1 string "description" "description"
    * paTitleCodes 1..1 BackboneElement "paTitleCodes" "paTitleCodes"
      * paTitleCode 0..* string "paTitleCode" "paTitleCode"
    * paTitleNames 1..1 BackboneElement "paTitleNames" "paTitleNames"
      * paTitleName 0..* string "paTitleName" "paTitleName"
    * mail 0..1 string "mail" "mail"
    * givenName 1..1 string "givenName" "givenName"
    * hsaIdentity 1..1 string "hsaIdentity" "hsaIdentity"
    * hsaSwitchboardNumber 0..1 string "hsaSwitchboardNumber" "hsaSwitchboardNumber"
    * hsaTelephoneNumbers 1..1 BackboneElement "hsaTelephoneNumbers" "hsaTelephoneNumbers"
      * hsaTelephoneNumber 0..* string "hsaTelephoneNumber" "hsaTelephoneNumber"
    * labeledUri 0..1 string "labeledUri" "labeledUri"
    * languageKnowledgeCodes 0..1 BackboneElement "languageKnowledgeCodes" "languageKnowledgeCodes"
      * languageKnowledgeCode 0..* string "languageKnowledgeCode" "languageKnowledgeCode"
    * mobileNumbers 1..1 BackboneElement "mobileNumbers" "mobileNumbers"
      * mobileNumber 0..* string "mobileNumber" "mobileNumber"
    * facsimileTelephoneNumbers 1..1 BackboneElement "facsimileTelephoneNumbers" "facsimileTelephoneNumbers"
      * facsimileTelephoneNumber 0..* string "facsimileTelephoneNumber" "facsimileTelephoneNumber"
    * nickName 0..1 string "nickName" "nickName"
    * smsTelephoneNumber 0..1 string "smsTelephoneNumber" "smsTelephoneNumber"
    * specialityCodes 1..1 BackboneElement "specialityCodes" "specialityCodes"
      * specialityCode 0..* string "specialityCode" "specialityCode"
    * specialityNames 1..1 BackboneElement "specialityNames" "specialityNames"
      * specialityName 0..* string "specialityName" "specialityName"
    * sn 1..1 string "sn" "sn"
    * telephoneHours 1..1 BackboneElement "telephoneHours" "telephoneHours"
      * telephoneHour 0..* BackboneElement "telephoneHour" "telephoneHour"
        * fromDay 1..1 integer "fromDay" "fromDay"
        * fromTime 1..1 time "fromTime" "fromTime"
        * fromTime2 1..1 string "fromTime2" "fromTime2"
        * toDay 1..1 integer "toDay" "toDay"
        * toTime 1..1 time "toTime" "toTime"
        * toTime2 1..1 string "toTime2" "toTime2"
        * comment 1..1 string "comment" "comment"
    * telephoneNumbers 1..1 BackboneElement "telephoneNumbers" "telephoneNumbers"
      * telephoneNumber 0..* string "telephoneNumber" "telephoneNumber"
    * title 0..1 string "title" "title"
    * DN 1..1 string "DN" "DN"
    * middleName 1..1 string "middleName" "middleName"
    * postalAddress 0..1 BackboneElement "postalAddress" "postalAddress"
      * addressLine 1..* string "addressLine" "addressLine"
    * hsaTitles 1..1 BackboneElement "hsaTitles" "hsaTitles"
      * hsaTitle 0..* string "hsaTitle" "hsaTitle"
