// Genererad från XSD för orgmaster.hsa v1.0.0 (fält ur XSD, se TKB avsnitt 3–7; scripts/xsd_to_ig.py)
// Kontrakt: GetHsaUnit v1.0
// Genererad: 2026-09-26

Logical: GetHsaUnit
Id: gethsaunit
Title: "GetHsaUnit — Response"
Description: """
  Logisk modell för svaret i GetHsaUnit
  (urn:riv:orgmaster:hsa:GetHsaUnitResponder:1, GetHsaUnitResponseType).
"""
Characteristics: #can-be-target
* careGiver 0..1 string "careGiver" "careGiver"
* parentHsaIdentity 0..1 string "parentHsaIdentity" "parentHsaIdentity"
* unitPrescriptionCodes 1..1 string "unitPrescriptionCodes" "unitPrescriptionCodes"
* alternateNames 0..1 BackboneElement "alternateNames" "alternateNames"
  * alternateName 0..* string "alternateName" "alternateName"
* alternateText 0..1 string "alternateText" "alternateText"
* businessClassifications 0..1 BackboneElement "businessClassifications" "businessClassifications"
  * businessClassification 0..* string "businessClassification" "businessClassification"
* businessClassificationCodes 0..1 BackboneElement "businessClassificationCodes" "businessClassificationCodes"
  * businessClassificationCode 0..* string "businessClassificationCode" "businessClassificationCode"
* businessTypes 0..1 BackboneElement "businessTypes" "businessTypes"
  * businessType 0..* string "businessType" "businessType"
* careTypes 0..1 BackboneElement "careTypes" "careTypes"
  * careType 0..* string "careType" "careType"
* county 0..1 string "county" "county"
* countyCode 0..1 string "countyCode" "countyCode"
* description 0..1 string "description" "description"
* directoryContact 0..1 string "directoryContact" "directoryContact"
* displayOption 0..1 string "displayOption" "displayOption"
* dropInHours 0..1 BackboneElement "dropInHours" "dropInHours"
  * dropInHour 0..* BackboneElement "dropInHour" "dropInHour"
    * fromDay 1..1 integer "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * fromTime2 1..1 string "fromTime2" "fromTime2"
    * toDay 1..1 integer "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * toTime2 1..1 string "toTime2" "toTime2"
    * comment 1..1 string "comment" "comment"
* email 0..1 string "email" "email"
* faxNumbers 0..1 BackboneElement "faxNumbers" "faxNumbers"
  * faxNumber 0..* string "faxNumber" "faxNumber"
* geographicalCoordinatesRt90 0..1 BackboneElement "geographicalCoordinatesRt90" "geographicalCoordinatesRt90"
  * coordinatesType 1..1 string "coordinatesType" "coordinatesType Heter type i schemat."
  * x 1..1 string "x" "x"
  * y 1..1 string "y" "y"
* healthCareArea 0..1 string "healthCareArea" "healthCareArea"
* hsaDestinationIndicators 1..1 BackboneElement "hsaDestinationIndicators" "hsaDestinationIndicators"
  * hsaDestinationIndicator 0..* string "hsaDestinationIndicator" "hsaDestinationIndicator"
* hsaIdentity 1..1 string "hsaIdentity" "hsaIdentity"
* hsaJpegLogotype 0..1 string "hsaJpegLogotype" "hsaJpegLogotype"
* invoiceAddress 0..1 BackboneElement "invoiceAddress" "invoiceAddress"
  * addressLine 1..* string "addressLine" "addressLine"
* jpegPhoto 0..1 string "jpegPhoto" "jpegPhoto"
* labeledUri 0..1 string "labeledUri" "labeledUri"
* location 0..1 string "location" "location"
* webPage1177 0..1 string "webPage1177" "webPage1177"
* managements 1..1 BackboneElement "managements" "managements"
  * management 0..* string "management" "management"
* municipality 0..1 string "municipality" "municipality"
* municipalityCode 0..1 string "municipalityCode" "municipalityCode"
* municipalitySection 0..1 string "municipalitySection" "municipalitySection"
* getHsaUnitName 1..1 string "getHsaUnitName" "getHsaUnitName Heter name i schemat."
* patientInformation 0..1 string "patientInformation" "patientInformation"
* postalAddress 0..1 BackboneElement "postalAddress" "postalAddress"
  * addressLine 1..* string "addressLine" "addressLine"
* postalCode 0..1 string "postalCode" "postalCode"
* priceInformation 0..1 string "priceInformation" "priceInformation"
* publicName 1..1 string "publicName" "publicName"
* relatedUnits 1..1 BackboneElement "relatedUnits" "relatedUnits"
  * relatedUnit 0..* string "relatedUnit" "relatedUnit"
* route 0..1 string "route" "route"
* street 0..1 string "street" "street"
* surgeryHours 1..1 BackboneElement "surgeryHours" "surgeryHours"
  * surgeryHour 0..* BackboneElement "surgeryHour" "surgeryHour"
    * fromDay 1..1 integer "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * fromTime2 1..1 string "fromTime2" "fromTime2"
    * toDay 1..1 integer "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * toTime2 1..1 string "toTime2" "toTime2"
    * comment 1..1 string "comment" "comment"
* switchboardNumber 0..1 string "switchboardNumber" "switchboardNumber"
* telephoneHours 1..1 BackboneElement "telephoneHours" "telephoneHours"
  * telephoneHour 0..* BackboneElement "telephoneHour" "telephoneHour"
    * fromDay 1..1 integer "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * fromTime2 1..1 string "fromTime2" "fromTime2"
    * toDay 1..1 integer "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * toTime2 1..1 string "toTime2" "toTime2"
    * comment 1..1 string "comment" "comment"
* telephoneNumbers 1..1 BackboneElement "telephoneNumbers" "telephoneNumbers"
  * telephoneNumber 0..* string "telephoneNumber" "telephoneNumber"
* textTelephoneNumbers 1..1 BackboneElement "textTelephoneNumbers" "textTelephoneNumbers"
  * textTelephoneNumber 0..* string "textTelephoneNumber" "textTelephoneNumber"
* unitExtraInformation 0..1 string "unitExtraInformation" "unitExtraInformation"
* unitFunctions 1..1 BackboneElement "unitFunctions" "unitFunctions"
  * unitFunction 0..* BackboneElement "unitFunction" "unitFunction"
    * hsaUnitFunctionName 1..1 string "hsaUnitFunctionName" "hsaUnitFunctionName Heter name i schemat."
    * telephoneHours 1..1 BackboneElement "telephoneHours" "telephoneHours"
      * telephoneHour 0..* BackboneElement "telephoneHour" "telephoneHour"
        * fromDay 1..1 integer "fromDay" "fromDay"
        * fromTime 1..1 time "fromTime" "fromTime"
        * fromTime2 1..1 string "fromTime2" "fromTime2"
        * toDay 1..1 integer "toDay" "toDay"
        * toTime 1..1 time "toTime" "toTime"
        * toTime2 1..1 string "toTime2" "toTime2"
        * comment 1..1 string "comment" "comment"
    * telephoneNumbers 1..1 BackboneElement "telephoneNumbers" "telephoneNumbers"
      * telephoneNumber 0..* string "telephoneNumber" "telephoneNumber"
* unitTemporaryInformation 0..1 BackboneElement "unitTemporaryInformation" "unitTemporaryInformation"
  * fromDate 1..1 string "fromDate" "fromDate"
  * toDate 1..1 string "toDate" "toDate"
  * comment 1..1 string "comment" "comment"
* visitingHours 1..1 BackboneElement "visitingHours" "visitingHours"
  * visitingHour 0..* BackboneElement "visitingHour" "visitingHour"
    * fromDay 1..1 integer "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * fromTime2 1..1 string "fromTime2" "fromTime2"
    * toDay 1..1 integer "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * toTime2 1..1 string "toTime2" "toTime2"
    * comment 1..1 string "comment" "comment"
* visitingRuleAge 0..1 BackboneElement "visitingRuleAge" "visitingRuleAge"
  * from 1..1 integer "from" "from"
  * to 1..1 integer "to" "to"
* visitingRuleReferral 0..1 string "visitingRuleReferral" "visitingRuleReferral"
* visitingRules 0..1 string "visitingRules" "visitingRules"
* referralReceiver 0..1 boolean "referralReceiver" "referralReceiver"
* referralTypes 1..1 BackboneElement "referralTypes" "referralTypes"
  * referralType 0..* string "referralType" "referralType"
* DN 1..1 string "DN" "DN"
