// Genererad från XSD för se.apotekensservice.lf v7.0 (ingen TKB finns i källan; scripts/xsd_to_ig.py)
// Kontrakt: LasLFVardsystem v4.1
// Genererad: 2026-09-26

Logical: LasLFVardsystem
Id: laslfvardsystem
Title: "LasLFVardsystem — Response"
Description: """
  Logisk modell för svaret i LasLFVardsystem
  (urn:riv:se.apotekensservice:lf:LasLFVardsystemResponder:4, LasLFVardsystemResponseType).
"""
Characteristics: #can-be-target
* lakemedelsforteckning 0..* BackboneElement "lakemedelsforteckning" "Patientens läkemedelsförteckning. Om patienten saknar poster i läkemedelsförteckningen så returneras en tom lista."
  * aktorsExpeditionsId 1..1 string "aktorsExpeditionsId" "Aktörens expeditionsId"
  * antalForpackningar 0..1 integer "antalForpackningar" "Antal förpackningar av utlämnad vara. Obligatorisk parameter om posten ej är en dosdispenserad artikel"
  * antalPillerKlartext 0..1 string "antalPillerKlartext" "Summa antal avdelade doser inklusive enhet. Angiven om posten är en dosdispenserad artikel."
  * artikelinformation 1..1 BackboneElement "artikelinformation" "Information om expedierad artikel."
    * antalEnhet 0..1 string "antalEnhet" "Antalets enhet. Exempelvis 'styck' eller 'milliliter'."
    * antalIForpackning 0..1 decimal "antalIForpackning" "Antal i förpackning. Numerisk angivelse, exempelvis '0,72'."
    * antalYtterstaForpackning 0..1 integer "antalYtterstaForpackning" "Antal multipel 2. Antal yttersta förpackningar för artikeln, exempelvis '6'."
    * antalYttreForpackning 0..1 integer "antalYttreForpackning" "Antal multipel 1. Antal yttre förpackningar som varan har, exempelvis '5'."
    * atckod 0..1 string "atckod" "ATC-kod vid inläsningstillfället."
    * atckodKlartext 0..1 string "atckodKlartext" "Verksamt ämne vid inläsningstillfället."
    * forpackningsstorlek 0..1 string "forpackningsstorlek" "Förpackningsstorlek vid inläsningstillfället, exempelvis '6x5x0,72 milliliter'. Ej angivet för dosdispenserade artiklar."
    * forpackningstyp 0..1 string "forpackningstyp" "Beskrivning av artikelns förpackningstyp vid inläsningstillfället."
    * intressent 0..1 string "intressent" "Ansvarig intressent för artikeln. Värde kan hämtas från olika fält i VARA beroende på artikel. Exempelvis parallellimportör."
    * lakemedelsform 0..1 string "lakemedelsform" "Läkemedelsform vid inläsningstillfället."
    * lakemedelsformKod 0..1 string "lakemedelsformKod" "Kod för läkemedelsform (beredningsformkod)."
    * nplPackid 1..1 string "nplPackid" "Identitet på förskrivet läkemedel som har NPL Pack-id alternativt SB Pack-id."
    * produktnamn 0..1 string "produktnamn" "Läkemedelsnamn vid inläsningstillfället."
    * styrka 0..1 decimal "styrka" "Numerisk styrka, exempelvis '20.0'."
    * styrkaEnhet 0..1 string "styrkaEnhet" "Styrkans enhet, exempelvis 'mg'."
    * styrkaKlartext 0..1 string "styrkaKlartext" "Styrka i klartext vid inläsningstillfället."
  * borttagen 1..1 boolean "borttagen" "Markering om posten är borttagen. Sant om posten är borttagen, annars falskt."
  * borttagsdatum 0..1 dateTime "borttagsdatum" "Datum då posten blev markerad som borttagen. Endast angiven om borttagen är sant."
  * borttagsorsak 0..1 string "borttagsorsak" "Kommentar för borttagen post. Endast angiven om borttagen är sant."
  * borttagstyp 0..1 string "borttagstyp" "Typ av borttag som gäller för posten. Endast angiven om borttagen är sant. Möjliga värden är: Synlig, Begränsad synlighet"
  * borttagstypHeltal 0..1 integer "borttagstypHeltal" "Typ av borttag som gäller för posten. Endast angiven om borttagen är sant. Möjliga värden är: 0 - Synlig, 1 - Begränsad synlighet"
  * doseringstext 1..1 string "doseringstext" "Doseringsanvisning."
  * expeditionsId 0..1 string "expeditionsId" "ExpeditionsId"
  * expeditionsdatum 1..1 dateTime "expeditionsdatum" "Datum för expedition på apotek."
  * forskrivararbetsplatsnamn 0..1 string "forskrivararbetsplatsnamn" "Förskrivarens arbetsplatsnamn"
  * forskrivararbetsplatsort 0..1 string "forskrivararbetsplatsort" "Förskrivarens arbetsplatsort"
  * forskrivarnamn 0..1 string "forskrivarnamn" "Förskrivarens namn"
  * forskrivarpostadress 0..1 string "forskrivarpostadress" "Förskrivarens postadress"
  * forskrivarpostnummer 0..1 string "forskrivarpostnummer" "Förskrivarens postnummer"
  * forskrivarspecialiteter 0..* string "forskrivarspecialiteter" "Förskrivarens specialitet i klartext"
  * forskrivaryrke 0..1 string "forskrivaryrke" "Förskrivarens yrke i klartext"
  * mangd 1..1 string "mangd" "Mängd"
  * radid 1..1 string "radid" "Unikt id för posten i läkemedelsförteckningen. (xs:long i schemat.)"
  * radnummer 0..1 integer "radnummer" "Radnummer för expedierad vara i aktuell expedition. Obligatorisk som indata dock ej som utdata."
* patient 1..1 BackboneElement "patient" "Information om patienten vars läkemedelsförteckning man hämtat. Om patienten är markerad som Avliden så returneras ej läkemedelsförteckning."
  * avliden 1..1 boolean "avliden" "Anger om patienten är markerad som avliden i FOLK. Sant om personen är markerad som avliden, annars falskt."
  * efternamn 0..1 string "efternamn" "Patientens efternamn som registrerat i FOLK."
  * fornamn 0..1 string "fornamn" "Patientens förnamn som registrerat i FOLK."
  * personnummer 0..1 string "personnummer" "Patientens personnummer."
* varningsnivaUppnadd 1..1 boolean "varningsnivaUppnadd" "Flagga som anger om förskrivarens antal läsningar det senaste dygnet överskridit varningsnivå. Sant om varningsnivå har uppnåtts, annars falskt."
* avPatientSparradePosterArBorttagna 1..1 boolean "avPatientSparradePosterArBorttagna" "Markering som anger om poster plockats bort ur resultatet pga att patienten spärrat dessa, dvs det finns poster som är spärrade och därför inte är med i resultatet. (Refererat element ur LasLFVardsystemResponder_4.1_ext.xsd, namnrymd urn:riv:se.apotekensservice:lf:LasLFVardsystemResponder:4.1.)"
