// Genererad från XSD för clinicalprocess.logistics.cervixscreening v1.0_RC4 (Genererad ur scheman i riv.clinicalprocess.logistics.cervixscreening, tagg 1.0_RC4; scripts/xsd_to_ig.py; scripts/xsd_to_ig.py)
// Kontrakt: ProcessCervixScreeningInformation v1.0
// Genererad: 2026-09-26

Logical: ProcessCervixScreeningInformationRequest
Id: processcervixscreeninginformation-request
Title: "ProcessCervixScreeningInformation — Request"
Description: """
  Logisk modell för begäran i ProcessCervixScreeningInformation
  (urn:riv:clinicalprocess:logistics:cervixscreening:ProcessCervixScreeningInformationResponder:1, ProcessCervixScreeningInformationType), inklusive SOAP-huvuden enligt WSDL.
"""
Characteristics: #can-be-target
* logicalAddress 1..1 string "logicalAddress" "SOAP-huvud LogicalAddress. The organisation number of the receiving insurance institution"
* cervixScreeningInformation 1..1 BackboneElement "cervixScreeningInformation" "cervixScreeningInformation"
  * subjectOfCare 1..1 BackboneElement "subjectOfCare" "subjectOfCare"
    * personId 1..1 BackboneElement "personId" "personId"
      * root 1..1 string "root" "root"
      * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
  * sendingRegion 1..1 BackboneElement "sendingRegion" "sendingRegion"
    * region 1..1 BackboneElement "region" "region"
      * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
        * root 1..1 string "root" "root"
        * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
      * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
    * careGiver 0..1 BackboneElement "careGiver" "careGiver"
      * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
        * root 1..1 string "root" "root"
        * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
      * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
    * careUnit 0..1 BackboneElement "careUnit" "careUnit"
      * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
        * root 1..1 string "root" "root"
        * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
      * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
  * exclusion 0..1 BackboneElement "exclusion" "exclusion"
    * reason 1..1 BackboneElement "reason" "reason"
      * cVCode 1..1 string "cVCode" "cVCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * registeredAt 1..1 string "registeredAt" "registeredAt"
    * originalRegion 1..1 BackboneElement "originalRegion" "originalRegion"
      * region 1..1 BackboneElement "region" "region"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
      * careGiver 0..1 BackboneElement "careGiver" "careGiver"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
      * careUnit 0..1 BackboneElement "careUnit" "careUnit"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
  * followUpGroups 0..* BackboneElement "followUpGroups" "followUpGroups"
    * followUpGroupType 1..1 BackboneElement "followUpGroupType" "followUpGroupType Heter type i schemat."
      * cVCode 1..1 string "cVCode" "cVCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * inclusionDate 1..1 string "inclusionDate" "inclusionDate"
    * originalRegion 1..1 BackboneElement "originalRegion" "originalRegion"
      * region 1..1 BackboneElement "region" "region"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
      * careGiver 0..1 BackboneElement "careGiver" "careGiver"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
      * careUnit 0..1 BackboneElement "careUnit" "careUnit"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
  * plannedInvitation 0..1 BackboneElement "plannedInvitation" "plannedInvitation"
    * date 1..1 string "date" "date"
    * reason 0..1 string "reason" "reason"
  * specimen 0..1 BackboneElement "specimen" "specimen"
    * specimenDate 1..1 string "specimenDate" "specimenDate"
    * originalRegion 1..1 BackboneElement "originalRegion" "originalRegion"
      * region 1..1 BackboneElement "region" "region"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
      * careGiver 0..1 BackboneElement "careGiver" "careGiver"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
      * careUnit 0..1 BackboneElement "careUnit" "careUnit"
        * organisationId 1..1 BackboneElement "organisationId" "organisationId Heter id i schemat."
          * root 1..1 string "root" "root"
          * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
        * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
    * HPVstatusList 0..* BackboneElement "HPVstatusList" "HPVstatusList"
      * hPVstatusValue 1..1 BackboneElement "hPVstatusValue" "hPVstatusValue Heter value i schemat."
        * cVCode 1..1 string "cVCode" "cVCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
