// Genererad från XSD för financial.billing.claim v1.1 (Genererad ur scheman i riv.financial.billing.claim, tagg 1.1; scripts/xsd_to_ig.py)
// Kontrakt: ProcessClaimSpecification v1.1
// Genererad: 2026-09-26

Logical: ProcessClaimSpecificationRequest
Id: processclaimspecification-request
Title: "ProcessClaimSpecification — Request"
Description: """
  Logisk modell för begäran i ProcessClaimSpecification
  (urn:riv:financial:billing:claim:ProcessClaimSpecificationResponder:1, ProcessClaimSpecificationType), inklusive SOAP-huvuden enligt WSDL.
"""
Characteristics: #can-be-target
* logicalAddress 1..1 string "logicalAddress" "SOAP-huvud LogicalAddress. The organisation number of the receiving county council"
* claimSpecification 1..1 BackboneElement "claimSpecification" "claimSpecification"
  * processClaimSpecificationId 1..1 string "processClaimSpecificationId" "processClaimSpecificationId Heter id i schemat."
  * issueDate 1..1 string "issueDate" "issueDate"
  * issueTime 0..1 string "issueTime" "issueTime"
  * typeOfInvoice 1..1 string "typeOfInvoice" "typeOfInvoice"
  * invoiceId 0..1 string "invoiceId" "invoiceId"
  * invoiceDateOfIssue 0..1 string "invoiceDateOfIssue" "invoiceDateOfIssue"
  * referenceToInvoice 0..1 string "referenceToInvoice" "referenceToInvoice"
  * referenceToProcessClaimSpecificationId 0..1 string "referenceToProcessClaimSpecificationId" "referenceToProcessClaimSpecificationId"
  * payableAmount 1..1 BackboneElement "payableAmount" "payableAmount"
    * amount 1..1 decimal "amount" "amount"
    * currency 1..1 BackboneElement "currency" "currency"
      * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 0..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
  * unspecified 0..* BackboneElement "unspecified" "unspecified"
    * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
    * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
  * supplierParty 1..1 BackboneElement "supplierParty" "supplierParty"
    * identification 1..2 BackboneElement "identification" "identification"
      * root 1..1 string "root" "root"
      * iiExtension 1..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * sellerContact 0..1 BackboneElement "sellerContact" "sellerContact"
      * contactName 0..1 string "contactName" "contactName Heter name i schemat."
      * telephone 0..1 string "telephone" "telephone"
      * electronicMail 0..1 string "electronicMail" "electronicMail"
  * customerParty 1..1 BackboneElement "customerParty" "customerParty"
    * identification 1..2 BackboneElement "identification" "identification"
      * root 1..1 string "root" "root"
      * iiExtension 1..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * buyerContact 0..1 BackboneElement "buyerContact" "buyerContact"
      * contactName 0..1 string "contactName" "contactName Heter name i schemat."
      * telephone 0..1 string "telephone" "telephone"
      * electronicMail 0..1 string "electronicMail" "electronicMail"
  * healthCareServicesSpecificationLine 0..* BackboneElement "healthCareServicesSpecificationLine" "healthCareServicesSpecificationLine"
    * patientInformation 1..1 BackboneElement "patientInformation" "patientInformation"
      * patientIdentity 1..1 BackboneElement "patientIdentity" "patientIdentity"
        * root 1..1 string "root" "root"
        * iiExtension 1..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * patientOtherInformation 1..1 BackboneElement "patientOtherInformation" "patientOtherInformation"
        * county 1..1 BackboneElement "county" "county"
          * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * municipality 1..1 BackboneElement "municipality" "municipality"
          * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * listingLocalAuthoritiesNumber 0..1 BackboneElement "listingLocalAuthoritiesNumber" "listingLocalAuthoritiesNumber"
          * root 1..1 string "root" "root"
          * iiExtension 1..1 string "iiExtension" "iiExtension Heter extension i schemat."
        * LMACardNumber 0..1 string "LMACardNumber" "LMACardNumber"
        * gender 0..1 BackboneElement "gender" "gender"
          * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * EUCardNumber 0..1 string "EUCardNumber" "EUCardNumber"
        * unspecified 0..* BackboneElement "unspecified" "unspecified"
          * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
          * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
    * healthcarePerformed 1..* BackboneElement "healthcarePerformed" "healthcarePerformed"
      * lineId 1..1 string "lineId" "lineId"
      * careContactId 0..1 string "careContactId" "careContactId"
      * referenceToLineId 0..1 string "referenceToLineId" "referenceToLineId"
      * reasonForCredit 0..1 string "reasonForCredit" "reasonForCredit"
      * unspecified 0..* BackboneElement "unspecified" "unspecified"
        * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
        * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
      * paymentCommitment 0..1 BackboneElement "paymentCommitment" "paymentCommitment"
        * remittanceNumber 0..1 string "remittanceNumber" "remittanceNumber"
        * paymentCommitmentNumber 0..1 string "paymentCommitmentNumber" "paymentCommitmentNumber"
        * typeOfAgreement 0..1 string "typeOfAgreement" "typeOfAgreement"
        * typeOfChapter 0..1 string "typeOfChapter" "typeOfChapter"
        * agreementInRiksavtalet 0..1 string "agreementInRiksavtalet" "agreementInRiksavtalet"
        * typeOfReimbursement 0..1 string "typeOfReimbursement" "typeOfReimbursement"
        * unspecified 0..* BackboneElement "unspecified" "unspecified"
          * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
          * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
      * healthcareCategory 1..1 BackboneElement "healthcareCategory" "healthcareCategory"
        * typeOfCare 1..1 BackboneElement "typeOfCare" "typeOfCare"
          * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * publicCare 0..1 boolean "publicCare" "publicCare"
        * plannedHealthcare 1..1 boolean "plannedHealthcare" "plannedHealthcare"
        * typeOfVisit 0..1 string "typeOfVisit" "typeOfVisit"
        * unspecified 0..* BackboneElement "unspecified" "unspecified"
          * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
          * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
      * timespan 1..1 BackboneElement "timespan" "timespan"
        * healthcareVisitDateTime 1..1 BackboneElement "healthcareVisitDateTime" "healthcareVisitDateTime"
          * careVisitDate 1..1 string "careVisitDate" "careVisitDate"
          * careVisitTime 0..1 string "careVisitTime" "careVisitTime"
        * healthcareDischargeDateTime 0..1 BackboneElement "healthcareDischargeDateTime" "healthcareDischargeDateTime"
          * careDischargeDate 1..1 string "careDischargeDate" "careDischargeDate"
          * careDischargeTime 0..1 string "careDischargeTime" "careDischargeTime"
        * invoicePeriod 0..1 BackboneElement "invoicePeriod" "invoicePeriod"
          * start 0..1 string "start" "start"
          * end 0..1 string "end" "end"
        * numberOfDays 0..1 BackboneElement "numberOfDays" "numberOfDays"
          * onLeave 0..1 string "onLeave" "onLeave"
          * inCare 0..1 string "inCare" "inCare"
      * healthcareUnit 1..1 BackboneElement "healthcareUnit" "healthcareUnit"
        * careUnitId 0..1 BackboneElement "careUnitId" "careUnitId"
          * root 1..1 string "root" "root"
          * iiExtension 1..1 string "iiExtension" "iiExtension Heter extension i schemat."
        * careUnitName 1..1 string "careUnitName" "careUnitName"
        * professionCodeForHealthcare 0..1 string "professionCodeForHealthcare" "professionCodeForHealthcare"
        * unspecified 0..* BackboneElement "unspecified" "unspecified"
          * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
          * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
      * categorization 0..1 BackboneElement "categorization" "categorization"
        * productCategory 0..1 string "productCategory" "productCategory"
        * priceList 0..1 string "priceList" "priceList"
        * DRGCost 0..1 BackboneElement "DRGCost" "DRGCost"
          * DRGCode 0..1 BackboneElement "DRGCode" "DRGCode"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
          * DRGPrice 0..1 BackboneElement "DRGPrice" "DRGPrice"
            * amount 1..1 decimal "amount" "amount"
            * currency 1..1 BackboneElement "currency" "currency"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
          * extendedAllowanceCareTime 0..1 BackboneElement "extendedAllowanceCareTime" "extendedAllowanceCareTime"
            * amount 1..1 decimal "amount" "amount"
            * currency 1..1 BackboneElement "currency" "currency"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
          * extendedAllowanceCost 0..1 BackboneElement "extendedAllowanceCost" "extendedAllowanceCost"
            * amount 1..1 decimal "amount" "amount"
            * currency 1..1 BackboneElement "currency" "currency"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
        * patientSpecificCare 0..* BackboneElement "patientSpecificCare" "patientSpecificCare"
          * patientSpecificCareCode 0..1 string "patientSpecificCareCode" "patientSpecificCareCode"
          * patientSpecificCareCodeName 0..1 string "patientSpecificCareCodeName" "patientSpecificCareCodeName"
          * numberOfPatientSpecificCare 0..1 integer "numberOfPatientSpecificCare" "numberOfPatientSpecificCare"
          * patientSpecificCarePrice 0..1 BackboneElement "patientSpecificCarePrice" "patientSpecificCarePrice"
            * amount 1..1 decimal "amount" "amount"
            * currency 1..1 BackboneElement "currency" "currency"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
          * patientSpecificCareTotalAmount 0..1 BackboneElement "patientSpecificCareTotalAmount" "patientSpecificCareTotalAmount"
            * amount 1..1 decimal "amount" "amount"
            * currency 1..1 BackboneElement "currency" "currency"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
          * unspecified 0..* BackboneElement "unspecified" "unspecified"
            * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
            * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
      * invoicedAmountDetails 1..1 BackboneElement "invoicedAmountDetails" "invoicedAmountDetails"
        * patientCareInvoiceGrossAmount 1..1 BackboneElement "patientCareInvoiceGrossAmount" "patientCareInvoiceGrossAmount"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * patientCareInvoiceNetAmount 1..1 BackboneElement "patientCareInvoiceNetAmount" "patientCareInvoiceNetAmount"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * patientCareAllowance 0..1 BackboneElement "patientCareAllowance" "patientCareAllowance"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * patientCareDiscount 0..1 BackboneElement "patientCareDiscount" "patientCareDiscount"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * patientCareCharge 0..1 BackboneElement "patientCareCharge" "patientCareCharge"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * outPatientCareFee 0..1 BackboneElement "outPatientCareFee" "outPatientCareFee"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * outPatientCareFeePaid 0..1 BackboneElement "outPatientCareFeePaid" "outPatientCareFeePaid"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * patientFeeReducedCategory 0..1 string "patientFeeReducedCategory" "patientFeeReducedCategory"
        * patientFreePassCauseIndicator 0..1 boolean "patientFreePassCauseIndicator" "patientFreePassCauseIndicator"
        * inpatientCareFee 0..1 BackboneElement "inpatientCareFee" "inpatientCareFee"
          * amount 1..1 decimal "amount" "amount"
          * currency 1..1 BackboneElement "currency" "currency"
            * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
            * codeSystem 0..1 string "codeSystem" "codeSystem"
            * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
            * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
            * displayName 0..1 string "displayName" "displayName"
            * originalText 0..1 string "originalText" "originalText"
        * unspecified 0..* BackboneElement "unspecified" "unspecified"
          * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
          * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
      * activity 1..1 BackboneElement "activity" "activity"
        * medicalFieldCode 1..1 string "medicalFieldCode" "medicalFieldCode"
        * businessClassification 0..1 BackboneElement "businessClassification" "businessClassification"
          * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * careLevel 0..1 string "careLevel" "careLevel"
        * unspecified 0..* BackboneElement "unspecified" "unspecified"
          * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
          * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
      * diagnosis 0..1 BackboneElement "diagnosis" "diagnosis"
        * inpatientCareDiagnosis 0..1 BackboneElement "inpatientCareDiagnosis" "inpatientCareDiagnosis"
          * mainDiagnosis 1..1 BackboneElement "mainDiagnosis" "mainDiagnosis"
            * diagnosisCode 1..1 BackboneElement "diagnosisCode" "diagnosisCode"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
          * biDiagnosis 0..* BackboneElement "biDiagnosis" "biDiagnosis"
            * diagnosisCode 1..1 BackboneElement "diagnosisCode" "diagnosisCode"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
        * outpatientCareDiagnosis 0..1 BackboneElement "outpatientCareDiagnosis" "outpatientCareDiagnosis"
          * mainDiagnosis 1..1 BackboneElement "mainDiagnosis" "mainDiagnosis"
            * diagnosisCode 1..1 BackboneElement "diagnosisCode" "diagnosisCode"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
          * biDiagnosis 0..* BackboneElement "biDiagnosis" "biDiagnosis"
            * diagnosisCode 1..1 BackboneElement "diagnosisCode" "diagnosisCode"
              * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
              * codeSystem 0..1 string "codeSystem" "codeSystem"
              * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
              * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
              * displayName 0..1 string "displayName" "displayName"
              * originalText 0..1 string "originalText" "originalText"
      * treatment 0..1 BackboneElement "treatment" "treatment"
        * typeOfTreatment 0..* BackboneElement "typeOfTreatment" "typeOfTreatment"
          * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * ATC 0..* BackboneElement "ATC" "ATC"
          * cvCode 0..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * unspecified 0..* BackboneElement "unspecified" "unspecified"
          * unspecifiedText 1..1 string "unspecifiedText" "unspecifiedText Heter text i schemat."
          * unspecifiedType 0..1 string "unspecifiedType" "unspecifiedType Heter type i schemat."
