// Genererad från XSD för se.apotekensservice.expo v2.0 (ingen TKB finns i källan; scripts/xsd_to_ig.py)
// Kontrakt: HamtaApoteksinfoEget v5.0
// Genererad: 2026-09-26

Logical: HamtaApoteksinfoEget
Id: hamtaapoteksinfoeget
Title: "HamtaApoteksinfoEget — Response"
Description: """
  Logisk modell för svaret i HamtaApoteksinfoEget
  (urn:riv:se.apotekensservice:expo:HamtaApoteksinfoEgetResponder:5, HamtaApoteksinfoEgetResponseType).
"""
Characteristics: #can-be-target
* expeditionsstalleLista 1..* BackboneElement "expeditionsstalleLista" "Lista innehållande en eller flera expeditionsstallen."
  * aktorsnamn 1..1 string "aktorsnamn" "Aktörens namn."
  * allmTelefon 1..1 string "allmTelefon" "Expeditionsställets allmänna telefonnummer."
  * apoteksId 1..1 string "apoteksId" "GLN-kod för unik identifiering av apotek."
  * besoksAdress 1..1 string "besoksAdress" "Expeditionsställets besöksadress."
  * besoksort 1..1 string "besoksort" "Expeditionsställets ort (besöksort)."
  * dosmottagareLista 0..* BackboneElement "dosmottagareLista" "Information om dosmottagare."
    * adress 0..1 string "adress" "Adress till dosmottagare. Obligatorisk om typ = 'D'."
    * apoteksIdDosmottagare 0..1 string "apoteksIdDosmottagare" "Apoteks-id för dosmottagare om dosmottagare är av typen apotek."
    * arbetsplatskod 0..1 string "arbetsplatskod" "Arbetsplatskod till dosmottagare. Är aktuellt om dosmottagare t ex är en distriktsläkarmottagning."
    * avdelning 0..1 string "avdelning" "Avdelning inom dosmottagare."
    * dosmottagarId 1..1 string "dosmottagarId" "Dosmottagarens identitet, dosproducentens identitet för dosmottagaren t ex kundnummer, GLN-kod. Unikt inom dosapoteket."
    * kommunkod 0..1 string "kommunkod" "Kommunkod till vilken dosmottagarens tillhör. Kod enligt SCB."
    * lanskod 0..1 string "lanskod" "Länskod till vilken dosmottagaren tillhör. Kod enligt SCB."
    * mottagarnamn 1..1 string "mottagarnamn" "Namn på dosmottagare."
    * postnummer 0..1 string "postnummer" "Postnummer till dosmottagare."
    * postort 0..1 string "postort" "Arbetsplatsort till dosmottagare. Obligatorisk om typ = 'D'."
    * typ 1..1 string "typ" "Typ av dosmottagare, kan antingen vara Apotek (där dospatienterna kan hämta sina dosleveranser) eller direktleverans, t ex vårdboende, distriktssköterska. Giltiga värden: D (direktleverans) eller A (apotek)."
  * eRecept 1..1 boolean "eRecept" "Flagga som anger om expeditionsstället är ett apotek som kan hantera e-recept för besökande privat personer."
  * eReceptDjur 1..1 boolean "eReceptDjur" "Markering gällande om apoteket kan expediera elektroniska djurrecept."
  * faxnummer 0..1 string "faxnummer" "Expeditionsställets faxnummer."
  * huvudOrgTypKod 0..1 string "huvudOrgTypKod" "Möjliga värden: ADM, AP, DIAP, DJUR, DX, OAP, SA, TVAP ADM En organisatiorisk enhet inom ett företag som har rent administrativa uppgifter. AP Apotek för allmänheten - enhet för detaljhandel med läkemedel med farmaceutisk bemanning under öppethållandet. DIAP Distansapotek - Större apoteksenhet med ansvar att kunna distribuera apoteksvaror direkt till avtalskunder, apoteksombud eller privatpersoner DJUR Ett apotek som har utökat djursortiment. DX Dosapotek - enhet för produktion av dosdispenserade läkemedel. OAP Övriga apotek - gammal definition av apotek. Bör ej användas. SA Sjukhusapotek - apotek som ger service till slutenvårdsenheter TVAP Enhet som på beställning tillverkar specifika individanpassade läkemedel."
  * kommun 1..1 integer "kommun" "Expeditionsställets kommuntillhörighet, kod enligt SCB."
  * kortNamn 0..1 string "kortNamn" "Kortversion på apoteksnamn. Behövs i bla i vårdsystem."
  * lan 1..1 integer "lan" "Expeditionsställets länstillhörighet, kod enligt SCB."
  * namn 1..1 string "namn" "Expeditionsställets officiella namn."
  * oppetHallandeLista 0..* BackboneElement "oppetHallandeLista" "När expeditionsstället har öppet."
    * dagBenamning 0..1 string "dagBenamning" "Exempelvis \"Nyårsafton\"."
    * lunchFrom 0..1 string "lunchFrom" "Om lunchstängt, \"stänger för lunch\". Format: HHmm H=Timme (0-24) m=Minut"
    * lunchTom 0..1 string "lunchTom" "Om lunchstängt, \"Öppnar igen efter lunch kl\". Format: HHmm H=Timme (0-24) m=Minut"
    * oppnar 0..1 string "oppnar" "Öppningstid vardagar/vekodagnr. Format: HHmm H=Timme (0-24) m=Minut"
    * slutDatum 0..1 dateTime "slutDatum" "Sista dagen i en period vid typ N, P eller S. Obligatorisk vid typ P, S eller D. Om typ D är slutdatum = startdatum."
    * stanger 0..1 string "stanger" "Stängningstid vardagar/vekodagnr. Format: HHmm H=Timme (0-24) m=Minut"
    * startDatum 1..1 dateTime "startDatum" "Första dagen i en period vid typ N, P eller S. Vid typ D anges datum för aktuell dag exv 2010-12-24."
    * tfStangtOrsak 0..1 string "tfStangtOrsak" "Orsak till tillfällig stängning."
    * typ 1..1 string "typ" "Typ av öppethållande. N = Normalt P = avvikande under angiven period D = avvikande under angiven dag S = tillfälligt stängt under angiven period"
    * veckodagnr 0..1 string "veckodagnr" "Ett nummer för veckodagen 1-7 för Måndag till Söndag, V för vardagar."
  * orgNr 1..1 string "orgNr" "Aktörens organisationsnummer (xs:long i schemat.)"
  * orgTypADM 1..1 boolean "orgTypADM" "Kod ADM som beskriver typ av expeditionsställe. En organisatiorisk enhet inom ett företag som har rent administrativa uppgifter."
  * orgTypDIST 1..1 boolean "orgTypDIST" "Kod DIST som beskriver typ av expeditionsställe. Distansapotek - Större apoteksenhet med ansvar att kunna distribuera apoteksvaror direkt till avtalskunder, apoteksombud eller privatpersoner"
  * orgTypDJAP 1..1 boolean "orgTypDJAP" "Kod DJAP som beskriver typ av expeditionsställe. Ett apotek som har utökat djursortiment."
  * orgTypDOS 1..1 boolean "orgTypDOS" "Kod DOS som beskriver typ av expeditionsställe. Dosapotek - enhet för produktion av dosdispenserade läkemedel."
  * orgTypEA 1..1 boolean "orgTypEA" "Kod EA som beskriver typ av expeditionsställe. Apotek för allmänheten - enhet för detaljhandel med läkemedel med farmaceutisk bemanning under öppethållandet."
  * orgTypEH 1..1 boolean "orgTypEH" "Kod EH som beskriver typ av expeditionsställe. En enhet som som kan lämna ut e-handel, dit man kan skicka e-handelspacket."
  * orgTypGSL 1..1 boolean "orgTypGSL" "Kod GSL som beskriver typ av expeditionsställe. Alla expeditionställen som säljer sortimentet på 80-listan (t ex shopar) ska ha flaggan satt. \"General Sales list\" - även kallad för \"80-listan\", enbart varor som ej är receptbelagda och som ingår i 80-sortimentet. Alla expeditionställen som säljer sortimentet på 80-listan (t ex shopar) ska ha flaggan satt."
  * orgTypSA 1..1 boolean "orgTypSA" "Kod SA som beskriver typ av expeditionsställe. Sjukhusapotek - apotek som ger service till slutenvårdsenheter."
  * orgTypTILV 1..1 boolean "orgTypTILV" "Kod TILV som beskriver typ av expeditionsställe. Enhet som på beställning tillverkar individanpassade specifika läkemedel."
  * postAdress 1..1 string "postAdress" "Expeditionsställets postAdress."
  * postNr 1..1 string "postNr" "Expeditionsställets postNr."
  * postort 1..1 string "postort" "Expeditionsställets postort."
  * recepturtelefon 0..1 string "recepturtelefon" "Expeditionsställets receptur telefonnummer."
  * slutDatum 0..1 dateTime "slutDatum" "Datum för avslut av verksamhet."
  * startDatum 1..1 dateTime "startDatum" "Datum för start av verksamhet. Det datum som allmänheten kan använda Apoteket."
  * statusDate 0..1 dateTime "statusDate" "Expeditionsställets tillståndsstatus ändringsdatum."
  * tidigareGlnKod 0..1 string "tidigareGlnKod" "Expeditionsställets tidigare ägares GLN."
  * tillstandsstatus 0..1 string "tillstandsstatus" "Expeditionsställets tillståndsstatus."
  * webbadress 0..1 string "webbadress" "Webbadress till apotekets webbtjänster. Apotekens Service använder adressen för att skicka notifieringsmeddelanden. Används endast av dosproducenter."
