// Genererad från XSD för se.apotekensservice.expo v2.0 (ingen TKB finns i källan; scripts/xsd_to_ig.py)
// Kontrakt: SkapaApotek v6.0
// Genererad: 2026-09-26

Logical: SkapaApotekRequest
Id: skapaapotek-request
Title: "SkapaApotek — Request"
Description: """
  Logisk modell för begäran i SkapaApotek
  (urn:riv:se.apotekensservice:expo:SkapaApotekResponder:6, SkapaApotekRequestType), inklusive SOAP-huvuden enligt WSDL.
"""
Characteristics: #can-be-target
* logicalAddress 1..1 string "logicalAddress" "SOAP-huvud LogicalAddress. Orgnr of Apotekens Service AB"
* argosHeader 1..1 BackboneElement "argosHeader" "SOAP-huvud ArgosHeader. Argos header of Apotekens Service AB. Check documentation regarding mandatory fields for this specific service interaction"
  * forskrivarkod 0..1 string "forskrivarkod" "forskrivarkod"
  * legitimationskod 0..1 string "legitimationskod" "legitimationskod"
  * fornamn 0..1 string "fornamn" "fornamn"
  * efternamn 0..1 string "efternamn" "efternamn"
  * yrkesgrupp 0..1 string "yrkesgrupp" "yrkesgrupp"
  * befattningskod 0..1 string "befattningskod" "befattningskod"
  * arbetsplatskod 0..1 string "arbetsplatskod" "arbetsplatskod"
  * arbetsplatsnamn 0..1 string "arbetsplatsnamn" "arbetsplatsnamn"
  * postort 0..1 string "postort" "postort"
  * postadress 0..1 string "postadress" "postadress"
  * postnummer 0..1 string "postnummer" "postnummer"
  * telefonnummer 0..1 string "telefonnummer" "telefonnummer"
  * requestId 0..1 string "requestId" "requestId"
  * rollnamn 0..1 string "rollnamn" "rollnamn"
  * hsaID 0..1 string "hsaID" "hsaID"
  * katalog 0..1 string "katalog" "katalog"
  * organisationsnummer 0..1 string "organisationsnummer" "organisationsnummer"
  * systemnamn 0..1 string "systemnamn" "systemnamn"
  * systemversion 0..1 string "systemversion" "systemversion"
  * systemIp 0..1 string "systemIp" "systemIp"
* allmTelefon 1..1 string "allmTelefon" "Expeditionsställets allmänna telefonnummer."
* besoksAdress 1..1 string "besoksAdress" "Expeditionsställets besöksadress."
* besoksort 1..1 string "besoksort" "Expeditionsställets ort (besöksort)."
* eRecept 1..1 boolean "eRecept" "Flagga som anger om expeditionsstället är ett apotek som kan hantera e-recept för besökande privat personer. Om eRecept är satt så är termerna kortNamn och recepturtelefon obligatoriska."
* eReceptDjur 1..1 boolean "eReceptDjur" "Markering om apoteket kan expediera elektroniska djurrecept eller ej. Om eReceptDjur är satt så är termerna kortNamn och recepturtelefon obligatoriska."
* faxnummer 0..1 string "faxnummer" "Expeditionsställets faxnummer. Obligatoriskt om huvudorganisationskod = DX eller om Organisationskod = DOS"
* huvudOrgTypKod 1..1 string "huvudOrgTypKod" "Huvudtypkoden är till stöd för dagens lösning av vårdsystem. På sikt önskar Apotekens Service AB att dessa koder arbetas bort och byts ut mot organisationstypflaggorna (ADM, DIST, DJAP, DOS, EA, EH, GSL, SA, TILV) Möjliga värden: ADM, AP, DIAP, DJUR, DX, OAP, SA, TVAP ADM En organisatiorisk enhet inom ett företag som har rent administrativa uppgifter. AP Apotek för allmänheten - enhet för detaljhandel med läkemedel med farmaceutisk bemanning under öppethållandet. DIAP Distansapotek - Större apoteksenhet med ansvar att kunna distribuera apoteksvaror direkt till avtalskunder, apoteksombud eller privatpersoner DJUR Ett apotek som har utökat djursortiment. DX Dosapotek - enhet för produktion av dosdispenserade läkemedel. OAP Övriga apotek - gammal definition av apotek. Bör ej användas. SA Sjukhusapotek - apotek som ger service till slutenvårdsenheter TVAP Enhet som på beställning tillverkar specifika individanpassade läkemedel."
* idLista 1..* BackboneElement "idLista" "Lista innehållande en eller flera identifierare för expeditionsstället. En Identitet som ska gälla för ett expeditionsställe kan skickas en eller flera gånger och tas aldrig bort. Vid uppdatering av ett expeditionsställe skickas en eller flera identiteter som identifierare. Obs! GLN-kod måste alltid skickas med."
  * exportId 0..1 boolean "exportId" "Obligatorisk för identitet med glnKod. Måste vara true om eRecept och/eller eReceptDjur är true. ExportId får ej sättas till true för en butikskod (används bara för GLN)."
  * glnKod 0..1 string "glnKod" "Expeditionsställets GLN-kod Måste sättas på en av identiteterna. Endast en glnkod per expeditionsställe är tillåtet."
* kommun 1..1 integer "kommun" "Expeditionsställets kommuntillhörighet, kod enligt SCB."
* kortNamn 0..1 string "kortNamn" "Kortversion på apoteksnamn. Behövs i bla i vårdsystem. Om termen eRecept och/eller eReceptDjur är satt så är termerna kortNamn och recepturtelefon obligatoriska."
* lan 1..1 integer "lan" "Expeditionsställets länstillhörighet, kod enligt SCB."
* namn 1..1 string "namn" "Expeditionsställets officiella namn."
* oppetHallandeLista 0..* BackboneElement "oppetHallandeLista" "När expeditionsstället har öppet. Måste skickas med vid varje uppdatering. All tidigare öppethållande data raderas innan det nya öppethållande datat läggs in."
  * dagBenamning 0..1 string "dagBenamning" "Exempelvis \"Nyårsafton\"."
  * lunchFrom 0..1 string "lunchFrom" "Om lunchstängt, \"stänger för lunch\". Format: HHmm H=Timme (0-23) m=Minut (0-59)"
  * lunchTom 0..1 string "lunchTom" "Om lunchstängt, \"Öppnar igen efter lunch kl\". Format: HHmm H=Timme (0-23) m=Minut (0-59)"
  * oppnar 0..1 string "oppnar" "Öppningstid vardagar/vekodagnr. Format: HHmm H=Timme (0-23) m=Minut (0-59)"
  * slutDatum 0..1 dateTime "slutDatum" "Sista dagen i en period vid typ N, P eller S. Obligatorisk vid typ P, S eller D. Om typ D är slutdatum = startdatum."
  * stanger 0..1 string "stanger" "Stängningstid vardagar/vekodagnr. Format: HHmm H=Timme (0-23) m=Minut (0-59)"
  * startDatum 1..1 dateTime "startDatum" "Första dagen i en period vid typ N, P eller S. Vid typ D anges datum för aktuell dag exv 2010-12-23."
  * tfStangtOrsak 0..1 string "tfStangtOrsak" "Orsak till tillfällig stängning."
  * typ 1..1 string "typ" "Typ av öppethållande. N = Normalt P = avvikande under angiven period D = avvikande under angiven dag S = tillfälligt stängt under angiven period"
  * veckodagnr 0..1 string "veckodagnr" "Ett nummer för veckodagen 1-7 för Måndag till Söndag, V för vardagar."
* orgNr 1..1 string "orgNr" "Aktörens organisationsnummer (xs:long i schemat.)"
* orgTypADM 1..1 boolean "orgTypADM" "Kod ADM som beskriver typ av expeditionsställe. En organisatiorisk enhet inom ett företag som har rent administrativa uppgifter."
* orgTypDIST 1..1 boolean "orgTypDIST" "Kod DIST som beskriver typ av expeditionsställe. Distansapotek - Större apoteksenhet med ansvar att kunna distribuera apoteksvaror direkt till avtalskunder, apoteksombud eller privatpersoner"
* orgTypDJAP 1..1 boolean "orgTypDJAP" "Kod DJAP som beskriver typ av expeditionsställe. Ett apotek som har utökat djursortiment."
* orgTypDOS 1..1 boolean "orgTypDOS" "Kod DOS som beskriver typ av expeditionsställe. Dosapotek - enhet för produktion av dosdispenserade läkemedel."
* orgTypEA 1..1 boolean "orgTypEA" "Kod EA som beskriver typ av expeditionsställe. Apotek för allmänheten - enhet för detaljhandel med läkemedel med farmaceutisk bemanning under öppethållandet."
* orgTypEH 1..1 boolean "orgTypEH" "Kod EH som beskriver typ av expeditionsställe. En enhet som som kan lämna ut e-handel, dit man kan skicka e-handelspacket."
* orgTypGSL 1..1 boolean "orgTypGSL" "Kod GSL som beskriver typ av expeditionsställe. Alla expeditionställen som säljer sortimentet på 80-listan (t ex shopar) ska ha flaggan satt. \"General Sales list\" - även kallad för \"80-listan\", enbart varor som ej är receptbelagda och som ingår i 80-sortimentet. Alla expeditionställen som säljer sortimentet på 80-listan (t ex shopar) ska ha flaggan satt."
* orgTypSA 1..1 boolean "orgTypSA" "Kod SA som beskriver typ av expeditionsställe. Sjukhusapotek - apotek som ger service till slutenvårdsenheter."
* orgTypTILV 1..1 boolean "orgTypTILV" "Kod TILV som beskriver typ av expeditionsställe. Enhet som på beställning tillverkar individanpassade specifika läkemedel."
* postAdress 1..1 string "postAdress" "Expeditionsställets postAdress."
* postNr 1..1 string "postNr" "Expeditionsställets postNr."
* postort 1..1 string "postort" "Expeditionsställets postort."
* recepturtelefon 0..1 string "recepturtelefon" "Expeditionsställets receptur telefonnummer. Om termen eRecept och/eller eReceptDjur är satt så är termerna kortNamn och recepturtelefon obligatoriska."
* slutDatum 0..1 dateTime "slutDatum" "Datum för avslut av verksamhet."
* startDatum 1..1 dateTime "startDatum" "Datum för start av verksamhet. Det datum som allmänheten kan använda Apoteket."
* tidigareGlnKod 0..1 string "tidigareGlnKod" "Expeditionsställets tidigare ägares GLN."
