// Genererad från XSD för strategicresourcemanagement.organizational.organization v2.0 (Genererat ur domänens XSD (senaste commit med innehåll, b349285d18c2).; scripts/xsd_to_ig.py)
// Kontrakt: GetUnit v2.0
// Genererad: 2026-09-26

Logical: GetUnit
Id: getunit
Title: "GetUnit — Response"
Description: """
  Logisk modell för svaret i GetUnit
  (urn:riv:strategicresourcemanagement:organizational:organization:GetUnitResponder:2, GetUnitResponseType).
"""
Characteristics: #can-be-target
* ^version = "2.0"
* unit 0..1 BackboneElement "unit" "unit"
  * alternateName 0..* string "alternateName" "alternateName"
  * alternateText 0..1 string "alternateText" "alternateText"
  * businessClassification 0..* BackboneElement "businessClassification" "businessClassification"
    * businessClassificationName 0..1 string "businessClassificationName" "businessClassificationName"
    * businessClassificationCode 0..1 string "businessClassificationCode" "businessClassificationCode"
  * businessType 0..* string "businessType" "businessType"
  * careType 0..* string "careType" "careType"
  * countyName 0..1 string "countyName" "countyName"
  * countyCode 0..1 string "countyCode" "countyCode"
  * description 0..1 string "description" "description"
  * directoryContact 0..1 string "directoryContact" "directoryContact"
  * displayOption 0..1 string "displayOption" "displayOption"
  * dropInHour 0..* BackboneElement "dropInHour" "dropInHour"
    * fromDay 1..1 string "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * toDay 1..1 string "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * comment 0..1 string "comment" "comment"
  * mail 0..1 string "mail" "mail"
  * facsimileTelephoneNumber 0..* string "facsimileTelephoneNumber" "facsimileTelephoneNumber"
  * geographicalCoordinatesRt90 0..1 BackboneElement "geographicalCoordinatesRt90" "geographicalCoordinatesRt90"
    * xCoordinate 1..1 string "xCoordinate" "xCoordinate"
    * yCoordinate 1..1 string "yCoordinate" "yCoordinate"
  * geographicalCoordinatesSWEREF99 0..1 BackboneElement "geographicalCoordinatesSWEREF99" "geographicalCoordinatesSWEREF99"
    * nCoordinate 1..1 string "nCoordinate" "nCoordinate"
    * eCoordinate 1..1 string "eCoordinate" "eCoordinate"
  * healthCareArea 0..1 string "healthCareArea" "healthCareArea"
  * destinationIndicator 0..* string "destinationIndicator" "destinationIndicator"
  * unitHsaId 1..1 string "unitHsaId" "unitHsaId"
  * jpegPhoto 0..1 string "jpegPhoto" "jpegPhoto"
  * jpegLogotype 0..1 string "jpegLogotype" "jpegLogotype"
  * labeledUri 0..1 string "labeledUri" "labeledUri"
  * location 0..1 string "location" "location"
  * webPage1177 0..1 string "webPage1177" "webPage1177"
  * management 0..* string "management" "management"
  * municipalityName 0..1 string "municipalityName" "municipalityName"
  * municipalityCode 0..1 string "municipalityCode" "municipalityCode"
  * unitName 1..1 string "unitName" "unitName"
  * patientInformation 0..1 string "patientInformation" "patientInformation"
  * postalAddress 0..1 BackboneElement "postalAddress" "postalAddress"
    * addressLine 1..* string "addressLine" "addressLine"
  * postalCode 0..1 string "postalCode" "postalCode"
  * priceInformation 0..1 string "priceInformation" "priceInformation"
  * publicName 1..1 string "publicName" "publicName"
  * relatedUnitHsaId 0..* string "relatedUnitHsaId" "relatedUnitHsaId"
  * route 0..1 string "route" "route"
  * smsTelephoneNumber 0..1 string "smsTelephoneNumber" "smsTelephoneNumber"
  * street 0..1 string "street" "street"
  * surgeryHour 0..* BackboneElement "surgeryHour" "surgeryHour"
    * fromDay 1..1 string "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * toDay 1..1 string "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * comment 0..1 string "comment" "comment"
  * switchboardNumber 0..1 string "switchboardNumber" "switchboardNumber"
  * telephoneHour 0..* BackboneElement "telephoneHour" "telephoneHour"
    * fromDay 1..1 string "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * toDay 1..1 string "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * comment 0..1 string "comment" "comment"
  * telephoneNumber 0..* string "telephoneNumber" "telephoneNumber"
  * textTelephoneNumber 0..* string "textTelephoneNumber" "textTelephoneNumber"
  * unitExtraInformation 0..1 string "unitExtraInformation" "unitExtraInformation"
  * unitFunction 0..* BackboneElement "unitFunction" "unitFunction"
    * unitFunctionName 1..1 string "unitFunctionName" "unitFunctionName Heter name i schemat."
    * telephoneHour 0..* BackboneElement "telephoneHour" "telephoneHour"
      * fromDay 1..1 string "fromDay" "fromDay"
      * fromTime 1..1 time "fromTime" "fromTime"
      * toDay 1..1 string "toDay" "toDay"
      * toTime 1..1 time "toTime" "toTime"
      * comment 0..1 string "comment" "comment"
    * telephoneNumber 0..* string "telephoneNumber" "telephoneNumber"
  * unitTemporaryInformation 0..1 BackboneElement "unitTemporaryInformation" "unitTemporaryInformation"
    * fromDate 1..1 string "fromDate" "fromDate"
    * toDate 1..1 string "toDate" "toDate"
    * temporaryInformation 1..1 string "temporaryInformation" "temporaryInformation"
  * visitingHour 0..* BackboneElement "visitingHour" "visitingHour"
    * fromDay 1..1 string "fromDay" "fromDay"
    * fromTime 1..1 time "fromTime" "fromTime"
    * toDay 1..1 string "toDay" "toDay"
    * toTime 1..1 time "toTime" "toTime"
    * comment 0..1 string "comment" "comment"
  * visitingRuleAge 0..1 BackboneElement "visitingRuleAge" "visitingRuleAge"
    * fromAge 1..1 string "fromAge" "fromAge"
    * toAge 1..1 string "toAge" "toAge"
    * comment 0..1 string "comment" "comment"
  * referralRules 0..1 string "referralRules" "referralRules"
  * visitingRules 0..1 string "visitingRules" "visitingRules"
  * unitStartDate 0..1 dateTime "unitStartDate" "unitStartDate"
  * unitEndDate 0..1 dateTime "unitEndDate" "unitEndDate"
  * feignedUnit 0..1 boolean "feignedUnit" "feignedUnit"
