// Genererad från XSD för supportprocess.serviceprovisioning.healthcareoffering v3.0.0 (Genererad ur scheman i riv.supportprocess.serviceprovisioning.healthcareoffering, tagg 3.0 (commit 0e5b32c68d33); scripts/xsd_to_ig.py)
// Kontrakt: GetCareServiceOfferings v3.0
// Genererad: 2026-09-26

Logical: GetCareServiceOfferings
Id: getcareserviceofferings
Title: "GetCareServiceOfferings — Response"
Description: """
  Logisk modell för svaret i GetCareServiceOfferings
  (urn:riv:supportprocess:serviceprovisioning:healthcareoffering:GetCareServiceOfferingsResponder:3, GetCareServiceOfferingsResponseType).
"""
Characteristics: #can-be-target
* careService 0..* BackboneElement "careService" "careService"
  * careServiceId 0..1 BackboneElement "careServiceId" "careServiceId"
    * root 1..1 string "root" "root"
    * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
  * typeOfCareService 1..1 BackboneElement "typeOfCareService" "typeOfCareService"
    * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
    * codeSystem 1..1 string "codeSystem" "codeSystem"
    * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
    * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
    * displayName 0..1 string "displayName" "displayName"
    * originalText 0..1 string "originalText" "originalText"
  * typeOfCareServiceDescription 0..* BackboneElement "typeOfCareServiceDescription" "typeOfCareServiceDescription"
    * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
    * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * role 0..* BackboneElement "role" "role"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
  * validity 1..1 BackboneElement "validity" "Används för att specificera ett datumintervall med hjälp av start- och slutdatum. start: Startdatum på formatet ÅÅÅÅMMDD end: Slutdatum på formatet ÅÅÅÅMMDD"
    * start 0..1 string "start" "start"
    * end 0..1 string "end" "end"
  * careServiceStatus 1..1 code "careServiceStatus" "careServiceStatus"
  * careServiceStatus from CareServiceStatusVS (required)
  * careOption 1..1 boolean "careOption" "careOption"
  * referralRequired 1..1 boolean "referralRequired" "referralRequired"
  * description 0..* BackboneElement "description" "description"
    * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
    * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * role 0..* BackboneElement "role" "role"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
  * indicator 0..* BackboneElement "indicator" "indicator"
    * indicatorId 1..1 BackboneElement "indicatorId" "indicatorId"
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * logicalAddress 1..1 string "logicalAddress" "logicalAddress"
  * requestTemplate 0..1 BackboneElement "requestTemplate" "requestTemplate"
    * address 1..1 uri "address" "address"
    * mandatory 1..1 boolean "mandatory" "mandatory"
  * providingOrganization 1..1 BackboneElement "providingOrganization" "providingOrganization"
    * providingOrganizationId 1..1 BackboneElement "providingOrganizationId" "providingOrganizationId Heter id i schemat."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * providingOrganizationName 1..1 string "providingOrganizationName" "providingOrganizationName Heter name i schemat."
    * management 1..1 BackboneElement "management" "management"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * publicProvider 1..1 boolean "publicProvider" "publicProvider"
    * description 0..* BackboneElement "description" "description"
      * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
      * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * role 0..* BackboneElement "role" "role"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
  * performingOrganization 1..1 BackboneElement "performingOrganization" "performingOrganization"
    * performingOrganizationId 1..* BackboneElement "performingOrganizationId" "performingOrganizationId Heter id i schemat."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * performingOrganizationName 0..* string "performingOrganizationName" "performingOrganizationName Heter name i schemat."
    * responsibleOrganization 1..1 BackboneElement "responsibleOrganization" "responsibleOrganization"
      * responsibleOrganizationId 1..1 BackboneElement "responsibleOrganizationId" "responsibleOrganizationId Heter id i schemat."
        * root 1..1 string "root" "root"
        * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * responsibleOrganizationName 1..1 string "responsibleOrganizationName" "responsibleOrganizationName Heter name i schemat."
      * description 0..* BackboneElement "description" "description"
        * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
        * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
          * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 1..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * role 0..* BackboneElement "role" "role"
          * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
          * codeSystem 1..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
    * availableTime 0..* string "availableTime" "availableTime"
    * typeOfBusiness 0..* BackboneElement "typeOfBusiness" "typeOfBusiness"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * description 0..* BackboneElement "description" "description"
      * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
      * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * role 0..* BackboneElement "role" "role"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
  * patientFee 0..1 BackboneElement "patientFee" "patientFee"
    * moValue 1..1 decimal "moValue" "moValue Heter value i schemat."
    * currency 1..1 string "currency" "currency"
  * targetGroup 0..* BackboneElement "targetGroup" "targetGroup"
    * age 0..1 BackboneElement "age" "age"
      * start 0..1 integer "start" "start"
      * end 0..1 integer "end" "end"
    * gender 0..1 BackboneElement "gender" "gender"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * targetGroupAttribute 0..* BackboneElement "targetGroupAttribute" "targetGroupAttribute"
      * typeOfPersonalAttribute 1..1 BackboneElement "typeOfPersonalAttribute" "typeOfPersonalAttribute"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * attributeValue 1..1 string "attributeValue" "attributeValue"
  * location 1..* BackboneElement "location" "location"
    * geographicalLocation 0..1 BackboneElement "geographicalLocation" "geographicalLocation"
      * county 0..1 BackboneElement "county" "county"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * municipality 0..1 BackboneElement "municipality" "municipality"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * otherLocation 0..1 BackboneElement "otherLocation" "otherLocation"
        * polygon 3..* BackboneElement "polygon" "polygon"
          * north 1..1 string "north" "north (xs:long i schemat.)"
          * east 1..1 string "east" "east (xs:long i schemat.)"
        * otherLocationName 0..1 string "otherLocationName" "otherLocationName Heter name i schemat."
    * physicalLocation 0..1 BackboneElement "physicalLocation" "physicalLocation"
      * locationAddress 0..1 string "locationAddress" "locationAddress"
      * geographicalCoordinates 0..1 BackboneElement "geographicalCoordinates" "geographicalCoordinates"
        * north 1..1 string "north" "north (xs:long i schemat.)"
        * east 1..1 string "east" "east (xs:long i schemat.)"
    * virtualLocation 0..1 BackboneElement "virtualLocation" "virtualLocation"
      * virtualLocationId 1..1 uri "virtualLocationId" "virtualLocationId Heter id i schemat."
    * description 0..* BackboneElement "description" "description"
      * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
      * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * role 0..* BackboneElement "role" "role"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
  * contactInformation 0..* BackboneElement "contactInformation" "contactInformation"
    * ranking 0..1 integer "ranking" "ranking"
    * forRole 0..* BackboneElement "forRole" "forRole"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * purpose 0..1 string "purpose" "purpose"
    * address 0..1 string "address" "address"
    * availableTime 0..* string "availableTime" "availableTime"
    * telecom 0..1 BackboneElement "telecom" "telecom"
      * typeOfTelecom 1..1 BackboneElement "typeOfTelecom" "typeOfTelecom"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * contactPoint 1..1 string "contactPoint" "contactPoint"
    * description 0..* BackboneElement "description" "description"
      * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
      * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * role 0..* BackboneElement "role" "role"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
  * cooperation 0..* BackboneElement "cooperation" "cooperation"
    * typeOfCooperation 1..1 string "typeOfCooperation" "typeOfCooperation"
    * validity 0..1 BackboneElement "validity" "Används för att specificera ett datumintervall med hjälp av start- och slutdatum. start: Startdatum på formatet ÅÅÅÅMMDD end: Slutdatum på formatet ÅÅÅÅMMDD"
      * start 0..1 string "start" "start"
      * end 0..1 string "end" "end"
    * referenceToCareServiceId 1..1 BackboneElement "referenceToCareServiceId" "referenceToCareServiceId"
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * description 0..* BackboneElement "description" "description"
      * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
      * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * role 0..* BackboneElement "role" "role"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
  * resource 0..* BackboneElement "resource" "resource"
    * typeOfResource 1..1 BackboneElement "typeOfResource" "typeOfResource"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * resourceAttribute 0..1 string "resourceAttribute" "resourceAttribute"
    * availableTime 0..* string "availableTime" "availableTime"
    * description 0..* BackboneElement "description" "description"
      * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
      * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * role 0..* BackboneElement "role" "role"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
  * interferenceInformation 0..* BackboneElement "interferenceInformation" "interferenceInformation"
    * datePeriod 1..1 BackboneElement "datePeriod" "Används för att specificera ett datumintervall med hjälp av start- och slutdatum. start: Startdatum på formatet ÅÅÅÅMMDD end: Slutdatum på formatet ÅÅÅÅMMDD"
      * start 0..1 string "start" "start"
      * end 0..1 string "end" "end"
    * typeOfInterference 0..1 BackboneElement "typeOfInterference" "typeOfInterference"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * description 1..* BackboneElement "description" "description"
      * descriptionText 1..1 string "descriptionText" "descriptionText Heter text i schemat."
      * descriptionLanguage 0..1 BackboneElement "descriptionLanguage" "descriptionLanguage Heter language i schemat."
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * role 0..* BackboneElement "role" "role"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
