// Genererad från XSD för supportprocess.serviceprovisioning.healthcareoffering v3.0.0 (Genererad ur scheman i riv.supportprocess.serviceprovisioning.healthcareoffering, tagg 3.0 (commit 0e5b32c68d33); scripts/xsd_to_ig.py)
// Kontrakt: GetCareServiceOfferings v3.0
// Genererad: 2026-09-26

Logical: GetCareServiceOfferingsRequest
Id: getcareserviceofferings-request
Title: "GetCareServiceOfferings — Request"
Description: """
  Logisk modell för begäran i GetCareServiceOfferings
  (urn:riv:supportprocess:serviceprovisioning:healthcareoffering:GetCareServiceOfferingsResponder:3, GetCareServiceOfferingsType), inklusive SOAP-huvuden enligt WSDL.
"""
Characteristics: #can-be-target
* ^version = "3.0"
* logicalAddress 1..1 string "logicalAddress" "SOAP-huvud LogicalAddress. The organisation number of the careservice provider"
* careServiceId 0..* BackboneElement "careServiceId" "careServiceId"
  * root 1..1 string "root" "root"
  * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
* typeOfCareService 0..* BackboneElement "typeOfCareService" "typeOfCareService"
  * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
  * codeSystem 1..1 string "codeSystem" "codeSystem"
  * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
  * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
  * displayName 0..1 string "displayName" "displayName"
  * originalText 0..1 string "originalText" "originalText"
* typeOfPlace 1..1 BackboneElement "typeOfPlace" "typeOfPlace"
  * typeOfPlaceEnum 1..1 code "typeOfPlaceEnum" "typeOfPlaceEnum"
  * typeOfPlaceEnum from TypeOfPlaceVS (required)
* typeOfBusiness 0..* BackboneElement "typeOfBusiness" "typeOfBusiness"
  * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
  * codeSystem 1..1 string "codeSystem" "codeSystem"
  * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
  * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
  * displayName 0..1 string "displayName" "displayName"
  * originalText 0..1 string "originalText" "originalText"
* providingOrganization 0..1 BackboneElement "providingOrganization" "providingOrganization"
  * providingOrganizationId 0..* BackboneElement "providingOrganizationId" "providingOrganizationId"
    * root 1..1 string "root" "root"
    * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
  * management 0..* BackboneElement "management" "management"
    * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
    * codeSystem 1..1 string "codeSystem" "codeSystem"
    * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
    * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
    * displayName 0..1 string "displayName" "displayName"
    * originalText 0..1 string "originalText" "originalText"
  * publicProvider 0..1 boolean "publicProvider" "publicProvider"
* actorLanguage 0..1 BackboneElement "actorLanguage" "actorLanguage"
  * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
  * codeSystem 1..1 string "codeSystem" "codeSystem"
  * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
  * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
  * displayName 0..1 string "displayName" "displayName"
  * originalText 0..1 string "originalText" "originalText"
* actorRole 0..1 BackboneElement "actorRole" "actorRole"
  * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
  * codeSystem 1..1 string "codeSystem" "codeSystem"
  * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
  * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
  * displayName 0..1 string "displayName" "displayName"
  * originalText 0..1 string "originalText" "originalText"
* performingOrganizationId 0..* BackboneElement "performingOrganizationId" "performingOrganizationId"
  * root 1..1 string "root" "root"
  * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
* targetGroupAge 0..1 integer "targetGroupAge" "targetGroupAge"
* targetGroupGender 0..1 BackboneElement "targetGroupGender" "targetGroupGender"
  * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
  * codeSystem 1..1 string "codeSystem" "codeSystem"
  * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
  * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
  * displayName 0..1 string "displayName" "displayName"
  * originalText 0..1 string "originalText" "originalText"
* targetGroupAttribute 0..* BackboneElement "targetGroupAttribute" "targetGroupAttribute"
  * typeOfPersonalAttribute 1..1 BackboneElement "typeOfPersonalAttribute" "typeOfPersonalAttribute"
    * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
    * codeSystem 1..1 string "codeSystem" "codeSystem"
    * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
    * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
    * displayName 0..1 string "displayName" "displayName"
    * originalText 0..1 string "originalText" "originalText"
  * attributeValue 1..1 string "attributeValue" "attributeValue"
* location 0..1 BackboneElement "location" "location"
  * geographicalLocation 0..1 BackboneElement "geographicalLocation" "geographicalLocation"
    * geographicalCoordinates 1..1 BackboneElement "geographicalCoordinates" "geographicalCoordinates"
      * north 1..1 string "north" "north (xs:long i schemat.)"
      * east 1..1 string "east" "east (xs:long i schemat.)"
    * radius 1..1 integer "radius" "radius"
  * county 0..* BackboneElement "county" "county"
    * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
    * codeSystem 1..1 string "codeSystem" "codeSystem"
    * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
    * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
    * displayName 0..1 string "displayName" "displayName"
    * originalText 0..1 string "originalText" "originalText"
  * municipality 0..* BackboneElement "municipality" "municipality"
    * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
    * codeSystem 1..1 string "codeSystem" "codeSystem"
    * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
    * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
    * displayName 0..1 string "displayName" "displayName"
    * originalText 0..1 string "originalText" "originalText"
* searchTerm 0..* string "searchTerm" "searchTerm"
