// Genererad från XSD för ehr.patientsummary v1.0 (fält ur XSD, se TKB avsnitt 3–7; scripts/xsd_to_ig.py)
// Kontrakt: ReceiveEhrExtract v1.0
// Genererad: 2026-09-26

Logical: ReceiveEhrExtractRequest
Id: receiveehrextract-request
Title: "ReceiveEhrExtract — Request"
Description: """
  Logisk modell för begäran i ReceiveEhrExtract
  (urn:riv:ehr:patientsummary:ReceiveEhrExtractResponder:1, ReceiveEhrExtractType), inklusive SOAP-huvuden enligt WSDL.
"""
Characteristics: #can-be-target
* logicalAddress 1..1 string "logicalAddress" "SOAP-huvud LogicalAddress. the HSA-id of the service producer"
* ehr_extract 0..* BackboneElement "ehr_extract" "The root node of an EHR Extract."
  * authorising_party 0..1 Identifier "authorising_party" "authorising_party"
  * ehr_id 1..1 Identifier "ehr_id" "ehr_id"
  * ehr_system 1..1 Identifier "ehr_system" "ehr_system"
  * subject_of_care 1..1 Identifier "subject_of_care" "subject_of_care"
  * time_created 1..1 dateTime "time_created" "time_created"
  * all_compositions 0..* BackboneElement "all_compositions" "Key aggregation class representing the set of Record Components authored and committed during a single clinical encounter. Note the values for territory will indicate the legal framework under which the data was committed. The session_time should be a restriction on the data types of low and high to make them TS, but this restriction is not permissible in XML Schema and thus the IVL properties are simply copied here with the appropriate types."
    * archetype_id 0..1 string "archetype_id" "archetype_id"
    * meaning 0..1 CodeableConcept "meaning" "meaning"
    * compositionName 1..1 string "compositionName" "compositionName Heter name i schemat."
    * orig_parent_ref 0..1 Identifier "orig_parent_ref" "orig_parent_ref"
    * policy_ids 0..* Identifier "policy_ids" "policy_ids"
    * rc_id 1..1 Identifier "rc_id" "rc_id"
    * sensitivity 0..1 integer "sensitivity" "sensitivity"
    * synthesised 1..1 boolean "synthesised" "synthesised"
    * links 0..* BackboneElement "links" "Creates a relationship between two Record Components that is orthogonal to the common one of containment. Note that if a recipient is not permitted to see the component linked to, even revealing the link constitutes an inappropriate disclosure. Role is of type CD so that the displayName property of that class can be used in place of any specific coding scheme."
      * follow_link 1..1 boolean "follow_link" "follow_link"
      * nature 1..1 code "nature" "nature"
      * role 0..1 CodeableConcept "role" "role"
      * target_type 0..1 CodeableConcept "target_type" "target_type"
      * target_id 1..* Identifier "target_id" "target_id"
    * feeder_audit 0..1 BackboneElement "feeder_audit" "The committal and revision data for a Record Component. Note that the invariant is incorrectly stated as constraining \"attribute_version_status.coding_scheme_name\" in the printed standard."
      * committer 1..1 Identifier "committer" "committer"
      * ehr_system 1..1 Identifier "ehr_system" "ehr_system"
      * previous_version 0..1 Identifier "previous_version" "previous_version"
      * reason_for_revision 0..1 CodeableConcept "reason_for_revision" "reason_for_revision"
      * time_committed 1..1 dateTime "time_committed" "time_committed"
      * version_set_id 0..1 Identifier "version_set_id" "version_set_id"
      * version_status 0..1 code "version_status" "version_status"
    * contribution_id 0..1 Identifier "contribution_id" "contribution_id"
    * session_time 0..1 Period "session_time" "session_time"
    * territory 0..1 code "territory" "territory"
    * attestations 0..* BackboneElement "attestations" "Any attestations for a Record Component. The proof field should be a cryptographic hash of the RECORD_COMPONENT it attests, but it is recognised that in many implementations the components will change to point to new components that revise them. In that case, the proof should sign the unchanging parts of the component only."
      * attested_view 0..1 Attachment "attested_view" "attested_view"
      * proof 0..1 Attachment "proof" "proof"
      * reason_for_attestation 1..1 CodeableConcept "reason_for_attestation" "reason_for_attestation"
      * time 1..1 dateTime "time" "time"
      * target_rc_id 1..* Identifier "target_rc_id" "target_rc_id"
      * attester 1..1 BackboneElement "attester" "The participation of an entity in the EHR."
        * function 0..1 CodeableConcept "function" "function"
        * healthcare_facility 0..1 Identifier "healthcare_facility" "healthcare_facility"
        * mode 0..1 code "mode" "mode"
        * performer 1..1 Identifier "performer" "performer"
        * service_setting 0..1 CodeableConcept "service_setting" "service_setting"
    * other_participations 0..* BackboneElement "other_participations" "The participation of an entity in the EHR."
      * function 0..1 CodeableConcept "function" "function"
      * healthcare_facility 0..1 Identifier "healthcare_facility" "healthcare_facility"
      * mode 0..1 code "mode" "mode"
      * performer 1..1 Identifier "performer" "performer"
      * service_setting 0..1 CodeableConcept "service_setting" "service_setting"
    * committal 1..1 BackboneElement "committal" "The committal and revision data for a Record Component. Note that the invariant is incorrectly stated as constraining \"attribute_version_status.coding_scheme_name\" in the printed standard."
      * committer 1..1 Identifier "committer" "committer"
      * ehr_system 1..1 Identifier "ehr_system" "ehr_system"
      * previous_version 0..1 Identifier "previous_version" "previous_version"
      * reason_for_revision 0..1 CodeableConcept "reason_for_revision" "reason_for_revision"
      * time_committed 1..1 dateTime "time_committed" "time_committed"
      * version_set_id 0..1 Identifier "version_set_id" "version_set_id"
      * version_status 0..1 code "version_status" "version_status"
    * composer 0..1 BackboneElement "composer" "The participation of an entity in the EHR."
      * function 0..1 CodeableConcept "function" "function"
      * healthcare_facility 0..1 Identifier "healthcare_facility" "healthcare_facility"
      * mode 0..1 code "mode" "mode"
      * performer 1..1 Identifier "performer" "performer"
      * service_setting 0..1 CodeableConcept "service_setting" "service_setting"
    * content 0..* BackboneElement "content" "Superclass of Section and Entry that enables the former to include instances of itself. Abstrakt typ; instansen anges med xsi:type som en av SECTION, ENTRY."
      * archetype_id 0..1 string "archetype_id" "archetype_id"
      * meaning 0..1 CodeableConcept "meaning" "meaning"
      * contentName 1..1 string "contentName" "contentName Heter name i schemat."
      * orig_parent_ref 0..1 Identifier "orig_parent_ref" "orig_parent_ref"
      * policy_ids 0..* Identifier "policy_ids" "policy_ids"
      * rc_id 1..1 Identifier "rc_id" "rc_id"
      * sensitivity 0..1 integer "sensitivity" "sensitivity"
      * synthesised 1..1 boolean "synthesised" "synthesised"
      * links 0..* BackboneElement "links" "Creates a relationship between two Record Components that is orthogonal to the common one of containment. Note that if a recipient is not permitted to see the component linked to, even revealing the link constitutes an inappropriate disclosure. Role is of type CD so that the displayName property of that class can be used in place of any specific coding scheme."
        * follow_link 1..1 boolean "follow_link" "follow_link"
        * nature 1..1 code "nature" "nature"
        * role 0..1 CodeableConcept "role" "role"
        * target_type 0..1 CodeableConcept "target_type" "target_type"
        * target_id 1..* Identifier "target_id" "target_id"
      * feeder_audit 0..1 BackboneElement "feeder_audit" "The committal and revision data for a Record Component. Note that the invariant is incorrectly stated as constraining \"attribute_version_status.coding_scheme_name\" in the printed standard."
        * committer 1..1 Identifier "committer" "committer"
        * ehr_system 1..1 Identifier "ehr_system" "ehr_system"
        * previous_version 0..1 Identifier "previous_version" "previous_version"
        * reason_for_revision 0..1 CodeableConcept "reason_for_revision" "reason_for_revision"
        * time_committed 1..1 dateTime "time_committed" "time_committed"
        * version_set_id 0..1 Identifier "version_set_id" "version_set_id"
        * version_status 0..1 code "version_status" "version_status"
      * section 0..1 BackboneElement "section" "Element som bara finns när instansen är av subtypen SECTION (xsi:type)."
        * members 0..* string "members" " (Rekursiv typ, ej utvecklad.)"
      * entry 0..1 BackboneElement "entry" "Element som bara finns när instansen är av subtypen ENTRY (xsi:type)."
        * act_id 0..1 string "act_id" "act_id"
        * act_status 0..1 code "act_status" "act_status"
        * subject_of_information_category 0..1 code "subject_of_information_category" "subject_of_information_category"
        * uncertainty_expressed 1..1 boolean "uncertainty_expressed" "uncertainty_expressed"
        * items 0..* BackboneElement "items" "Superclass of Cluster and Element that enables the former to include instances of itself. The obs_time should be a restriction on the data types of low and high to make them TS, but this restriction is not permissible in XML Schema and thus the IVL properties are simply copied here with the appropriate types. Abstrakt typ; instansen anges med xsi:type som en av CLUSTER, ELEMENT."
          * archetype_id 0..1 string "archetype_id" "archetype_id"
          * meaning 0..1 CodeableConcept "meaning" "meaning"
          * itemName 1..1 string "itemName" "itemName Heter name i schemat."
          * orig_parent_ref 0..1 Identifier "orig_parent_ref" "orig_parent_ref"
          * policy_ids 0..* Identifier "policy_ids" "policy_ids"
          * rc_id 1..1 Identifier "rc_id" "rc_id"
          * sensitivity 0..1 integer "sensitivity" "sensitivity"
          * synthesised 1..1 boolean "synthesised" "synthesised"
          * links 0..* BackboneElement "links" "Creates a relationship between two Record Components that is orthogonal to the common one of containment. Note that if a recipient is not permitted to see the component linked to, even revealing the link constitutes an inappropriate disclosure. Role is of type CD so that the displayName property of that class can be used in place of any specific coding scheme."
            * follow_link 1..1 boolean "follow_link" "follow_link"
            * nature 1..1 code "nature" "nature"
            * role 0..1 CodeableConcept "role" "role"
            * target_type 0..1 CodeableConcept "target_type" "target_type"
            * target_id 1..* Identifier "target_id" "target_id"
          * feeder_audit 0..1 BackboneElement "feeder_audit" "The committal and revision data for a Record Component. Note that the invariant is incorrectly stated as constraining \"attribute_version_status.coding_scheme_name\" in the printed standard."
            * committer 1..1 Identifier "committer" "committer"
            * ehr_system 1..1 Identifier "ehr_system" "ehr_system"
            * previous_version 0..1 Identifier "previous_version" "previous_version"
            * reason_for_revision 0..1 CodeableConcept "reason_for_revision" "reason_for_revision"
            * time_committed 1..1 dateTime "time_committed" "time_committed"
            * version_set_id 0..1 Identifier "version_set_id" "version_set_id"
            * version_status 0..1 code "version_status" "version_status"
          * emphasis 0..1 CodeableConcept "emphasis" "emphasis"
          * item_category 0..1 code "item_category" "item_category"
          * obs_time 0..1 Period "obs_time" "obs_time"
          * cluster 0..1 BackboneElement "cluster" "Element som bara finns när instansen är av subtypen CLUSTER (xsi:type)."
            * structure_type 1..1 code "structure_type" "structure_type"
            * parts 0..* string "parts" " (Rekursiv typ, ej utvecklad.)"
          * element 0..1 BackboneElement "element" "Element som bara finns när instansen är av subtypen ELEMENT (xsi:type)."
            * elementValue 0..1 string "elementValue" " (ISO 21090 ANY, polymorft värde, modellerat som string.) Heter value i schemat."
        * info_provider 0..1 BackboneElement "info_provider" "The participation of an entity in the EHR."
          * function 0..1 CodeableConcept "function" "function"
          * healthcare_facility 0..1 Identifier "healthcare_facility" "healthcare_facility"
          * mode 0..1 code "mode" "mode"
          * performer 1..1 Identifier "performer" "performer"
          * service_setting 0..1 CodeableConcept "service_setting" "service_setting"
        * other_participations 0..* BackboneElement "other_participations" "The participation of an entity in the EHR."
          * function 0..1 CodeableConcept "function" "function"
          * healthcare_facility 0..1 Identifier "healthcare_facility" "healthcare_facility"
          * mode 0..1 code "mode" "mode"
          * performer 1..1 Identifier "performer" "performer"
          * service_setting 0..1 CodeableConcept "service_setting" "service_setting"
        * subject_of_information 0..1 BackboneElement "subject_of_information" "Identifies the relationship of a person to the subject of care. Specifically used in Entry.subject_of_information."
          * party 0..1 Identifier "party" "party"
          * relationship 1..1 Attachment "relationship" "relationship"
  * criteria 0..* BackboneElement "criteria" "Restrictions or filters on the creation of the EHR Extract. The time_period should be a restriction on the data types of low and high to make them TS, but this restriction is not permissible in XML Schema and thus the IVL properties are simply copied here with the appropriate types."
    * all_versions 0..1 boolean "all_versions" "all_versions"
    * archetype_ids 0..* Identifier "archetype_ids" "archetype_ids"
    * max_sensitivity 0..1 integer "max_sensitivity" "max_sensitivity"
    * multimedia_included 0..1 boolean "multimedia_included" "multimedia_included"
    * other_constraints 0..1 string "other_constraints" "other_constraints"
    * time_period 0..1 Period "time_period" "time_period"
  * folders 0..* BackboneElement "folders" "Organises and groups Compositions within an EHR Extract."
    * archetype_id 0..1 string "archetype_id" "archetype_id"
    * meaning 0..1 CodeableConcept "meaning" "meaning"
    * folderName 1..1 string "folderName" "folderName Heter name i schemat."
    * orig_parent_ref 0..1 Identifier "orig_parent_ref" "orig_parent_ref"
    * policy_ids 0..* Identifier "policy_ids" "policy_ids"
    * rc_id 1..1 Identifier "rc_id" "rc_id"
    * sensitivity 0..1 integer "sensitivity" "sensitivity"
    * synthesised 1..1 boolean "synthesised" "synthesised"
    * links 0..* BackboneElement "links" "Creates a relationship between two Record Components that is orthogonal to the common one of containment. Note that if a recipient is not permitted to see the component linked to, even revealing the link constitutes an inappropriate disclosure. Role is of type CD so that the displayName property of that class can be used in place of any specific coding scheme."
      * follow_link 1..1 boolean "follow_link" "follow_link"
      * nature 1..1 code "nature" "nature"
      * role 0..1 CodeableConcept "role" "role"
      * target_type 0..1 CodeableConcept "target_type" "target_type"
      * target_id 1..* Identifier "target_id" "target_id"
    * feeder_audit 0..1 BackboneElement "feeder_audit" "The committal and revision data for a Record Component. Note that the invariant is incorrectly stated as constraining \"attribute_version_status.coding_scheme_name\" in the printed standard."
      * committer 1..1 Identifier "committer" "committer"
      * ehr_system 1..1 Identifier "ehr_system" "ehr_system"
      * previous_version 0..1 Identifier "previous_version" "previous_version"
      * reason_for_revision 0..1 CodeableConcept "reason_for_revision" "reason_for_revision"
      * time_committed 1..1 dateTime "time_committed" "time_committed"
      * version_set_id 0..1 Identifier "version_set_id" "version_set_id"
      * version_status 0..1 code "version_status" "version_status"
    * sub_folders 0..* string "sub_folders" " (Rekursiv typ, ej utvecklad.)"
    * attestations 0..* BackboneElement "attestations" "Any attestations for a Record Component. The proof field should be a cryptographic hash of the RECORD_COMPONENT it attests, but it is recognised that in many implementations the components will change to point to new components that revise them. In that case, the proof should sign the unchanging parts of the component only."
      * attested_view 0..1 Attachment "attested_view" "attested_view"
      * proof 0..1 Attachment "proof" "proof"
      * reason_for_attestation 1..1 CodeableConcept "reason_for_attestation" "reason_for_attestation"
      * time 1..1 dateTime "time" "time"
      * target_rc_id 1..* Identifier "target_rc_id" "target_rc_id"
      * attester 1..1 BackboneElement "attester" "The participation of an entity in the EHR."
        * function 0..1 CodeableConcept "function" "function"
        * healthcare_facility 0..1 Identifier "healthcare_facility" "healthcare_facility"
        * mode 0..1 code "mode" "mode"
        * performer 1..1 Identifier "performer" "performer"
        * service_setting 0..1 CodeableConcept "service_setting" "service_setting"
    * composition_rc_ids 0..* string "composition_rc_ids" "composition_rc_ids"
  * demographic_extract 0..* BackboneElement "demographic_extract" "Superclass of all identified parties to the record. Note that the type of id is not given in the printed class description but is included in the class diagram on page 47 of the standard. Abstrakt typ; instansen anges med xsi:type som en av SOFTWARE_OR_DEVICE, ORGANISATION, PERSON."
    * extract_id 1..1 Identifier "extract_id" "extract_id"
    * identifiedEntityId 0..* Identifier "identifiedEntityId" "identifiedEntityId Heter id i schemat."
    * telecom 0..* ContactPoint "telecom" "telecom"
    * softwareOrDevice 0..1 BackboneElement "softwareOrDevice" "Element som bara finns när instansen är av subtypen SOFTWARE_OR_DEVICE (xsi:type)."
      * softwareOrDeviceCode 1..1 CodeableConcept "softwareOrDeviceCode" "softwareOrDeviceCode Heter code i schemat."
      * desc 1..1 string "desc" "desc"
      * manufacturerModelName 1..1 string "manufacturerModelName" "manufacturerModelName"
      * softwareOrDeviceVersion 0..1 string "softwareOrDeviceVersion" "softwareOrDeviceVersion Heter version i schemat."
      * owningOrganisation_id 0..1 string "owningOrganisation_id" "owningOrganisation_id"
    * organisation 0..1 BackboneElement "organisation" "Element som bara finns när instansen är av subtypen ORGANISATION (xsi:type)."
      * organisationCode 1..1 CodeableConcept "organisationCode" "organisationCode Heter code i schemat."
      * desc 1..1 string "desc" "desc"
      * organisationName 1..1 string "organisationName" "organisationName Heter name i schemat."
      * addr 0..* Address "addr" "addr"
    * person 0..1 BackboneElement "person" "Element som bara finns när instansen är av subtypen PERSON (xsi:type)."
      * personName 0..* HumanName "personName" "personName Heter name i schemat."
      * addr 0..* Address "addr" "addr"
* parameters 0..* BackboneElement "parameters" "parameters"
  * parameterCode 0..1 CodeableConcept "parameterCode" "parameterCode Heter code i schemat."
  * parameterName 1..1 string "parameterName" "parameterName Heter name i schemat."
  * parameterValue 1..1 string "parameterValue" "parameterValue Heter value i schemat."
