// Genererad från XSD för supportprocess.logistics.scheduling v2.0.0 (Genererad ur scheman i riv.supportprocess.logistics.scheduling, tagg 2.0_RC1 (commit 5131f0ee09b2); scripts/xsd_to_ig.py)
// Kontrakt: GetAvailableTimeslots v2.0
// Genererad: 2026-09-26

Logical: GetAvailableTimeslots
Id: getavailabletimeslots
Title: "GetAvailableTimeslots — Response"
Description: """
  Logisk modell för svaret i GetAvailableTimeslots
  (urn:riv:supportprocess:logistics:scheduling:GetAvailableTimeslotsResponder:2, GetAvailableTimeslotsResponseType).
"""
Characteristics: #can-be-target
* ^version = "2.0"
* timeslot 0..* BackboneElement "timeslot" "timeslot"
  * timeslotId 1..1 string "timeslotId" "timeslotId"
  * timeType 1..1 BackboneElement "timeType" "timeType"
    * timeTypeCode 1..1 string "timeTypeCode" "timeTypeCode Heter code i schemat."
    * hidden 0..1 boolean "hidden" "hidden"
    * careContactCode 0..1 BackboneElement "careContactCode" "careContactCode"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * healthcareService 0..* BackboneElement "healthcareService" "healthcareService"
      * healthcareServiceCode 1..1 BackboneElement "healthcareServiceCode" "healthcareServiceCode Heter code i schemat."
        * snomedCtCode 1..1 string "snomedCtCode" "snomedCtCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "Tillåtna värden: 1.2.752.116.2.1.1."
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * information 0..* BackboneElement "information" "information"
        * header 1..1 string "header" "header"
        * description 0..1 string "description" "description"
        * link 0..1 uri "link" "link"
      * conditionsToConfirm 0..* BackboneElement "conditionsToConfirm" "conditionsToConfirm"
        * header 1..1 string "header" "header"
        * description 0..1 string "description" "description"
        * link 0..1 uri "link" "link"
    * healthcareTeam 0..1 boolean "healthcareTeam" "healthcareTeam"
    * patientGroup 0..1 boolean "patientGroup" "patientGroup"
    * cancelAppointmentAllowed 1..1 boolean "cancelAppointmentAllowed" "cancelAppointmentAllowed"
    * updateAppointmentAllowed 1..1 boolean "updateAppointmentAllowed" "updateAppointmentAllowed"
    * appointmentRule 0..3 BackboneElement "appointmentRule" "appointmentRule"
      * timeTypeRulesType 1..1 code "timeTypeRulesType" "timeTypeRulesType Heter type i schemat."
      * timeTypeRulesType from ProcessVS (required)
      * reasonTextRequired 1..1 code "reasonTextRequired" "reasonTextRequired"
      * reasonTextRequired from ReasonRequiredVS (required)
      * reasonCodeRequired 1..1 code "reasonCodeRequired" "reasonCodeRequired"
      * reasonCodeRequired from ReasonRequiredVS (required)
      * reasonCodes 0..* BackboneElement "reasonCodes" "reasonCodes"
        * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
        * codeSystem 1..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * information 0..* BackboneElement "information" "information"
        * header 1..1 string "header" "header"
        * description 0..1 string "description" "description"
        * link 0..1 uri "link" "link"
      * conditionToConfirm 0..* BackboneElement "conditionToConfirm" "conditionToConfirm"
        * header 1..1 string "header" "header"
        * description 0..1 string "description" "description"
        * link 0..1 uri "link" "link"
  * startTime 1..1 string "startTime" "startTime"
  * endTime 0..1 string "endTime" "endTime"
  * timeLength 0..1 decimal "timeLength" "timeLength"
  * healthcareFacilityHSAId 1..1 BackboneElement "healthcareFacilityHSAId" "healthcareFacilityHSAId"
    * root 1..1 string "root" "root"
    * hSAIdExtension 1..1 string "hSAIdExtension" "hSAIdExtension Heter extension i schemat."
  * practitioner 0..* BackboneElement "practitioner" "practitioner"
    * HSAId 1..1 BackboneElement "HSAId" "HSAId"
      * root 1..1 string "root" "root"
      * hSAIdExtension 1..1 string "hSAIdExtension" "hSAIdExtension Heter extension i schemat."
    * firstName 1..1 string "firstName" "firstName"
    * lastName 1..1 string "lastName" "lastName"
    * title 0..1 string "title" "title"
  * resource 0..* BackboneElement "resource" "resource"
    * typeOfResource 0..1 BackboneElement "typeOfResource" "typeOfResource"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * resourceAttribute 0..1 BackboneElement "resourceAttribute" "resourceAttribute"
      * cvCode 1..1 string "cvCode" "cvCode Heter code i schemat."
      * codeSystem 1..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
    * description 0..1 string "description" "description"
  * withinCareGuarantee 0..1 boolean "withinCareGuarantee" "withinCareGuarantee"
  * alternativeLocation 0..1 string "alternativeLocation" "alternativeLocation"
* resultCode 1..1 code "resultCode" "resultCode"
* resultCode from ResultCodeVS (required)
* resultText 0..1 string "resultText" "resultText"
