// Genererad från XSD för masterdata.citizen.citizen v2.0 (Genererad ur scheman i riv.masterdata.citizen.citizen, tagg 2.0; scripts/xsd_to_ig.py)
// Kontrakt: LookupResidentsForProfile v2.0
// Genererad: 2026-09-26

Logical: LookupResidentsForProfile
Id: lookupresidentsforprofile
Title: "LookupResidentsForProfile — Response"
Description: """
  Logisk modell för svaret i LookupResidentsForProfile
  (urn:riv:masterdata:citizen:citizen:LookupResidentsForProfileResponder:2, LookupResidentsForProfileResponseType).
"""
Characteristics: #can-be-target
* ^version = "2.0"
* lookupResidentsResponseType 1..1 BackboneElement "lookupResidentsResponseType" "Returtyp för operationen lookupResidentsForProfile"
  * populationRegistrationRecords 0..* BackboneElement "populationRegistrationRecords" "Folkbokföringspost"
    * protectedPersonIndicator 1..1 boolean "protectedPersonIndicator" "protectedPersonIndicator"
    * testIndicator 1..1 boolean "testIndicator" "testIndicator"
    * syncronizationTime 0..1 dateTime "syncronizationTime" "syncronizationTime"
    * notificationCase 0..1 BackboneElement "notificationCase" "Ärendeuppgifter"
      * recordId 0..1 string "recordId" "recordId"
      * notificationType 0..1 string "notificationType" "notificationType"
      * modificationTime 0..1 dateTime "modificationTime" "modificationTime"
      * totalRecord 0..1 boolean "totalRecord" "totalRecord"
      * notificationDate 0..1 BackboneElement "notificationDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
    * personalRecord 1..1 BackboneElement "personalRecord" "Grupp för personpost"
      * personalIdentity 0..1 BackboneElement "personalIdentity" "Personidentitet"
        * personalIdentityId 1..1 string "personalIdentityId" "personalIdentityId Heter id i schemat."
        * personalIdentityType 1..1 string "personalIdentityType" "personalIdentityType Heter type i schemat."
      * referredPersonalIdentity 0..* BackboneElement "referredPersonalIdentity" "Personidentitet"
        * personalIdentityId 1..1 string "personalIdentityId" "personalIdentityId Heter id i schemat."
        * personalIdentityType 1..1 string "personalIdentityType" "personalIdentityType Heter type i schemat."
      * deregistration 0..1 BackboneElement "deregistration" "Uppgifter om avregistrering"
        * deregistrationReasonCode 0..1 code "deregistrationReasonCode" "deregistrationReasonCode"
        * deregistrationReasonCode from DeregistrationReasonCodeVS (required)
        * deregistrationDate 0..1 BackboneElement "deregistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * personalRecordName 0..1 BackboneElement "personalRecordName" "Namn Heter name i schemat."
        * givenNameIndicator 0..1 integer "givenNameIndicator" "givenNameIndicator"
        * givenName 0..1 BackboneElement "givenName" "Grupp för del av namn där delen kan vara styrkt eller ej"
          * namePartName 0..1 string "namePartName" "namePartName Heter name i schemat."
          * attested 0..1 boolean "attested" "attested"
        * middleName 0..1 BackboneElement "middleName" "Grupp för del av namn där delen kan vara styrkt eller ej"
          * namePartName 0..1 string "namePartName" "namePartName Heter name i schemat."
          * attested 0..1 boolean "attested" "attested"
        * surname 0..1 BackboneElement "surname" "Grupp för del av namn där delen kan vara styrkt eller ej"
          * namePartName 0..1 string "namePartName" "namePartName Heter name i schemat."
          * attested 0..1 boolean "attested" "attested"
        * notificationName 0..1 string "notificationName" "notificationName"
      * populationRegistrationLocality 0..1 BackboneElement "populationRegistrationLocality" "Uppgifter om folkbokföring"
        * populationRegistrationDate 0..1 BackboneElement "populationRegistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * countyCode 0..1 string "countyCode" "countyCode"
        * municipalityCode 0..1 string "municipalityCode" "municipalityCode"
        * parishCode 0..1 string "parishCode" "parishCode"
        * propertyDesignation 0..1 string "propertyDesignation" "propertyDesignation"
        * fictitiousPropertyNumber 0..1 integer "fictitiousPropertyNumber" "fictitiousPropertyNumber"
        * populationRegistrationType 0..1 code "populationRegistrationType" "populationRegistrationType"
        * populationRegistrationType from PopulationRegistrationTypeVS (required)
      * addressInformation 0..1 BackboneElement "addressInformation" "Grupp för adressuppgifter"
        * residentialAddress 0..1 BackboneElement "residentialAddress" "Svensk adress"
          * careOf 0..1 string "careOf" "careOf"
          * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
          * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
          * postalCode 0..1 integer "postalCode" "postalCode"
          * city 0..1 string "city" "city"
        * nationalKeys 0..1 BackboneElement "nationalKeys" "Riksnycklar"
          * propertyId 0..1 string "propertyId" "propertyId"
          * addressPlaceId 0..1 string "addressPlaceId" "addressPlaceId"
          * apartmentId 0..1 string "apartmentId" "apartmentId"
        * district 0..1 BackboneElement "district" "Grupp för Distriktskod"
          * districtCode 0..1 integer "districtCode" "districtCode"
        * specialPostalAddress 0..1 BackboneElement "specialPostalAddress" "Svensk adress"
          * careOf 0..1 string "careOf" "careOf"
          * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
          * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
          * postalCode 0..1 integer "postalCode" "postalCode"
          * city 0..1 string "city" "city"
        * addressAbroad 0..1 BackboneElement "addressAbroad" "Utlandsadress"
          * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
          * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
          * postalAddress3 0..1 string "postalAddress3" "postalAddress3"
          * country 0..1 string "country" "country"
          * addressAbroadDate 0..1 BackboneElement "addressAbroadDate" "Kan beskriva ett datum med variabel noggrannhet."
            * format 1..1 code "format" "format"
            * format from DateTypeFormatVS (required)
            * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
          * votingDate 0..1 BackboneElement "votingDate" "Kan beskriva ett datum med variabel noggrannhet."
            * format 1..1 code "format" "format"
            * format from DateTypeFormatVS (required)
            * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * maritalStatus 0..1 BackboneElement "maritalStatus" "Civistånd"
        * maritalStatusCode 0..1 code "maritalStatusCode" "maritalStatusCode"
        * maritalStatusCode from MaritalStatusCodeVS (required)
        * maritalStatusDate 0..1 BackboneElement "maritalStatusDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * birth 0..1 BackboneElement "birth" "Uppgifter om födelse"
        * placeOfBirthSweden 0..1 BackboneElement "placeOfBirthSweden" "Uppgifter om hemort i Sverige"
          * birthCountyCode 0..1 string "birthCountyCode" "birthCountyCode"
          * birthParish 0..1 string "birthParish" "birthParish"
        * birthAbroad 0..1 BackboneElement "birthAbroad" "Uppgifter om födelse i utlandet"
          * placeOfBirthAbroad 0..1 BackboneElement "placeOfBirthAbroad" "Födelseort utland"
            * placeOfBirthAbroad 0..1 string "placeOfBirthAbroad" "placeOfBirthAbroad"
            * attested 0..1 boolean "attested" "attested"
          * countryOfBirth 0..1 string "countryOfBirth" "countryOfBirth"
      * immigration 0..1 BackboneElement "immigration" "Grupp för invandringsuppgifter"
        * immigrationDate 0..1 BackboneElement "immigrationDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * rightOfResidence 0..1 boolean "rightOfResidence" "rightOfResidence"
        * immigrationIdentity 0..* BackboneElement "immigrationIdentity" "Grupp för personnummer och vilket land det är knutet till. Motsvarar skatteverkets NordisktPnrDa, NordisktPnrFi, NordisktPnrFo, NordisktPnrIs och NordisktPnrNo"
          * personalIdentityNumber 1..1 string "personalIdentityNumber" "personalIdentityNumber"
          * country 1..1 string "country" "country"
      * relationships 0..* BackboneElement "relationships" "Grupp för relation"
        * relationshipId 1..1 BackboneElement "relationshipId" "Grupp för relationspersons identitet Antingen får man personnummer eller datum då personen föddes."
          * personalIdentity 0..1 BackboneElement "personalIdentity" "Personidentitet"
            * personalIdentityId 1..1 string "personalIdentityId" "personalIdentityId Heter id i schemat."
            * personalIdentityType 1..1 string "personalIdentityType" "personalIdentityType Heter type i schemat."
          * dateOfBirth 0..1 BackboneElement "dateOfBirth" "Kan beskriva ett datum med variabel noggrannhet."
            * format 1..1 code "format" "format"
            * format from DateTypeFormatVS (required)
            * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * relationshipType 1..1 code "relationshipType" "relationshipType"
        * relationshipType from RelationshipTypeVS (required)
        * relationshipFromDate 0..1 BackboneElement "relationshipFromDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * relationshipToDate 0..1 BackboneElement "relationshipToDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * relationshipName 0..1 BackboneElement "relationshipName" "Namn Heter name i schemat."
          * givenNameIndicator 0..1 integer "givenNameIndicator" "givenNameIndicator"
          * givenName 0..1 BackboneElement "givenName" "Grupp för del av namn där delen kan vara styrkt eller ej"
            * namePartName 0..1 string "namePartName" "namePartName Heter name i schemat."
            * attested 0..1 boolean "attested" "attested"
          * middleName 0..1 BackboneElement "middleName" "Grupp för del av namn där delen kan vara styrkt eller ej"
            * namePartName 0..1 string "namePartName" "namePartName Heter name i schemat."
            * attested 0..1 boolean "attested" "attested"
          * surname 0..1 BackboneElement "surname" "Grupp för del av namn där delen kan vara styrkt eller ej"
            * namePartName 0..1 string "namePartName" "namePartName Heter name i schemat."
            * attested 0..1 boolean "attested" "attested"
          * notificationName 0..1 string "notificationName" "notificationName"
        * deregistration 0..1 BackboneElement "deregistration" "Uppgifter om avregistrering"
          * deregistrationReasonCode 0..1 code "deregistrationReasonCode" "deregistrationReasonCode"
          * deregistrationReasonCode from DeregistrationReasonCodeVS (required)
          * deregistrationDate 0..1 BackboneElement "deregistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
            * format 1..1 code "format" "format"
            * format from DateTypeFormatVS (required)
            * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * relationshipStatus 0..1 code "relationshipStatus" "relationshipStatus Heter status i schemat."
        * relationshipStatus from RelationshipStatusVS (required)
      * citizenship 0..* BackboneElement "citizenship" "Grupp för medborgarskap"
        * citizenshipCountryCode 0..1 BackboneElement "citizenshipCountryCode" "Grupp för medborgarskapslandkod"
          * countryCode 0..1 string "countryCode" "countryCode"
          * attested 0..1 boolean "attested" "attested"
        * citizenshipDate 0..1 BackboneElement "citizenshipDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * citizenshipStatus 0..1 code "citizenshipStatus" "citizenshipStatus Heter status i schemat."
        * citizenshipStatus from CitizenshipStatusVS (required)
    * historicalRecords 0..1 BackboneElement "historicalRecords" "Grupp för historik"
      * populationRegistrationLocality 0..* BackboneElement "populationRegistrationLocality" "Uppgifter om folkbokföring"
        * populationRegistrationDate 0..1 BackboneElement "populationRegistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * countyCode 0..1 string "countyCode" "countyCode"
        * municipalityCode 0..1 string "municipalityCode" "municipalityCode"
        * parishCode 0..1 string "parishCode" "parishCode"
        * propertyDesignation 0..1 string "propertyDesignation" "propertyDesignation"
        * fictitiousPropertyNumber 0..1 integer "fictitiousPropertyNumber" "fictitiousPropertyNumber"
        * populationRegistrationType 0..1 code "populationRegistrationType" "populationRegistrationType"
        * populationRegistrationType from PopulationRegistrationTypeVS (required)
      * historicalAddress 0..1 BackboneElement "historicalAddress" "Grupp för historik adress"
        * residentialAddress 0..1 BackboneElement "residentialAddress" "Svensk adress"
          * careOf 0..1 string "careOf" "careOf"
          * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
          * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
          * postalCode 0..1 integer "postalCode" "postalCode"
          * city 0..1 string "city" "city"
