<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Inera AB licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->	
<wsdl:definitions name='CancelExtendedPatientRelationInteraction'
	xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
	xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
	xmlns:xs='http://www.w3.org/2001/XMLSchema'
	xmlns:tjsr='urn:riv:ehr:patientrelationship:administration:CancelExtendedPatientRelationResponder:1'
	xmlns:itr='urn:riv:itintegration:registry:1'
	xmlns:tns='urn:riv:ehr:patientrelationship:administration:CancelExtendedPatientRelation:1:rivtabp21'
	targetNamespace='urn:riv:ehr:patientrelationship:administration:CancelExtendedPatientRelation:1:rivtabp21'>

	<wsdl:documentation xml:lang='sv'>
		 Tjänsteinteraktionens namn: CancelExtendedPatientRelation
		 Beskrivning: 
		   Denna tjänst återkallar en patientrelation i patientrelationstjänsten. patientrelationen raderas inte från patientrelationstjänsten utan markeras som återkallad (ej längre giltig) för historikens skull. En återkallan kan ej återtas.
		 Revisioner: 
		 Tjänstedomän: patientrelationship:administration
		 Tjänsteinteraktionstyp: Fråga-Svar
		 WS-profil: RIVTABP21
		 Förvaltas av: Inera AB
	</wsdl:documentation>
	
	<wsdl:types>
		<xs:schema targetNamespace='urn:riv:ehr:patientrelationship:administration:CancelExtendedPatientRelation:1:rivtabp21'>
			<xs:import schemaLocation='CancelExtendedPatientRelationResponder_1.0.xsd' namespace='urn:riv:ehr:patientrelationship:administration:CancelExtendedPatientRelationResponder:1' />
			<xs:import schemaLocation='../../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
		</xs:schema>
	</wsdl:types>
	
		
	<wsdl:message name='CancelExtendedPatientRelationRequest'>
		<wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
			<wsdl:documentation xml:lang='sv'>Som logisk adress anges HSA-id för vårdgivare som patientrelationen gäller för.</wsdl:documentation>
		</wsdl:part>
	
		<wsdl:part name='parameters' element='tjsr:CancelExtendedPatientRelationRequest' />
	</wsdl:message>

	<wsdl:message name='CancelExtendedPatientRelationResponse'>
		<wsdl:part name='parameters' element='tjsr:CancelExtendedPatientRelationResponse' />
	</wsdl:message>

	<wsdl:portType name='CancelExtendedPatientRelationResponderInterface'>
		<wsdl:operation name='CancelExtendedPatientRelation'>
			<wsdl:input message='tns:CancelExtendedPatientRelationRequest' />
			<wsdl:output message='tns:CancelExtendedPatientRelationResponse' />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name='CancelExtendedPatientRelationResponderBinding' type='tns:CancelExtendedPatientRelationResponderInterface'>
		<soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
		<wsdl:operation name='CancelExtendedPatientRelation'>
			<soap:operation soapAction='urn:riv:ehr:patientrelationship:administration:CancelExtendedPatientRelationResponder:1:CancelExtendedPatientRelation' style='document' />
			<wsdl:input>
				<soap:header use='literal' message='tns:CancelExtendedPatientRelationRequest' part='LogicalAddress' />
				<soap:body use='literal' parts='parameters' />
			</wsdl:input>
			<wsdl:output>
				<soap:body use='literal' />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name='CancelExtendedPatientRelationResponderService'>
		<wsdl:port name='CancelExtendedPatientRelationResponderPort' binding='tns:CancelExtendedPatientRelationResponderBinding'>
			<soap:address location='http://tempuri.org' />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
