<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="urn:riv:se.apotekensservice:lf:LasLFVardsystemResponder:4"
           targetNamespace="urn:riv:se.apotekensservice:lf:LasLFVardsystemResponder:4.1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="4.1">

	<xs:element name="avPatientSparradePosterArBorttagna" type="xs:boolean" nillable="false">
		<xs:annotation>
			<xs:documentation>
				Markering som anger om poster plockats bort ur resultatet
				pga att patienten spärrat dessa, dvs det finns poster som
				är spärrade och därför inte är med i resultatet. 
			</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>
		