id: inera.clinicalprocess-healthcond-description
canonical: https://fhir.inera.se/ig/clinicalprocess-healthcond-description
name: clinicalprocesshealthconddescription
title: "clinicalprocess: healthcond: description"
status: draft
version: 3.0.5
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: draft

dependencies:
  hl7.fhir.r4.core: 4.0.1
  se.inera.rivta.core: current

pages:
  index.md:
    title: Hem
  1-inledning.md:
    title: 1 Inledning
  2-versionsinformation.md:
    title: 2 Versionsinformation
  3-tjanstedomanens-arkitektur.md:
    title: 3 Tjänstedomänens arkitektur
  4-tjanstedomanens-krav-och-regler.md:
    title: 4 Tjänstedomänens krav och regler
  5-tjanstedomanens-meddelandemodeller.md:
    title: 5 Tjänstedomänens meddelandemodeller
  6-gemensamma-informationskomponenter.md:
    title: 6 Gemensamma informationskomponenter
  7-tjanstekontrakt.md:
    title: 7 Tjänstekontrakt

menu:
  Home: index.html
  1 Inledning: 1-inledning.html
  2 Versionsinformation: 2-versionsinformation.html
  3 Tjänstedomänens arkitektur: 3-tjanstedomanens-arkitektur.html
  4 Tjänstedomänens krav och regler: 4-tjanstedomanens-krav-och-regler.html
  5 Tjänstedomänens meddelandemodeller: 5-tjanstedomanens-meddelandemodeller.html
  6 Gemensamma informationskomponenter: 6-gemensamma-informationskomponenter.html
  7 Tjänstekontrakt: 7-tjanstekontrakt.html
  Artifacts: artifacts.html

parameters:
  show-inherited-invariants: false
  apply-contact: true
  apply-publisher: true
  apply-version: true
  apply-copyright: true

publisher: Inera AB
contact:
  - name: Inera Arkitektur
    telecom:
      - system: url
        value: https://www.inera.se
copyright: >-
  Copyright 2024 Inera AB. Licensieras under Creative Commons Attribution 4.0.
