// Genererad från XSD för se.apotekensservice.or v7.0 (ingen TKB finns i källan; scripts/xsd_to_ig.py)
// Kontrakt: HamtaAktuellaOrdinationer v5.2
// Genererad: 2026-09-26

Logical: HamtaAktuellaOrdinationer
Id: hamtaaktuellaordinationer
Title: "HamtaAktuellaOrdinationer — Response"
Description: """
  Logisk modell för svaret i HamtaAktuellaOrdinationer
  (urn:riv:se.apotekensservice:or:HamtaAktuellaOrdinationerResponder:5, HamtaAktuellaOrdinationerResponseType).
"""
Characteristics: #can-be-target
* apoteksInformationLista 0..* BackboneElement "apoteksInformationLista" "Lista med apotek därifrån förändringar eller skapande utförts på/av ordinationerna."
  * aktorsnamn 0..1 string "aktorsnamn" "Officiellt namn för aktör"
  * aktorsorgnr 0..1 string "aktorsorgnr" "Aktörens organisationsnummer."
  * allmantelefon 0..1 string "allmantelefon" "Telefonnummer för receptexpedition"
  * besoksadress 0..1 string "besoksadress" "Expeditionsställets besöksadress"
  * eReceptDjur 0..1 boolean "eReceptDjur" "Anger om apoteket expedierar erecept för djur"
  * fax 0..1 string "fax" "Expeditionsställets faxnummer"
  * glnKod 1..1 string "glnKod" "Expeditionsställets GLN-kod"
  * huvudtypkod 0..1 string "huvudtypkod" "Kod som beskriver huvudverksamheten för expeditionsstället"
  * namn 0..1 string "namn" "Expeditionsställets officiella namn"
  * ort 0..1 string "ort" "Expeditionsställets besöksort"
  * registrerad 1..1 boolean "registrerad" "Anger om apoteket finns registrerat i EXPO. Om false så saknar alla fält utom glnKod värden."
  * slutdatum 0..1 dateTime "slutdatum" "Datum för stängning av verksamhet"
  * startdatum 0..1 dateTime "startdatum" "Datum för start av verksamhet"
* arbetsplatsInfoLista 0..* BackboneElement "arbetsplatsInfoLista" "Lista med arbetsplatser därifrån förändringar utförts på ordinationerna."
  * arbetsplatsNamn 0..1 string "arbetsplatsNamn" "ArbetsplatsNamn"
  * arbetsplatsOrt 0..1 string "arbetsplatsOrt" "ArbetsplatsOrt"
  * arbetsplatskod 1..1 string "arbetsplatskod" "Arbetsplatskod"
  * faxnummer 0..1 string "faxnummer" "Faxnummer"
  * giltigSlut 0..1 dateTime "giltigSlut" "Slutdatum för arbetsplatsens giltighetsperiod."
  * giltigStart 0..1 dateTime "giltigStart" "Startdatum för arbetsplatsens giltighetsperiod."
  * postadress 0..1 string "postadress" "Postadress"
  * postnummer 0..1 string "postnummer" "Postnummer"
  * registrerad 1..1 boolean "registrerad" "Anger om arbetsplatsen finns registrerad i ARKO. Om false så saknar alla fält utom arbetsplatskod värden."
  * telefonnummer1 0..1 string "telefonnummer1" "Telefonnummer 1"
  * telefonnummer2 0..1 string "telefonnummer2" "Telefonnummer 2"
* artikelLista 0..* BackboneElement "artikelLista" "Lista med artikelinformation för de varor som ingår i ordinationerna."
  * alternativtAntalKlartext 0..1 string "alternativtAntalKlartext" "Sammanslagning av multiplar, antal och alternativ enhet. Om alternativ enhet saknas för artikeln är detta fält tomt."
  * antalKlartext 0..1 string "antalKlartext" "Sammanslagning av multiplar, antal och enhet på storleken."
  * artikelbenamning 0..1 string "artikelbenamning" "Sammanfattande beskrivning på en artikel (läkemedelsnamn + läkemedelsform + styrka + styrkans enhet + företag vid behov) Förkortningar kan förekomma."
  * atcKlartext 0..1 string "atcKlartext" "ATC-kod i klartext enligt lexikontabell. Språk anges på svenska (sv)."
  * atcKod 0..1 string "atcKod" "ATC-kod"
  * avregistreringsdatum 0..1 dateTime "avregistreringsdatum" "Datum då artikeln blev avregistrerad."
  * bestallningsstoppad 0..1 boolean "bestallningsstoppad" "Markering om artikel enligt TLV är beställningsstoppad i gällande prisperiod."
  * foregaendePrisperiodensvara 0..1 boolean "foregaendePrisperiodensvara" "Markering som anger om artikeln var definierad som föregående prisperiodens vara."
  * formansberattigad 0..1 boolean "formansberattigad" "Markering som visar om artikeln är förmånsberättigad enligt VARA, vilket beslutas av TLV."
  * forpackningsenhet 0..1 string "forpackningsenhet" "Enhet på förpackningsstorleken, i klartext. Returnerar den alternativa enheten om sådan finns angiven för artikeln. Språk anges på svenska (sv)."
  * forpackningsinnehall 0..1 string "forpackningsinnehall" "Beskrivning av förpackning, innehåll och antal."
  * forpackningsmangd 0..1 decimal "forpackningsmangd" "Totala mängden i förpackningen. Returnerar den alternativa förpackningsmängden om sådan finns angiven för artikeln."
  * forpackningstyp 0..1 string "forpackningstyp" "Beskrivning av förpackningstyp för en artikel."
  * forsaljningsstoppad 0..1 boolean "forsaljningsstoppad" "Markering som visar om artikeln inte längre får försäljas. Sant om antingen artikeln eller produkten är försäljningsstoppad."
  * forskrivningsratter 0..* string "forskrivningsratter" "Lista med förskrivningsrätter för artikeln. Använder koder enligt NPL."
  * forskrivningsrattsyrken 0..* BackboneElement "forskrivningsrattsyrken" "Lista med yrken som har förskrivningsrätt för artikeln. Listan utvinns ur förskrivningsrättskoderna, översätts till tvåställiga yrkeskoder och klartexter. Varje yrke finns max en gång i listan."
    * yrkesKod 1..1 string "yrkesKod" "Yrkeskod för utfärdarkategori."
    * yrkesKodKlartext 1..1 string "yrkesKodKlartext" "Yrkeskod för utfärdarkategori, klartext."
  * historiskaVarunummer 0..* string "historiskaVarunummer" "Lista över eventuella tidigare varunummer. Används om en artikel har fått nytt varunummer."
  * intressent 0..1 string "intressent" "Intressent (företag) som är ansvarig för artikeln."
  * lakemedel 0..1 boolean "lakemedel" "Markering som visar om en artikel är ett läkemedel."
  * narkotikaklass 0..1 string "narkotikaklass" "Koden för narkotikaklass enligt Läkemedelsverkets förteckning: - = Ospecificerad 0 = Ej narkotikaklassad 1 = II 2 = Narkotika förteckning IV/V 3 = III 4 = IV 5 = V 6 = I"
  * narkotikaklassKlartext 0..1 string "narkotikaklassKlartext" "Narkotikaklass i klartext enligt Läkemedelsverket förteckning. Klartext enligt lexikontabell för narkotikaklass. Språk anges på svenska (sv)."
  * nplId 0..1 string "nplId" "Produktid, antingen NPL-id eller SB-id. Unikt id för en läkemedelsprodukt. Alla förpackningar med samma styrka/form/tillverkare grupperas i samma produktid."
  * nplPackageId 0..1 string "nplPackageId" "Förpackningsid, antingen NPL-packid eller SB-packid. Unikt id för en läkemedelsartikel."
  * prisperiodensvara 0..1 boolean "prisperiodensvara" "Markering som anger om artikeln är definierad som prisperiodens vara."
  * produkttyp 0..1 string "produkttyp" "Artikelns produkttyp som kod."
  * produkttypKlartext 0..1 string "produkttypKlartext" "Artikelns produkttyp som klartext enligt lexikontabell för produkttyp. Språk anges på svenska (sv)."
  * registrerad 1..1 boolean "registrerad" "Anger om artikeln finns registrerad i VARA."
  * sarskiltLakemedelKod 0..1 string "sarskiltLakemedelKod" "Kod som anger om särskild receptblankett krävs och om recept får itereras. 1 = Särskilt receptblankett krävs INTE. 2 = Särskild receptblankett krävs. Recepten får itereras. 3 = Särskild receptblankett krävs. Recepten får EJ itereras. 4 = Särskild receptblankett krävs. Recept för humant bruk får itereras. - = Ospecifierat"
  * tillhandahalls 0..1 boolean "tillhandahalls" "Markering som visar om artikeln marknadsförs på den svenska marknaden. Sant om både artikeln och produkten tillhandahålls."
  * utbytbar 0..1 boolean "utbytbar" "Markering som anger om artikeln är utbytbar enligt VARA."
  * varunummer 0..1 string "varunummer" "Nordiskt varunummer som är unikt för handelsvaror. För läkemedel kan dubbletter förekomma vid parallellimport."
  * artikelExtension 0..1 BackboneElement "artikelExtension" "artikelExtension Heter extension i schemat."
    * utlamnandebegransningKod 0..1 string "utlamnandebegransningKod" "Kod som anger om produkten får utlämnas från apotek endast om den har förskrivits av en läkare med viss specialistkompetens."
    * utlamnandebegransningKlartext 0..1 string "utlamnandebegransningKlartext" "Anger om produkten får utlämnas från apotek endast om den har förskrivits av en läkare med viss specialistkompetens."
* forskrivarInfoLista 0..* BackboneElement "forskrivarInfoLista" "Lista med förskrivare som gjort förändringar i ordinationerna."
  * efternamn 0..1 string "efternamn" "Efternamn"
  * fornamn 0..1 string "fornamn" "Förnamn"
  * forskrivarkod 1..1 string "forskrivarkod" "Förskrivarkod."
  * giltig 1..1 boolean "giltig" "Sann om förskrivaren är giltig."
  * gruppforskrivarkodKlartext 0..1 string "gruppforskrivarkodKlartext" "Gruppförskrivarkod klartext."
  * yrkesKodInfoLista 0..* BackboneElement "yrkesKodInfoLista" "Lista av yrkeskodsinformation."
    * specialistKodKlartext 0..* string "specialistKodKlartext" "Lista med specialistkod för utfärdarkategori, klartext."
    * yrkesKodKlartext 1..1 string "yrkesKodKlartext" "Yrkeskod för utfärdarkategori, klartext."
    * inskrankt 0..1 boolean "inskrankt" "Sann om förskrivaren (per yrkeskod) har inskränkt förskrivningsrätt."
* ordinationslista 1..1 BackboneElement "ordinationslista" "Ordinationslista"
  * dispenseradordinationLista 0..* BackboneElement "dispenseradordinationLista" "Lista med dispenserade ordinationer."
    * affResultat 1..1 BackboneElement "affResultat" "Information om aff-fel för ordinationen."
      * affFelLista 0..* BackboneElement "affFelLista" "Lista med AFF-fel"
        * allvarlighetsgrad 1..1 integer "allvarlighetsgrad" "Kod för att beskriva hur allvarligt ett AFF-fel är. 1 = Accepterad med varning, 2 = Avvisad."
        * felkod 1..1 string "felkod" "Felkod enligt Automatisk format- och författningskontroll (AFF)."
        * felmeddelande 1..1 string "felmeddelande" "Felmeddelande för AFF-fel."
      * affStatus 1..1 integer "affStatus" "Status för hela ordinationen eller uttaget. Allvarligaste AFF-felet styr status för hela ordinationen. 0 = Accepterad, 1 = Accepterad med varning, 2 = Avvisad."
      * avvisningsorsak 0..1 string "avvisningsorsak" "Information om avvisningsorsak."
      * kontrolltidpunkt 1..1 dateTime "kontrolltidpunkt" "Datum och tidpunkt för utförd AFF-kontroll."
      * kontrolltyp 1..1 integer "kontrolltyp" "Typ av AFF-kontroll som har genomförts. 1 = AFF-PRENEF 2 = AFF-NEF 3 = AFF-REG 4 = AFF-KORR 5 = AFF-EXP 6 = AFF-KEX 7 = AFF-MAK 8 = AFF-NOD 9 = AFF-UTS"
    * akut 0..1 boolean "akut" "Markering att ordinationen är akut."
    * apoteketsKommentar 0..1 string "apoteketsKommentar" "Farmaceutens kommentar på ordinationen."
    * artikelinformation 1..1 BackboneElement "artikelinformation" "Information om artikeln som ordinerats."
      * nplId 0..1 string "nplId" "NPL-id alternativt SB-id som identifierar läkemedelprodukt."
      * nplPackId 0..1 string "nplPackId" "NPL pack-id alternativt SB Pack-id som identifierar läkemedelsartikel."
      * utbyttArtikel 0..1 boolean "utbyttArtikel" "Markering om substitution har skett vid expedition. Kan endast sättas via uttag."
      * varunr 0..1 string "varunr" "Identitet på förskriven eller expedierad artikel."
    * behandlingsinformation 1..1 BackboneElement "behandlingsinformation" "behandlingsinformation"
      * andamalKlartext 0..1 string "andamalKlartext" "Ändamål i klartext"
      * behandlingsslut 0..1 dateTime "behandlingsslut" "Datum om tidpunkt då behandlingen avslutas."
      * behandlingsstart 0..1 dateTime "behandlingsstart" "Datum om och tidpunkt då behandlingen påbörjas."
      * doseringstext1 0..1 string "doseringstext1" "Doseringstext från förskrivare eller korrigerad av farmaceut"
      * doseringstext2 0..1 string "doseringstext2" "Kompletterande doseringstext för exempelvis extempore och licensläkemedel."
      * sprakkod 0..1 string "sprakkod" "Främmande språk för doseringstext enligt ISO-639-1"
    * dispenseringsregler 1..1 BackboneElement "dispenseringsregler" "Dispenseringsregler"
      * bytesEj 0..1 string "bytesEj" "Markering att farmaceut eller patient beslutat att ordinerad artikel ej får bytas ut. A=Apoteks-nej, P=Patient-nej. Får enbart anges för Ordinationstyp=D (Dispenserad ordination)."
      * ejTillatenSubstitution 0..1 boolean "ejTillatenSubstitution" "Markering om förskriven vara ej får bytas ut enligt förskrivare."
      * forman 1..1 boolean "forman" "Förskrivarens uppgift om ordinationen ska innefattas i förmånen."
      * insattningstidpunkt 0..1 dateTime "insattningstidpunkt" "Datum när patienten skall påbörja intag."
      * sistaGiltighetsdag 0..1 dateTime "sistaGiltighetsdag" "Ordinationens sista giltighetsdag."
    * doseringsschema 0..1 BackboneElement "doseringsschema" "Information om intag. Valfritt för stående, obligatorisk dispenserad ordination, får ej anges för vid behov."
      * intagstillfalle 1..* BackboneElement "intagstillfalle" "Beskriver tid och mängd för intag av läkemedel."
        * dagIPeriod 1..1 integer "dagIPeriod" "Dag i perioden när intag skall göras. Exempel: Intag ska ske varje måndag och onsdag och startdatum är på en måndag. Måndag Insättningsdatum = 2010-01-01, Periodlängd=7, Dag i period= 1. Onsdag Insättningsdatum = 2010-01-01, Periodlängd=7, Dag i period=3."
        * intagsmangd 0..1 decimal "intagsmangd" "Intagsmängd per tillfälle. Null hanteras som enligt ordination."
        * intagstillfalle 1..1 integer "intagstillfalle" "Klockslag när patienten ska inta medicinering."
      * periodlangd 1..1 integer "periodlangd" "Antal dagar som dosering skall gälla. Vid regelbunden dosering anges periodlängd = 1 Vid oregelbunden dosering anges antal dagar som intervallet omfattar. Exempelvis 2 om intag ska ske varannan dag."
    * forandring 0..1 BackboneElement "forandring" "Information om eventuell historikskapande händelse (förändring). Endast en typ av historikskapande-information (makluering, förändring eller utsättning) kan förekomma."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Apotekspersonal."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * forandrandeOrdinator 0..1 BackboneElement "forandrandeOrdinator" "Förandrande Ordinatör."
        * arbetsplatskod 1..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 0..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * administrator 0..1 BackboneElement "administrator" "Administratör."
        * fornamn 0..1 string "fornamn" "Administratörens förnamn."
        * efternamn 0..1 string "efternamn" "Administratörens efternamn."
        * anvandarId 1..1 string "anvandarId" "Användar-id för administratören, eller id för databasjobbet, som uppdaterar en ordination."
        * arbetsplats 1..1 string "arbetsplats" "Unik kod för identifiering av administratörens arbetsplats."
      * kommentar 0..1 string "kommentar" "Kommentar vid förändring, utsättning eller makulering av ordination. Obligatorisk parameter utom vid makulering med orsakskod annan än 4."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tidpunkt då ny historikpost skapades."
      * typ 1..1 string "typ" "Anger vilken typ som avses. M =Makulering, U = Utsättning, K = Korrigerad, S = Spärrad, O = Utskrivet original."
    * forskrivarKommentar 0..1 string "forskrivarKommentar" "Förskrivarens kommentar till apoteket."
    * harForandrats 1..1 boolean "harForandrats" "Markering om ordinationen har ändrats av förskrivare eller farmaceut."
    * historisktOrdinationsId 0..1 string "historisktOrdinationsId" "Hänvisning till en eventuell historisk post av ordinationen. Alla historiska poster har tillståndsstatus Historik (211). En historisk post skapas exempelvis vid korrigering."
    * korrigerbar 0..1 boolean "korrigerbar" "Markering om ordinationen är korrigerbar."
    * leveransMeddelande 0..1 string "leveransMeddelande" "Leveransinformation om ordinationen skickas till ett ombud."
    * makulering 0..1 BackboneElement "makulering" "Information om eventuell historikskapande händelse (makluering). Endast en typ av historikskapande-information (makluering, förändring eller utsättning) kan förekomma."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Apotekspersonal."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * forandrandeOrdinator 0..1 BackboneElement "forandrandeOrdinator" "Förandrande Ordinatör."
        * arbetsplatskod 1..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 0..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * administrator 0..1 BackboneElement "administrator" "Administratör."
        * fornamn 0..1 string "fornamn" "Administratörens förnamn."
        * efternamn 0..1 string "efternamn" "Administratörens efternamn."
        * anvandarId 1..1 string "anvandarId" "Användar-id för administratören, eller id för databasjobbet, som uppdaterar en ordination."
        * arbetsplats 1..1 string "arbetsplats" "Unik kod för identifiering av administratörens arbetsplats."
      * kommentar 0..1 string "kommentar" "Kommentar vid förändring, utsättning eller makulering av ordination. Obligatorisk parameter utom vid makulering med orsakskod annan än 4."
      * orsakskod 1..1 integer "orsakskod" "Orsakskod som strukturerat beskriver orsak till makulering."
      * orsakskodKlartext 1..1 string "orsakskodKlartext" "Orsakskoder vid makulering: 1 = Fel patient. 2 = Fel läkemedel/vara/ styrka/ändamål. Patienten informerad. 3 = Utsatt lm/Inaktuell medicinering. Patienten informerad. Gäller ej dospatienter då utsättning skall användas. 4 = Annan orsak. Patienten informerad."
      * paUppdragAv 1..1 string "paUppdragAv" "Uppgift om vem som har gett i uppdrag att genomföra makulering. P = Patient, F = Förskrivare."
      * samtyckeMakulering 0..1 boolean "samtyckeMakulering" "Inhämtat samtycke från patient. Obligatorisk parameter då förskrivare makulerar recept om orsakskod = 2, 3 eller 4."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tidpunkt då ny historikpost skapades."
      * typ 1..1 string "typ" "Anger vilken typ som avses. M =Makulering, U = Utsättning, K = Korrigerad, S = Spärrad, O = Utskrivet original."
    * notatOrdination 0..1 string "notatOrdination" "Förskrivarens notat kopplat till en specifik ordination."
    * ordinationsId 1..1 string "ordinationsId" "Ordinationens unika id som sätts av eHälsomyndigheten."
    * ordinationsinformation 1..1 BackboneElement "ordinationsinformation" "Kompletterande information om ordinationen."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Den som godkänt ordinationen."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * lagringstidpunkt 1..1 dateTime "lagringstidpunkt" "Datum och tid då ordinationen skapades i OR."
      * mottagandeApotek 0..1 string "mottagandeApotek" "Apoteks-id (GLN) vid direktadressering av ordinationer."
      * ordinationstidpunkt 1..1 dateTime "ordinationstidpunkt" "Datum och eventuell tid för ordinationens utfärdande."
      * ordinator 1..1 BackboneElement "ordinator" "Den ordinatör som utfärdat ordinationen."
        * arbetsplatskod 0..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 1..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * kontaktuppgift 1..1 BackboneElement "kontaktuppgift" "Ordinatörens kontaktinformation."
          * adress1 0..1 string "adress1" "Förskrivarens lokalitet eller patientens adress 1. Obligatorisk för förskrivare."
          * adress2 0..1 string "adress2" "Patientens adress 2 eller förskrivarens alternativt vårdcentralens gatuadress. Obligatorisk för förskrivare."
          * postnummer 0..1 string "postnummer" "Patientens eller förskrivarens postnummer. Obligatorisk för förskrivare."
          * postort 0..1 string "postort" "Patientens eller förskrivarens postort. Obligatorisk för förskrivare."
          * telefonnummer1 0..1 string "telefonnummer1" "Patientens eller förskrivarens telefonnummer 1. Obligatorisk för förskrivare."
          * telefonnummer2 0..1 string "telefonnummer2" "Patientens eller förskrivarens telefonnummer 2."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * utfardarkategori 1..1 string "utfardarkategori" "Förskrivarens utfärdarkategori enligt NEF. LAK = Läkare ATL = AT-läkare LMF = Läkare med förordnande TAN = Tandläkare VET = Veterinär TAH = Tandhygienist BMO = Barnmorska SSK = Sjuksköterska HJM = Hjälpmedelsförskrivare"
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * originalformat 1..1 integer "originalformat" "Originalhandlingens ursprung. 0 = Pappersordination 1 = Telefonordination 2 = E-recept (NEF) (3 = Faxordination patient) 4 = Faxordination 5 = E-ordination 6 = Utskrivet från OR 7 = Utskriven E-ordination."
      * originalordinationsId 1..1 string "originalordinationsId" "Unikt id för en ordination. Dock ej unikt för e-recept som tillhör receptsamling."
      * patient 1..1 BackboneElement "patient" "Den patient som ordinationen gäller för."
        * efternamn 1..1 string "efternamn" "Patientens efternamn. Hämtas från första delen (före kommatecken) av patientens Rednamn som fås vid anrop mot FOLK."
        * fodelsedatum 0..1 BackboneElement "fodelsedatum" "Födelsedatum och kön för patienter som inte har fullständigt personnummer."
          * fodelsedatum 1..1 dateTime "fodelsedatum" "Födelsedatum för patient som saknar giltigt personnummer."
          * kon 1..1 integer "kon" "Patientens kön. Giltiga värden är: 1 = Man 2 = Kvinna 3 = Ej specificerat"
        * fornamn 1..1 string "fornamn" "Patientens förnamn. Hämtas från andra delen (efter kommatecken) av patientens Rednamn som fås vid anrop mot FOLK."
        * kontaktuppgift 0..1 BackboneElement "kontaktuppgift" "Kontaktuppgifter för patienten."
          * adress1 0..1 string "adress1" "Förskrivarens lokalitet eller patientens adress 1. Obligatorisk för förskrivare."
          * adress2 0..1 string "adress2" "Patientens adress 2 eller förskrivarens alternativt vårdcentralens gatuadress. Obligatorisk för förskrivare."
          * postnummer 0..1 string "postnummer" "Patientens eller förskrivarens postnummer. Obligatorisk för förskrivare."
          * postort 0..1 string "postort" "Patientens eller förskrivarens postort. Obligatorisk för förskrivare."
          * telefonnummer1 0..1 string "telefonnummer1" "Patientens eller förskrivarens telefonnummer 1. Obligatorisk för förskrivare."
          * telefonnummer2 0..1 string "telefonnummer2" "Patientens eller förskrivarens telefonnummer 2."
        * personnummer 0..1 string "personnummer" "Giltigt personnummer."
      * registrerandeApotekspersonal 0..1 BackboneElement "registrerandeApotekspersonal" "Den som registrerat ordinationen."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * testindikator 1..1 integer "testindikator" "Markering om ordinationen är äkta, för test eller för utbildning. 1 = Äkta 2 = Test 3 = Utbildning"
    * ordinationsstatus 1..1 BackboneElement "ordinationsstatus" "ordinationsstatus"
      * radversion 1..1 string "radversion" "Ordinationens versionsnummer för intern versionshantering av en ordination. Ny radversion av ordinationen skapas vid varje uttag. Returneras alltid men kan vara utan värde."
      * ordinationsstatusStatus 1..1 integer "ordinationsstatusStatus" "Status för dosunderlag, ordination eller uttag. Heter status i schemat."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tid då dosunderlag, ordination eller uttag senast förändrades."
    * ordinationstyp 0..1 string "ordinationstyp" "Typ av ordination. Anges enbart på ordinationer till dospatient. B = Helförpackning vid behov S = Helförpackning stående D = Dispenserad ordination"
    * radnummerNEF 0..1 string "radnummerNEF" "Unikt id för en rad i en receptsamling som skickas in via NEF. Radnumret är en kombination av rad inom receptsamlingen och eventuellt flerval. Id:t sätts av vårdsystemet. Radnummer utan flerval: 1,2,...n Radnummer med flerval: 1-1, 1-2, 1-n"
    * senastDispenseratUttag 0..1 BackboneElement "senastDispenseratUttag" "Senast dispenseratuttag"
      * senastExpedieratNPLId 0..1 string "senastExpedieratNPLId" "Senast expedierat NPL-id eller SB-id."
      * senastExpedieratNPLPackId 0..1 string "senastExpedieratNPLPackId" "Senast expedierat NPL Pack-id eller SB Pack-id."
      * senastExpedieratVarunr 0..1 string "senastExpedieratVarunr" "Senast expedierat varunr"
      * senasteExpedieradMangd 1..1 decimal "senasteExpedieradMangd" "Senaste expedierad mängd"
      * senasteFormansval 1..1 string "senasteFormansval" "Förmån som användes vid senaste expedition. R = Med förmån U = Utan förmån L = Livsmedel F = Kostnadsfritt"
      * senasteUttagsdatum 1..1 dateTime "senasteUttagsdatum" "Datum för senaste uttag"
    * tidigareOrdinationsId 0..1 string "tidigareOrdinationsId" "Koppling till föregående ordination vid ordinationsförändringar. Ordinationerna behandlas som olika, fristående ordinationer. Används exempelvis vid förlängningar eller för att koppla ihop en ordination som skrivits ut på receptoriginal och registrerats in i OR igen."
    * utsattning 0..1 BackboneElement "utsattning" "Information om eventuell historikskapande händelse (utsättning). Endast en typ av historikskapande-information (makluering, förändring eller utsättning) kan förekomma. Utsättning innehållande enbart utsättningstidpunkt kan dock förekomma i kombination med annat historikskapande objekt."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Apotekspersonal."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * forandrandeOrdinator 0..1 BackboneElement "forandrandeOrdinator" "Förandrande Ordinatör."
        * arbetsplatskod 1..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 0..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * administrator 0..1 BackboneElement "administrator" "Administratör."
        * fornamn 0..1 string "fornamn" "Administratörens förnamn."
        * efternamn 0..1 string "efternamn" "Administratörens efternamn."
        * anvandarId 1..1 string "anvandarId" "Användar-id för administratören, eller id för databasjobbet, som uppdaterar en ordination."
        * arbetsplats 1..1 string "arbetsplats" "Unik kod för identifiering av administratörens arbetsplats."
      * kommentar 0..1 string "kommentar" "Kommentar vid förändring, utsättning eller makulering av ordination. Obligatorisk parameter utom vid makulering med orsakskod annan än 4."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tidpunkt då ny historikpost skapades."
      * typ 1..1 string "typ" "Anger vilken typ som avses. M =Makulering, U = Utsättning, K = Korrigerad, S = Spärrad, O = Utskrivet original."
      * utsattningstidpunkt 0..1 dateTime "utsattningstidpunkt" "Datum när patienten skall avsluta intag."
    * dispenseradOrdinationExtension 0..1 BackboneElement "dispenseradOrdinationExtension" "dispenseradOrdinationExtension Heter extension i schemat."
      * sparradUppgiftKod 0..1 integer "sparradUppgiftKod" "Kod för spärrad uppgift i receptet."
      * sparradUppgiftKlartext 0..1 string "sparradUppgiftKlartext" "Klartext för spärrad uppgift i receptet."
  * dosunderlag 0..1 BackboneElement "dosunderlag" "Dospatients dosunderlag."
    * dosordinator 0..1 BackboneElement "dosordinator" "Dosordinatör."
      * arbetsplatskod 1..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
      * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
      * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
      * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
      * forskrivarkod 1..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
      * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tid då Dosunderlaget skapades."
      * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
    * dosproducent 0..1 string "dosproducent" "Apoteks-id på dosproducent som patienten är kopplad till."
    * dosunderlagsstatus 1..1 BackboneElement "dosunderlagsstatus" "Tillståndsstatus för dosunderlag."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Förändrande apotekspersonal"
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * dosunderlagsstatusStatus 1..1 integer "dosunderlagsstatusStatus" "Status för dosunderlag, ordination eller uttag. Heter status i schemat."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tid då dosunderlag, ordination eller uttag senast förändrades."
    * dosunderlagsversion 1..1 integer "dosunderlagsversion" "Ny Dosunderlagsversion skapas varje gång Dosunderlaget ändrar status till \"Ej godkänt\". Dosunderlagsversionen skrivs ut på dosreceptet."
    * godkannandeFarmaceut 0..1 BackboneElement "godkannandeFarmaceut" "Godkännande Farmaceut."
      * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
      * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
      * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
      * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
      * godkannandetidpunkt 1..1 dateTime "godkannandetidpunkt" "Datum och tid för dosunderlagets godkännande."
      * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
      * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
  * helforpackningsordinationLista 0..* BackboneElement "helforpackningsordinationLista" "Lista med helförpackningsordinationer."
    * affResultat 1..1 BackboneElement "affResultat" "Information om aff-fel för ordinationen."
      * affFelLista 0..* BackboneElement "affFelLista" "Lista med AFF-fel"
        * allvarlighetsgrad 1..1 integer "allvarlighetsgrad" "Kod för att beskriva hur allvarligt ett AFF-fel är. 1 = Accepterad med varning, 2 = Avvisad."
        * felkod 1..1 string "felkod" "Felkod enligt Automatisk format- och författningskontroll (AFF)."
        * felmeddelande 1..1 string "felmeddelande" "Felmeddelande för AFF-fel."
      * affStatus 1..1 integer "affStatus" "Status för hela ordinationen eller uttaget. Allvarligaste AFF-felet styr status för hela ordinationen. 0 = Accepterad, 1 = Accepterad med varning, 2 = Avvisad."
      * avvisningsorsak 0..1 string "avvisningsorsak" "Information om avvisningsorsak."
      * kontrolltidpunkt 1..1 dateTime "kontrolltidpunkt" "Datum och tidpunkt för utförd AFF-kontroll."
      * kontrolltyp 1..1 integer "kontrolltyp" "Typ av AFF-kontroll som har genomförts. 1 = AFF-PRENEF 2 = AFF-NEF 3 = AFF-REG 4 = AFF-KORR 5 = AFF-EXP 6 = AFF-KEX 7 = AFF-MAK 8 = AFF-NOD 9 = AFF-UTS"
    * apoteketsKommentar 0..1 string "apoteketsKommentar" "Farmaceutens kommentar på ordinationen."
    * artikelinformation 1..1 BackboneElement "artikelinformation" "Information om artikeln som ordinerats."
      * nplId 0..1 string "nplId" "NPL-id alternativt SB-id som identifierar läkemedelprodukt."
      * nplPackId 0..1 string "nplPackId" "NPL pack-id alternativt SB Pack-id som identifierar läkemedelsartikel."
      * utbyttArtikel 0..1 boolean "utbyttArtikel" "Markering om substitution har skett vid expedition. Kan endast sättas via uttag."
      * varunr 0..1 string "varunr" "Identitet på förskriven eller expedierad artikel."
    * behandlingsinformation 1..1 BackboneElement "behandlingsinformation" "behandlingsinformation"
      * andamalKlartext 0..1 string "andamalKlartext" "Ändamål i klartext"
      * behandlingsslut 0..1 dateTime "behandlingsslut" "Datum om tidpunkt då behandlingen avslutas."
      * behandlingsstart 0..1 dateTime "behandlingsstart" "Datum om och tidpunkt då behandlingen påbörjas."
      * doseringstext1 0..1 string "doseringstext1" "Doseringstext från förskrivare eller korrigerad av farmaceut"
      * doseringstext2 0..1 string "doseringstext2" "Kompletterande doseringstext för exempelvis extempore och licensläkemedel."
      * sprakkod 0..1 string "sprakkod" "Främmande språk för doseringstext enligt ISO-639-1"
    * doseringsschema 0..1 BackboneElement "doseringsschema" "Information om intag. Valfritt för stående, obligatorisk dispenserad ordination, får ej anges för vid behov."
      * intagstillfalle 1..* BackboneElement "intagstillfalle" "Beskriver tid och mängd för intag av läkemedel."
        * dagIPeriod 1..1 integer "dagIPeriod" "Dag i perioden när intag skall göras. Exempel: Intag ska ske varje måndag och onsdag och startdatum är på en måndag. Måndag Insättningsdatum = 2010-01-01, Periodlängd=7, Dag i period= 1. Onsdag Insättningsdatum = 2010-01-01, Periodlängd=7, Dag i period=3."
        * intagsmangd 0..1 decimal "intagsmangd" "Intagsmängd per tillfälle. Null hanteras som enligt ordination."
        * intagstillfalle 1..1 integer "intagstillfalle" "Klockslag när patienten ska inta medicinering."
      * periodlangd 1..1 integer "periodlangd" "Antal dagar som dosering skall gälla. Vid regelbunden dosering anges periodlängd = 1 Vid oregelbunden dosering anges antal dagar som intervallet omfattar. Exempelvis 2 om intag ska ske varannan dag."
    * forandring 0..1 BackboneElement "forandring" "Information om eventuell historikskapande händelse (förändring). Endast en typ av historikskapande-information (makluering, förändring eller utsättning) kan förekomma."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Apotekspersonal."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * forandrandeOrdinator 0..1 BackboneElement "forandrandeOrdinator" "Förandrande Ordinatör."
        * arbetsplatskod 1..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 0..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * administrator 0..1 BackboneElement "administrator" "Administratör."
        * fornamn 0..1 string "fornamn" "Administratörens förnamn."
        * efternamn 0..1 string "efternamn" "Administratörens efternamn."
        * anvandarId 1..1 string "anvandarId" "Användar-id för administratören, eller id för databasjobbet, som uppdaterar en ordination."
        * arbetsplats 1..1 string "arbetsplats" "Unik kod för identifiering av administratörens arbetsplats."
      * kommentar 0..1 string "kommentar" "Kommentar vid förändring, utsättning eller makulering av ordination. Obligatorisk parameter utom vid makulering med orsakskod annan än 4."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tidpunkt då ny historikpost skapades."
      * typ 1..1 string "typ" "Anger vilken typ som avses. M =Makulering, U = Utsättning, K = Korrigerad, S = Spärrad, O = Utskrivet original."
    * forskrivarKommentar 0..1 string "forskrivarKommentar" "Förskrivarens kommentar till apoteket."
    * harForandrats 1..1 boolean "harForandrats" "Markering om ordinationen har ändrats av förskrivare eller farmaceut."
    * helforpackningsregler 1..1 BackboneElement "helforpackningsregler" "helforpackningsregler"
      * ejTillatenSubstitution 0..1 boolean "ejTillatenSubstitution" "Markering om förskriven vara ej får bytas ut enligt förskrivare."
      * forman 1..1 boolean "forman" "Förskrivarens uppgift om ordinationen ska innefattas i förmånen."
      * forskrivetAntalUttag 1..1 integer "forskrivetAntalUttag" "Antal tillåtna uttag på ordinationen."
      * forstaUttagFore 0..1 dateTime "forstaUttagFore" "Datum inom vilket första uttag av läkemedel måste göras. Sker inte någon expedition på receptet innan detta datum sätts hela ordinationen till utgången."
      * insattningstidpunkt 0..1 dateTime "insattningstidpunkt" "Datum när patienten skall påbörja intag."
      * intervall 0..1 BackboneElement "intervall" "Absolut expeditionsintervall."
        * expeditionsintervall 1..1 integer "expeditionsintervall" "Absolut expeditionsintervall. Av förskrivaren angiven kortaste tid mellan två expeditioner."
        * intervallenhet 1..1 string "intervallenhet" "Enhet för det absoluta expeditionsintervallet. Kan anges i dagar, veckor eller månader. Mn = Månader V = Veckor Dg = Dagar Obligatorisk parameter om Expeditionsintervall anges."
      * resterandeAntalUttag 1..1 integer "resterandeAntalUttag" "Kvarvarande antal uttag på ordinationen"
      * sistaGiltighetsdag 0..1 dateTime "sistaGiltighetsdag" "Ordinationens sista giltighetsdag."
      * slutexpedierad 1..1 boolean "slutexpedierad" "Markering om farmaceut anser att ordinationen är slutexpedierad. Används då kvarvarande mängd är minde än minsta förpackningsstorlek för aktuell artikel."
      * slutexpedieradAvFarmaceut 0..1 boolean "slutexpedieradAvFarmaceut" "Farmaceut har markerat att ordinationen är slutexpedierad."
    * historisktOrdinationsId 0..1 string "historisktOrdinationsId" "Hänvisning till en eventuell historisk post av ordinationen. Alla historiska poster har tillståndsstatus Historik (211). En historisk post skapas exempelvis vid korrigering."
    * korrigerbar 0..1 boolean "korrigerbar" "Markering om ordinationen är korrigerbar."
    * leveransMeddelande 0..1 string "leveransMeddelande" "Leveransinformation om ordinationen skickas till ett ombud."
    * makulering 0..1 BackboneElement "makulering" "Information om eventuell historikskapande händelse (makluering). Endast en typ av historikskapande-information (makluering, förändring eller utsättning) kan förekomma."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Apotekspersonal."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * forandrandeOrdinator 0..1 BackboneElement "forandrandeOrdinator" "Förandrande Ordinatör."
        * arbetsplatskod 1..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 0..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * administrator 0..1 BackboneElement "administrator" "Administratör."
        * fornamn 0..1 string "fornamn" "Administratörens förnamn."
        * efternamn 0..1 string "efternamn" "Administratörens efternamn."
        * anvandarId 1..1 string "anvandarId" "Användar-id för administratören, eller id för databasjobbet, som uppdaterar en ordination."
        * arbetsplats 1..1 string "arbetsplats" "Unik kod för identifiering av administratörens arbetsplats."
      * kommentar 0..1 string "kommentar" "Kommentar vid förändring, utsättning eller makulering av ordination. Obligatorisk parameter utom vid makulering med orsakskod annan än 4."
      * orsakskod 1..1 integer "orsakskod" "Orsakskod som strukturerat beskriver orsak till makulering."
      * orsakskodKlartext 1..1 string "orsakskodKlartext" "Orsakskoder vid makulering: 1 = Fel patient. 2 = Fel läkemedel/vara/ styrka/ändamål. Patienten informerad. 3 = Utsatt lm/Inaktuell medicinering. Patienten informerad. Gäller ej dospatienter då utsättning skall användas. 4 = Annan orsak. Patienten informerad."
      * paUppdragAv 1..1 string "paUppdragAv" "Uppgift om vem som har gett i uppdrag att genomföra makulering. P = Patient, F = Förskrivare."
      * samtyckeMakulering 0..1 boolean "samtyckeMakulering" "Inhämtat samtycke från patient. Obligatorisk parameter då förskrivare makulerar recept om orsakskod = 2, 3 eller 4."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tidpunkt då ny historikpost skapades."
      * typ 1..1 string "typ" "Anger vilken typ som avses. M =Makulering, U = Utsättning, K = Korrigerad, S = Spärrad, O = Utskrivet original."
    * mangdinformation 1..1 BackboneElement "mangdinformation" "mangdinformation"
      * antalForpackningar 1..1 integer "antalForpackningar" "Antal förpackningar per uttag"
      * ingenDygnsdos 0..1 boolean "ingenDygnsdos" "Markering att dygnsdos inte kan anges. Exempelvis vid ordination av kräm."
      * maxDygnsdos 0..1 decimal "maxDygnsdos" "Maximal mängd läkemedel som får förbrukas per dygn enligt doseringsschema eller doseringsanvisning."
      * maxVeckodos 0..1 decimal "maxVeckodos" "Maximal mängd läkemedel som får förbrukas per vecka enligt doseringsschema eller doseringsanvisning."
      * startforpackning 1..1 boolean "startforpackning" "Anger om startförpackning ska expedieras vid första uttag"
      * totalmangd 1..1 decimal "totalmangd" "Förskriven totalmängd."
      * totalmangdKvar 1..1 decimal "totalmangdKvar" "Resterande mängd som finns kvar på receptet"
    * notatOrdination 0..1 string "notatOrdination" "Förskrivarens notat kopplat till en specifik ordination."
    * ordinationsId 1..1 string "ordinationsId" "Ordinationens unika id som sätts av eHälsomyndigheten."
    * ordinationsinformation 1..1 BackboneElement "ordinationsinformation" "Kompletterande information om ordinationen."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Den som godkänt ordinationen."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * lagringstidpunkt 1..1 dateTime "lagringstidpunkt" "Datum och tid då ordinationen skapades i OR."
      * mottagandeApotek 0..1 string "mottagandeApotek" "Apoteks-id (GLN) vid direktadressering av ordinationer."
      * ordinationstidpunkt 1..1 dateTime "ordinationstidpunkt" "Datum och eventuell tid för ordinationens utfärdande."
      * ordinator 1..1 BackboneElement "ordinator" "Den ordinatör som utfärdat ordinationen."
        * arbetsplatskod 0..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 1..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * kontaktuppgift 1..1 BackboneElement "kontaktuppgift" "Ordinatörens kontaktinformation."
          * adress1 0..1 string "adress1" "Förskrivarens lokalitet eller patientens adress 1. Obligatorisk för förskrivare."
          * adress2 0..1 string "adress2" "Patientens adress 2 eller förskrivarens alternativt vårdcentralens gatuadress. Obligatorisk för förskrivare."
          * postnummer 0..1 string "postnummer" "Patientens eller förskrivarens postnummer. Obligatorisk för förskrivare."
          * postort 0..1 string "postort" "Patientens eller förskrivarens postort. Obligatorisk för förskrivare."
          * telefonnummer1 0..1 string "telefonnummer1" "Patientens eller förskrivarens telefonnummer 1. Obligatorisk för förskrivare."
          * telefonnummer2 0..1 string "telefonnummer2" "Patientens eller förskrivarens telefonnummer 2."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * utfardarkategori 1..1 string "utfardarkategori" "Förskrivarens utfärdarkategori enligt NEF. LAK = Läkare ATL = AT-läkare LMF = Läkare med förordnande TAN = Tandläkare VET = Veterinär TAH = Tandhygienist BMO = Barnmorska SSK = Sjuksköterska HJM = Hjälpmedelsförskrivare"
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * originalformat 1..1 integer "originalformat" "Originalhandlingens ursprung. 0 = Pappersordination 1 = Telefonordination 2 = E-recept (NEF) (3 = Faxordination patient) 4 = Faxordination 5 = E-ordination 6 = Utskrivet från OR 7 = Utskriven E-ordination."
      * originalordinationsId 1..1 string "originalordinationsId" "Unikt id för en ordination. Dock ej unikt för e-recept som tillhör receptsamling."
      * patient 1..1 BackboneElement "patient" "Den patient som ordinationen gäller för."
        * efternamn 1..1 string "efternamn" "Patientens efternamn. Hämtas från första delen (före kommatecken) av patientens Rednamn som fås vid anrop mot FOLK."
        * fodelsedatum 0..1 BackboneElement "fodelsedatum" "Födelsedatum och kön för patienter som inte har fullständigt personnummer."
          * fodelsedatum 1..1 dateTime "fodelsedatum" "Födelsedatum för patient som saknar giltigt personnummer."
          * kon 1..1 integer "kon" "Patientens kön. Giltiga värden är: 1 = Man 2 = Kvinna 3 = Ej specificerat"
        * fornamn 1..1 string "fornamn" "Patientens förnamn. Hämtas från andra delen (efter kommatecken) av patientens Rednamn som fås vid anrop mot FOLK."
        * kontaktuppgift 0..1 BackboneElement "kontaktuppgift" "Kontaktuppgifter för patienten."
          * adress1 0..1 string "adress1" "Förskrivarens lokalitet eller patientens adress 1. Obligatorisk för förskrivare."
          * adress2 0..1 string "adress2" "Patientens adress 2 eller förskrivarens alternativt vårdcentralens gatuadress. Obligatorisk för förskrivare."
          * postnummer 0..1 string "postnummer" "Patientens eller förskrivarens postnummer. Obligatorisk för förskrivare."
          * postort 0..1 string "postort" "Patientens eller förskrivarens postort. Obligatorisk för förskrivare."
          * telefonnummer1 0..1 string "telefonnummer1" "Patientens eller förskrivarens telefonnummer 1. Obligatorisk för förskrivare."
          * telefonnummer2 0..1 string "telefonnummer2" "Patientens eller förskrivarens telefonnummer 2."
        * personnummer 0..1 string "personnummer" "Giltigt personnummer."
      * registrerandeApotekspersonal 0..1 BackboneElement "registrerandeApotekspersonal" "Den som registrerat ordinationen."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * testindikator 1..1 integer "testindikator" "Markering om ordinationen är äkta, för test eller för utbildning. 1 = Äkta 2 = Test 3 = Utbildning"
    * ordinationsstatus 1..1 BackboneElement "ordinationsstatus" "ordinationsstatus"
      * radversion 1..1 string "radversion" "Ordinationens versionsnummer för intern versionshantering av en ordination. Ny radversion av ordinationen skapas vid varje uttag. Returneras alltid men kan vara utan värde."
      * ordinationsstatusStatus 1..1 integer "ordinationsstatusStatus" "Status för dosunderlag, ordination eller uttag. Heter status i schemat."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tid då dosunderlag, ordination eller uttag senast förändrades."
    * ordinationstyp 0..1 string "ordinationstyp" "Typ av ordination. Anges enbart på ordinationer till dospatient. B = Helförpackning vid behov S = Helförpackning stående D = Dispenserad ordination"
    * radnummerNEF 0..1 string "radnummerNEF" "Unikt id för en rad i en receptsamling som skickas in via NEF. Radnumret är en kombination av rad inom receptsamlingen och eventuellt flerval. Id:t sätts av vårdsystemet. Radnummer utan flerval: 1,2,...n Radnummer med flerval: 1-1, 1-2, 1-n"
    * senasteHelforpackningsuttag 0..1 BackboneElement "senasteHelforpackningsuttag" "senasteHelforpackningsuttag"
      * nastaUttagInomFormanen 0..1 dateTime "nastaUttagInomFormanen" "Datum för nästa tillåtna uttag inom förmånen."
      * senastExpedieratNPLId 0..1 string "senastExpedieratNPLId" "Senast expedierat NPL-id eller SB-id."
      * senastExpedieratNPLPackId 0..1 string "senastExpedieratNPLPackId" "Senast expedierat NPL Pack-id eller SB Pack-id."
      * senastExpedieratVarunr 0..1 string "senastExpedieratVarunr" "Senast expedierat varunr"
      * senasteExpedieradMangd 1..1 decimal "senasteExpedieradMangd" "Senaste expedierad mängd"
      * senasteFormansval 1..1 string "senasteFormansval" "Förmån som användes vid senaste expedition. U = Utan förmån R = Med förmån L = Livsmedel F = Kostnadsfritt"
      * senasteUttagInomFormanen 0..1 dateTime "senasteUttagInomFormanen" "Datum för senaste uttag inom förmånen enligt förmånsreglerna."
      * senasteUttagsdatum 1..1 dateTime "senasteUttagsdatum" "Datum för senaste uttag"
    * tidigareOrdinationsId 0..1 string "tidigareOrdinationsId" "Koppling till föregående ordination vid ordinationsförändringar. Ordinationerna behandlas som olika, fristående ordinationer. Används exempelvis vid förlängningar eller för att koppla ihop en ordination som skrivits ut på receptoriginal och registrerats in i OR igen."
    * utsattning 0..1 BackboneElement "utsattning" "Information om eventuell historikskapande händelse (utsättning). Endast en typ av historikskapande-information (makluering, förändring eller utsättning) kan förekomma. Utsättning innehållande enbart utsättningstidpunkt kan dock förekomma i kombination med annat historikskapande objekt."
      * apotekspersonal 0..1 BackboneElement "apotekspersonal" "Apotekspersonal."
        * anvandarId 0..1 string "anvandarId" "Användar-id för farmaceut (legitimationskod) eller apotekspersonal (för- och efternamn) som uppdaterar en ordination. Användar-id är en övergångslösning fram tills alla apoteksaktörer har övergått till ORG-gränssnittet."
        * apoteksId 1..1 string "apoteksId" "Apoteks-id är en unik kod som definierar ett specifikt apotek tillhörande en specifik juridisk ägare."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * forandrandeOrdinator 0..1 BackboneElement "forandrandeOrdinator" "Förandrande Ordinatör."
        * arbetsplatskod 1..1 string "arbetsplatskod" "Unik kod för identifiering av förskrivarens arbetsplats vid ordinationstillfället. Saknar förskrivare ordinarie arbetsplats anges en grupparbetsplatskod. Arbetsplatskoden anges för att styra ekonomiska transaktioner vid ordinationer inom förmånen."
        * befattningskod 0..1 string "befattningskod" "Användarens befattningskod enligt HSA."
        * efternamn 0..1 string "efternamn" "Användarens efternamn. Obligatorisk för förskrivare."
        * fornamn 0..1 string "fornamn" "Användarens förnamn. Obligatorisk för förskrivare."
        * forskrivarkod 0..1 string "forskrivarkod" "Förskrivarens individuella 7-ställiga legitimationskod eller förskrivarens gruppförskrivarkod då individuell kod saknas. Gruppförskrivarkod används då förskrivaren saknar individuell förskrivarkod men har via sin roll erhållit förskrivningsrätt. Kan exempelvis vara en AT-läkare eller förskrivare med förordnande. Förskrivarkoden definieras av Socialstyrelsen och gruppförskrivarkoden definieras av eHälsomyndigheten."
        * legitimationskod 0..1 string "legitimationskod" "Förskrivares 7-ställiga förskrivarkod alternativt legitimerad användares 6-ställiga legitimationskod enligt Socialstyrelsen. Obligatorisk för gruppförskrivare (ej läkare) och för farmaceuter."
        * yrkeskod 0..1 string "yrkeskod" "Användarens yrkeskod som definierar vilken typ av legitimation som användaren innehar. Obligatorisk för förskrivare."
      * administrator 0..1 BackboneElement "administrator" "Administratör."
        * fornamn 0..1 string "fornamn" "Administratörens förnamn."
        * efternamn 0..1 string "efternamn" "Administratörens efternamn."
        * anvandarId 1..1 string "anvandarId" "Användar-id för administratören, eller id för databasjobbet, som uppdaterar en ordination."
        * arbetsplats 1..1 string "arbetsplats" "Unik kod för identifiering av administratörens arbetsplats."
      * kommentar 0..1 string "kommentar" "Kommentar vid förändring, utsättning eller makulering av ordination. Obligatorisk parameter utom vid makulering med orsakskod annan än 4."
      * tidpunkt 1..1 dateTime "tidpunkt" "Datum och tidpunkt då ny historikpost skapades."
      * typ 1..1 string "typ" "Anger vilken typ som avses. M =Makulering, U = Utsättning, K = Korrigerad, S = Spärrad, O = Utskrivet original."
      * utsattningstidpunkt 0..1 dateTime "utsattningstidpunkt" "Datum när patienten skall avsluta intag."
    * helforpackningsordinationExtension 0..1 BackboneElement "helforpackningsordinationExtension" "helforpackningsordinationExtension Heter extension i schemat."
      * sparradUppgiftKod 0..1 integer "sparradUppgiftKod" "Kod för spärrad uppgift i receptet."
      * sparradUppgiftKlartext 0..1 string "sparradUppgiftKlartext" "Klartext för spärrad uppgift i receptet."
  * personnummer 0..1 string "personnummer" "Patientens personnummer."
  * underlagsversion 0..1 integer "underlagsversion" "Version på Ordinationslista. Används för att verifiera att klientsystemet har rätt underlag vid uppdateringar."
