// Genererad från XSD för druglogistics.dosedispensing v1.1.0 (ingen TKB finns i källan; scripts/xsd_to_ig.py)
// Kontrakt: HamtaVardtagareinformation v1.0
// Genererad: 2026-09-26

Logical: HamtaVardtagareinformation
Id: hamtavardtagareinformation
Title: "HamtaVardtagareinformation — Response"
Description: """
  Logisk modell för svaret i HamtaVardtagareinformation
  (urn:riv:druglogistics:dosedispensing:HamtaVardtagareinformationResponder:1, HamtaVardtagareinformationResponseType).
"""
Characteristics: #can-be-target
* resultatkod 1..1 code "resultatkod" "resultatkod"
* resultatkod from ResultatkodVS (required)
* meddelandetext 1..1 string "meddelandetext" "meddelandetext"
* meddelandeid 1..1 integer "meddelandeid" "meddelandeid"
* Vardtagarinformation 0..1 BackboneElement "Vardtagarinformation" "Vardtagarinformation"
  * hemmaboende 1..1 boolean "hemmaboende" "hemmaboende"
  * dosapoteksid 1..1 string "dosapoteksid" "dosapoteksid"
  * dosapoteknamn 1..1 string "dosapoteknamn" "dosapoteknamn"
  * forstadosdag 1..1 dateTime "forstadosdag" "forstadosdag"
  * avvikandedosschema 1..1 boolean "avvikandedosschema" "avvikandedosschema"
  * Patientinformation 1..1 BackboneElement "Patientinformation" "Patientinformation"
    * fornamn 1..1 string "fornamn" "Anvandarens fornamn."
    * mellannamn 0..1 string "mellannamn" "Anvandarens mellanamn."
    * efternamn 1..1 string "efternamn" "Anvandarens efternamn."
    * identitetstyp 1..1 code "identitetstyp" "identitetstyp"
    * identitetstyp from IdentitetstypVS (required)
    * personid 1..1 string "personid" "Anvandarens personid"
    * lanskod 0..1 string "lanskod" "Anvandarens folkbokforda lanskod"
    * kommunkod 0..1 string "kommunkod" "Anvandarens folkbokforda kommunkod"
  * Hemmaboendeinformation 0..1 BackboneElement "Hemmaboendeinformation" "Hemmaboendeinformation"
    * adress 0..1 string "adress" "adress"
    * postnummer 0..1 string "postnummer" "postnummer"
    * ort 0..1 string "ort" "ort"
    * telefon 0..1 string "telefon" "telefon"
    * dosmottagareid 0..1 string "dosmottagareid" "dosmottagareid"
    * dosmottagarenamn 0..1 string "dosmottagarenamn" "dosmottagarenamn"
  * Tillfalligadress 0..1 BackboneElement "Tillfalligadress" "Tillfalligadress"
    * adress 0..1 string "adress" "adress"
    * postnummer 0..1 string "postnummer" "postnummer"
    * ort 0..1 string "ort" "ort"
    * telefon 0..1 string "telefon" "telefon"
    * dosmottagareid 0..1 string "dosmottagareid" "dosmottagareid"
    * dosmottagarenamn 0..1 string "dosmottagarenamn" "dosmottagarenamn"
  * Leveransadressinformation 0..1 BackboneElement "Leveransadressinformation" "Leveransadressinformation"
    * boendeenhetnamn 1..1 string "boendeenhetnamn" "boendeenhetnamn"
    * boendeenhetid 1..1 string "boendeenhetid" "boendeenhetid"
    * boendeenhetadress 1..1 string "boendeenhetadress" "boendeenhetadress"
    * boendeenhetpostnummer 1..1 string "boendeenhetpostnummer" "boendeenhetpostnummer"
    * boendeenhetpostort 1..1 string "boendeenhetpostort" "boendeenhetpostort"
    * boendeenhetavdelning 0..1 string "boendeenhetavdelning" "boendeenhetavdelning"
    * arbetsplatskod 1..1 string "arbetsplatskod" "arbetsplatskod"
    * dosmottagareid 0..1 string "dosmottagareid" "dosmottagareid"
    * dosmottagarenamn 0..1 string "dosmottagarenamn" "dosmottagarenamn"
  * Kontaktinformation 1..1 BackboneElement "Kontaktinformation" "Kontaktinformation"
    * PALforskrivarkod 0..1 string "PALforskrivarkod" "PALforskrivarkod"
    * PALfornamn 0..1 string "PALfornamn" "PALfornamn"
    * PALefternamn 0..1 string "PALefternamn" "PALefternamn"
    * anhorigkontaktnamn 0..1 string "anhorigkontaktnamn" "anhorigkontaktnamn"
    * anhorigkontaktemail 0..1 string "anhorigkontaktemail" "anhorigkontaktemail"
    * ansvarigkontaktnamn 0..1 string "ansvarigkontaktnamn" "ansvarigkontaktnamn"
    * ansvarigkontaktemail 0..1 string "ansvarigkontaktemail" "ansvarigkontaktemail"
    * ansvarigkontaktadress 0..1 string "ansvarigkontaktadress" "ansvarigkontaktadress"
    * ansvarigkontaktpostnummer 0..1 string "ansvarigkontaktpostnummer" "ansvarigkontaktpostnummer"
    * ansvarigkontaktpostort 0..1 string "ansvarigkontaktpostort" "ansvarigkontaktpostort"
    * ansvarigkontakttelefon1 0..1 string "ansvarigkontakttelefon1" "ansvarigkontakttelefon1"
    * ansvarigkontakttelefon2 0..1 string "ansvarigkontakttelefon2" "ansvarigkontakttelefon2"
    * vardandeenhetid 0..1 string "vardandeenhetid" "vardandeenhetid"
    * vardandeenhetnamn 0..1 string "vardandeenhetnamn" "vardandeenhetnamn"
    * vardandeenhetpostort 0..1 string "vardandeenhetpostort" "vardandeenhetpostort"
    * vardandeenhetpostnummer 0..1 string "vardandeenhetpostnummer" "vardandeenhetpostnummer"
  * Betalningsinformation 0..1 BackboneElement "Betalningsinformation" "Betalningsinformation"
    * form 0..1 string "form" "form"
    * information 0..1 string "information" "information"
    * betalningsansvarigfornamn 0..1 string "betalningsansvarigfornamn" "betalningsansvarigfornamn"
    * betalningsansvarigefternamn 0..1 string "betalningsansvarigefternamn" "betalningsansvarigefternamn"
    * betalningsansvarigadress 0..1 string "betalningsansvarigadress" "betalningsansvarigadress"
    * betalningsansvarigpostnummer 0..1 string "betalningsansvarigpostnummer" "betalningsansvarigpostnummer"
    * betalningsansvarigort 0..1 string "betalningsansvarigort" "betalningsansvarigort"
    * betalningsansvarigtelefon 0..1 string "betalningsansvarigtelefon" "betalningsansvarigtelefon"
  * Produktionsinfo 0..1 BackboneElement "Produktionsinfo" "Produktionsinfo"
    * dosaktor 0..1 string "dosaktor" "dosaktor"
    * dosapotek 1..1 string "dosapotek" "dosapotek"
    * dosapotekid 1..1 string "dosapotekid" "dosapotekid"
    * stopptidbestallning 0..1 dateTime "stopptidbestallning" "stopptidbestallning"
    * stopptidordination 0..1 dateTime "stopptidordination" "stopptidordination"
    * forstadosdag 1..1 dateTime "forstadosdag" "forstadosdag"
    * dosvecka 0..1 string "dosvecka" "dosvecka"
    * doseringsschema 1..1 BackboneElement "doseringsschema" "doseringsschema"
      * periodlangd 1..1 integer "periodlangd" "Antal dagar som dosering skall galla. Vid regelbunden dosering anges periodlangd = 1 Vid oregelbunden dosering anges antal dagar som intervallet omfattar. Exempelvis 2 om intag ska ske varannan dag."
      * intagstillfalle 1..* BackboneElement "intagstillfalle" "Beskriver tid och mangd for intag av lakemedel."
        * intagstillfalle 1..1 integer "intagstillfalle" "Klockslag nar patienten ska inta medicinering."
        * intagsmangd 0..1 decimal "intagsmangd" "Intagsmangd per tillfalle"
        * dagIPeriod 1..1 integer "dagIPeriod" "Dag i perioden nar intag skall goras. Exempel: Intag ska ske varje mandag och onsdag och startdatum ar pa en mandag. Mandag Insattningsdatum = 2010-01-01, Periodlangd=7, Dag i period= 1. Onsdag Insattningsdatum = 2010-01-01, Periodlangd=7, Dag i period=3."
    * dosmottagareid 0..1 string "dosmottagareid" "dosmottagareid"
    * dosmottagarenamn 0..1 string "dosmottagarenamn" "dosmottagarenamn"
  * Vardtagarstatus 0..* BackboneElement "Vardtagarstatus" "Vardtagarstatus"
    * statuskod 1..1 code "statuskod" "statuskod"
    * statuskod from VardtagarStatusVS (required)
    * frantid 0..1 dateTime "frantid" "frantid"
    * tilltid 0..1 dateTime "tilltid" "tilltid"
  * vilandestatusorsak 0..* string "vilandestatusorsak" "vilandestatusorsak"
