// Genererad från XSD för coreprocess.residentparticipation.residentparticipation v1.0.0-rc2 (Genererad ur tjänsteschemat och domänschemat i riv.coreprocess.residentparticipation.residentparticipation, tagg 1.0_RC2; scripts/xsd_to_ig.py)
// Kontrakt: GetCareManagers v1.0
// Genererad: 2026-09-26

Logical: GetCareManagers
Id: getcaremanagers
Title: "GetCareManagers — Response"
Description: """
  Logisk modell för svaret i GetCareManagers
  (urn:riv:coreprocess:residentparticipation:residentparticipation:GetCareManagersResponder:1, GetCareManagersResponseType).
"""
Characteristics: #can-be-target
* ^version = "1.0"
* careManager 0..* BackboneElement "careManager" "careManager"
  * careManagerHeader 1..1 BackboneElement "careManagerHeader" "careManagerHeader"
    * accessControlHeader 1..1 BackboneElement "accessControlHeader" "accessControlHeader"
      * accountableHealthcareProviderId 1..1 BackboneElement "accountableHealthcareProviderId" "accountableHealthcareProviderId"
        * root 1..1 string "root" "root"
        * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
      * accountableCareUnitId 0..1 BackboneElement "accountableCareUnitId" "accountableCareUnitId"
        * root 1..1 string "root" "root"
        * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
      * patientId 1..1 BackboneElement "patientId" "patientId"
        * root 1..1 string "root" "root"
        * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
      * careProcessId 0..1 BackboneElement "careProcessId" "careProcessId"
        * root 1..1 string "root" "root"
        * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
      * blockComparisonTime 1..1 string "blockComparisonTime" "blockComparisonTime"
    * sourceSystemId 1..1 BackboneElement "sourceSystemId" "sourceSystemId"
      * root 1..1 string "root" "root"
      * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
  * practitionerRoleCode 1..1 BackboneElement "practitionerRoleCode" "practitionerRoleCode Heter code i schemat."
    * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
    * codeSystem 0..1 string "codeSystem" "codeSystem"
    * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
    * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
    * displayName 0..1 string "displayName" "displayName"
    * originalText 0..1 string "originalText" "originalText"
  * practitioner 1..1 BackboneElement "practitioner" "practitioner"
    * hsaId 1..1 BackboneElement "hsaId" "hsaId"
      * root 1..1 string "root" "root"
      * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
    * practitionerName 0..1 string "practitionerName" "practitionerName Heter name i schemat."
    * qualification 0..1 BackboneElement "qualification" "qualification"
      * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
      * codeSystem 0..1 string "codeSystem" "codeSystem"
      * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
      * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
      * displayName 0..1 string "displayName" "displayName"
      * originalText 0..1 string "originalText" "originalText"
  * careTeam 0..1 BackboneElement "careTeam" "careTeam"
    * careTeamId 1..1 BackboneElement "careTeamId" "careTeamId Heter id i schemat."
      * root 1..1 string "root" "root"
      * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
    * careTeamName 1..1 string "careTeamName" "careTeamName Heter name i schemat."
    * internalNotes 0..1 string "internalNotes" "internalNotes"
    * externalNotes 0..1 string "externalNotes" "externalNotes"
    * contact 0..* BackboneElement "contact" "contact"
      * telecom 0..* BackboneElement "telecom" "telecom"
        * system 0..1 BackboneElement "system" "system"
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * contactPointSystemValue 1..1 string "contactPointSystemValue" "contactPointSystemValue Heter value i schemat."
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
      * address 0..1 BackboneElement "address" "address"
        * addressType 0..1 BackboneElement "addressType" "addressType Heter type i schemat."
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * line 0..* string "line" "line"
        * city 0..1 string "city" "city"
        * postalCode 0..1 string "postalCode" "postalCode"
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
  * period 1..1 BackboneElement "period" "period"
    * start 1..1 string "start" "start"
    * end 0..1 string "end" "end"
  * internalNotes 0..1 string "internalNotes" "internalNotes"
  * externalNotes 0..1 string "externalNotes" "externalNotes"
  * managingCareGiver 1..1 BackboneElement "managingCareGiver" "managingCareGiver"
    * hsaId 1..1 BackboneElement "hsaId" "hsaId"
      * root 1..1 string "root" "root"
      * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
    * organizationName 0..1 string "organizationName" "organizationName Heter name i schemat."
    * contact 0..* BackboneElement "contact" "contact"
      * telecom 0..* BackboneElement "telecom" "telecom"
        * system 0..1 BackboneElement "system" "system"
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * contactPointSystemValue 1..1 string "contactPointSystemValue" "contactPointSystemValue Heter value i schemat."
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
      * address 0..1 BackboneElement "address" "address"
        * addressType 0..1 BackboneElement "addressType" "addressType Heter type i schemat."
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * line 0..* string "line" "line"
        * city 0..1 string "city" "city"
        * postalCode 0..1 string "postalCode" "postalCode"
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
  * managingCareUnit 0..1 BackboneElement "managingCareUnit" "managingCareUnit"
    * hsaId 1..1 BackboneElement "hsaId" "hsaId"
      * root 1..1 string "root" "root"
      * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
    * organizationName 0..1 string "organizationName" "organizationName Heter name i schemat."
    * contact 0..* BackboneElement "contact" "contact"
      * telecom 0..* BackboneElement "telecom" "telecom"
        * system 0..1 BackboneElement "system" "system"
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * contactPointSystemValue 1..1 string "contactPointSystemValue" "contactPointSystemValue Heter value i schemat."
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
      * address 0..1 BackboneElement "address" "address"
        * addressType 0..1 BackboneElement "addressType" "addressType Heter type i schemat."
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * line 0..* string "line" "line"
        * city 0..1 string "city" "city"
        * postalCode 0..1 string "postalCode" "postalCode"
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
  * careProvidingCareUnit 0..1 BackboneElement "careProvidingCareUnit" "careProvidingCareUnit"
    * hsaId 1..1 BackboneElement "hsaId" "hsaId"
      * root 1..1 string "root" "root"
      * iIExtension 0..1 string "iIExtension" "iIExtension Heter extension i schemat."
    * organizationName 0..1 string "organizationName" "organizationName Heter name i schemat."
    * contact 0..* BackboneElement "contact" "contact"
      * telecom 0..* BackboneElement "telecom" "telecom"
        * system 0..1 BackboneElement "system" "system"
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * contactPointSystemValue 1..1 string "contactPointSystemValue" "contactPointSystemValue Heter value i schemat."
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
      * address 0..1 BackboneElement "address" "address"
        * addressType 0..1 BackboneElement "addressType" "addressType Heter type i schemat."
          * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
          * codeSystem 0..1 string "codeSystem" "codeSystem"
          * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
          * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
          * displayName 0..1 string "displayName" "displayName"
          * originalText 0..1 string "originalText" "originalText"
        * line 0..* string "line" "line"
        * city 0..1 string "city" "city"
        * postalCode 0..1 string "postalCode" "postalCode"
        * period 0..* BackboneElement "period" "period"
          * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
            * start 1..1 string "start" "start"
            * end 0..1 string "end" "end"
          * weekDay 0..7 code "weekDay" "weekDay"
          * weekDay from WeekDaysVS (required)
          * month 0..* code "month" "month"
          * month from MonthsVS (required)
          * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
            * start 0..1 string "start" "start"
            * end 0..1 string "end" "end"
  * contact 0..* BackboneElement "contact" "contact"
    * telecom 0..* BackboneElement "telecom" "telecom"
      * system 0..1 BackboneElement "system" "system"
        * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
        * codeSystem 0..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * contactPointSystemValue 1..1 string "contactPointSystemValue" "contactPointSystemValue Heter value i schemat."
      * period 0..* BackboneElement "period" "period"
        * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
          * start 1..1 string "start" "start"
          * end 0..1 string "end" "end"
        * weekDay 0..7 code "weekDay" "weekDay"
        * weekDay from WeekDaysVS (required)
        * month 0..* code "month" "month"
        * month from MonthsVS (required)
        * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
          * start 0..1 string "start" "start"
          * end 0..1 string "end" "end"
    * address 0..1 BackboneElement "address" "address"
      * addressType 0..1 BackboneElement "addressType" "addressType Heter type i schemat."
        * cVCode 0..1 string "cVCode" "cVCode Heter code i schemat."
        * codeSystem 0..1 string "codeSystem" "codeSystem"
        * codeSystemName 0..1 string "codeSystemName" "codeSystemName"
        * codeSystemVersion 0..1 string "codeSystemVersion" "codeSystemVersion"
        * displayName 0..1 string "displayName" "displayName"
        * originalText 0..1 string "originalText" "originalText"
      * line 0..* string "line" "line"
      * city 0..1 string "city" "city"
      * postalCode 0..1 string "postalCode" "postalCode"
      * period 0..* BackboneElement "period" "period"
        * datePeriod 0..1 BackboneElement "datePeriod" "datePeriod"
          * start 1..1 string "start" "start"
          * end 0..1 string "end" "end"
        * weekDay 0..7 code "weekDay" "weekDay"
        * weekDay from WeekDaysVS (required)
        * month 0..* code "month" "month"
        * month from MonthsVS (required)
        * time 0..1 BackboneElement "time" "Används för att specificera ett tidsintervall med hjälp av start- och sluttid. start: Starttid på formatet HHmmss end: Sluttid på formatet HHmmss"
          * start 0..1 string "start" "start"
          * end 0..1 string "end" "end"
