id: inera.informatics-terminology
canonical: https://fhir.inera.se/ig/informatics-terminology
name: informaticsterminology
title: "informatics: terminology"
status: draft
version: 1.4
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: draft

dependencies:
  hl7.fhir.r4.core: 4.0.1

pages:
  index.md:
    title: Hem
  1-inledning.md:
    title: 1 Inledning
  2-generella-regler.md:
    title: 2 Generella regler
  3-sla-krav-support.md:
    title: 3 SLA-krav/support
  4-tjanstekontrakt.md:
    title: 4 Tjänstekontrakt
  5-tillgangliga-urval.md:
    title: 5 Tillgängliga urval

menu:
  Home: index.html
  1 Inledning: 1-inledning.html
  2 Generella regler: 2-generella-regler.html
  3 SLA-krav/support: 3-sla-krav-support.html
  4 Tjänstekontrakt: 4-tjanstekontrakt.html
  5 Tillgängliga urval: 5-tillgangliga-urval.html
  Artifacts: artifacts.html

parameters:
  show-inherited-invariants: false
  apply-contact: true
  apply-publisher: true
  apply-version: true
  apply-copyright: true

publisher: Inera AB
contact:
  - name: Inera Arkitektur
    telecom:
      - system: url
        value: https://www.inera.se
copyright: >-
  Copyright 2024 Inera AB. Licensieras under Creative Commons Attribution 4.0.
