<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Inera licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions name='AttachMedicationDispenseAuthorizationInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' 
  xmlns:tjsr='urn:riv:clinicalprocess:activityprescription:prescribe:AttachMedicationDispenseAuthorizationResponder:2' 
  xmlns:tjsi='urn:riv:clinicalprocess:activityprescription:prescribe:AttachMedicationDispenseAuthorizationInitiator:2' 
  xmlns:tns='urn:riv:clinicalprocess:activityprescription:prescribe:AttachMedicationDispenseAuthorization:2:rivtabp21' 
  targetNamespace='urn:riv:clinicalprocess:activityprescription:prescribe:AttachMedicationDispenseAuthorization:2:rivtabp21' 
  xmlns:itr='urn:riv:itintegration:registry:1'>
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: AttachMedicationDispenseAuthorizationInteraction
			 Beskrivning: 
			   vård- och omsorg kärnprocess: hantera aktiviteter:ordination
			 Revisioner: 
			 Tjänstedomän: clinicalprocess:activityprescription:prescribe
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP21
			 Förvaltas av: Inera
			 </xs:documentation>
  </xs:annotation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:clinicalprocess:activityprescription:prescribe:AttachMedicationDispenseAuthorization:2:rivtabp21'>
      <xs:import schemaLocation='AttachMedicationDispenseAuthorizationResponder_2.0.xsd' namespace='urn:riv:clinicalprocess:activityprescription:prescribe:AttachMedicationDispenseAuthorizationResponder:2' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='AttachMedicationDispenseAuthorizationRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
      <wsdl:documentation>The organisation number of the receiving insurance institution</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:AttachMedicationDispenseAuthorization' />
  </wsdl:message>
  <wsdl:message name='AttachMedicationDispenseAuthorizationResponse'>
    <wsdl:part name='parameters' element='tjsr:AttachMedicationDispenseAuthorizationResponse' />
  </wsdl:message>
  <wsdl:portType name='AttachMedicationDispenseAuthorizationResponderInterface'>
    <wsdl:operation name='AttachMedicationDispenseAuthorization'>
      <wsdl:input message='tns:AttachMedicationDispenseAuthorizationRequest' />
      <wsdl:output message='tns:AttachMedicationDispenseAuthorizationResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='AttachMedicationDispenseAuthorizationResponderBinding' type='tns:AttachMedicationDispenseAuthorizationResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='AttachMedicationDispenseAuthorization'>
      <soap:operation soapAction='urn:riv:clinicalprocess:activityprescription:prescribe:AttachMedicationDispenseAuthorizationResponder:1:AttachMedicationDispenseAuthorization' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:AttachMedicationDispenseAuthorizationRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='AttachMedicationDispenseAuthorizationResponderService'>
    <wsdl:port name='AttachMedicationDispenseAuthorizationResponderPort' binding='tns:AttachMedicationDispenseAuthorizationResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
