<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Inera AB licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->	
<wsdl:definitions name='UnregisterTemporaryRevokeInteraction'
	xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
	xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
	xmlns:xs='http://www.w3.org/2001/XMLSchema'
	xmlns:tjsr='urn:riv:ehr:blocking:synchronization:UnregisterTemporaryRevokeResponder:2'
	xmlns:itr='urn:riv:itintegration:registry:1'
	xmlns:tns='urn:riv:ehr:blocking:synchronization:UnregisterTemporaryRevoke:2:rivtabp21'
	targetNamespace='urn:riv:ehr:blocking:synchronization:UnregisterTemporaryRevoke:2:rivtabp21'>

	<wsdl:documentation xml:lang='sv'>
		 Tjänsteinteraktionens namn: UnregisterTemporaryRevoke
		 Beskrivning: 
		   Tjänst som avregistrerar/raderar en tillfällig hävning i den nationella spärrtjänsten, om hävningen finns.
		   Tjänsten används för att synkronisera borttag av en lokal tillfällig hävning till den nationella spärrtjänsten.
		   Tjänsten realiseras på nationell nivå.
		 Revisioner: 
		 Tjänstedomän: blocking:synchronization
		 Tjänsteinteraktionstyp: Fråga-Svar
		 WS-profil: RIVTABP21
		 Förvaltas av: Inera AB
	</wsdl:documentation>
	
	<wsdl:types>
		<xs:schema targetNamespace='urn:riv:ehr:blocking:synchronization:UnregisterTemporaryRevoke:2:rivtabp21'>
			<xs:import schemaLocation='UnregisterTemporaryRevokeResponder_2.0.xsd' namespace='urn:riv:ehr:blocking:synchronization:UnregisterTemporaryRevokeResponder:2' />
			<xs:import schemaLocation='../../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
		</xs:schema>
	</wsdl:types>
	
		
	<wsdl:message name='UnregisterTemporaryRevokeRequest'>
		<wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
			<wsdl:documentation xml:lang='sv'>Som logisk adress anges HSA-id för vårdgivaren som spärren gäller för.</wsdl:documentation>
		</wsdl:part>
	
		<wsdl:part name='parameters' element='tjsr:UnregisterTemporaryRevokeRequest' />
	</wsdl:message>

	<wsdl:message name='UnregisterTemporaryRevokeResponse'>
		<wsdl:part name='parameters' element='tjsr:UnregisterTemporaryRevokeResponse' />
	</wsdl:message>

	<wsdl:portType name='UnregisterTemporaryRevokeResponderInterface'>
		<wsdl:operation name='UnregisterTemporaryRevoke'>
			<wsdl:input message='tns:UnregisterTemporaryRevokeRequest' />
			<wsdl:output message='tns:UnregisterTemporaryRevokeResponse' />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name='UnregisterTemporaryRevokeResponderBinding' type='tns:UnregisterTemporaryRevokeResponderInterface'>
		<soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
		<wsdl:operation name='UnregisterTemporaryRevoke'>
			<soap:operation soapAction='urn:riv:ehr:blocking:synchronization:UnregisterTemporaryRevokeResponder:2:UnregisterTemporaryRevoke' style='document' />
			<wsdl:input>
				<soap:header use='literal' message='tns:UnregisterTemporaryRevokeRequest' part='LogicalAddress' />
				<soap:body use='literal' parts='parameters' />
			</wsdl:input>
			<wsdl:output>
				<soap:body use='literal' />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name='UnregisterTemporaryRevokeResponderService'>
		<wsdl:port name='UnregisterTemporaryRevokeResponderPort' binding='tns:UnregisterTemporaryRevokeResponderBinding'>
			<soap:address location='http://tempuri.org' />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
