// Genererad från XSD för strategicresourcemanagement.persons.person v5.1 (Genererat ur domänens XSD (tagg 5.1).; scripts/xsd_to_ig.py)
// Kontrakt: GetPersonsForProfileUnrestricted v5.0
// Genererad: 2026-09-26

Logical: GetPersonsForProfileUnrestricted
Id: getpersonsforprofileunrestricted
Title: "GetPersonsForProfileUnrestricted — Response"
Description: """
  Logisk modell för svaret i GetPersonsForProfileUnrestricted
  (urn:riv:strategicresourcemanagement:persons:person:GetPersonsForProfileUnrestrictedResponder:5, GetPersonsForProfileUnrestrictedResponseType).
"""
Characteristics: #can-be-target
* requestedPersonRecord 1..* BackboneElement "requestedPersonRecord" "requestedPersonRecord"
  * requestedPersonalIdentity 1..1 BackboneElement "requestedPersonalIdentity" "En universellt unik identifierare."
    * root 1..1 string "root" "root"
    * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
  * personRecord 0..1 BackboneElement "personRecord" "Grupp för personpost"
    * personalIdentity 1..1 BackboneElement "personalIdentity" "En universellt unik identifierare."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * identityLevel 0..1 string "identityLevel" "identityLevel"
    * identityLevelDate 0..1 BackboneElement "identityLevelDate" "Kan beskriva ett datum med variabel noggrannhet."
      * format 1..1 code "format" "format"
      * format from DateTypeFormatVS (required)
      * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
    * gender 0..1 string "gender" "gender"
    * protectedPersonIndicator 1..1 boolean "protectedPersonIndicator" "protectedPersonIndicator"
    * testIndicator 1..1 boolean "testIndicator" "testIndicator"
    * primaryIdentity 1..1 boolean "primaryIdentity" "primaryIdentity"
    * personRecordVersion 0..1 string "personRecordVersion" "personRecordVersion Heter version i schemat."
    * personRecordName 0..1 BackboneElement "personRecordName" "Namn Heter name i schemat."
      * givenNameIndicator 0..1 integer "givenNameIndicator" "givenNameIndicator"
      * givenName 0..1 string "givenName" "givenName"
      * middleName 0..1 string "middleName" "middleName"
      * surname 0..1 string "surname" "surname"
      * notificationName 0..1 string "notificationName" "notificationName"
    * linkedIdentity 0..* BackboneElement "linkedIdentity" "Klass för att koppla ihop 2 identiteter. Ex en nationell reservidentitet till ett PNR"
      * referredPersonalIdentity 1..1 BackboneElement "referredPersonalIdentity" "En universellt unik identifierare."
        * root 1..1 string "root" "root"
        * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * assuranceLevel 1..1 string "assuranceLevel" "assuranceLevel"
      * primaryIdentity 1..1 boolean "primaryIdentity" "primaryIdentity"
    * referredPersonalIdentities 0..* BackboneElement "referredPersonalIdentities" "Klass för Hänvisningspersonnummer. För de personer som bytt personnummer anges tidigare personnummer/samordningsnummer som hänvisningspersonnummer. Det gamla personnumret/samordningsnumret utgör även det en egen personpost. I det fallet anges det nya personnumret som hänvisningspersonnummer. En person kan få nytt personnummer efter exempelvis ändring av en persons födelsetid eller vid beslut om ändrad könstillhörighet. Klassen håller ihop personidentiteter av typerna personnummer och samordningsnummer enligt Skatteverket till skillnad från klassen KoppladIdenitet som är Personuppgiftstjänstens egna klass för att kunna koppla ihop alla typer av personidentiteter (inkl. reservidentiteter)."
      * referredPersonalIdentity 1..1 BackboneElement "referredPersonalIdentity" "En universellt unik identifierare."
        * root 1..1 string "root" "root"
        * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * referredPersonalIdentityStatus 0..1 string "referredPersonalIdentityStatus" "referredPersonalIdentityStatus"
    * birth 0..1 BackboneElement "birth" "Uppgifter om födelse"
      * dateOfBirth 0..1 BackboneElement "dateOfBirth" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * placeOfBirthSweden 0..1 BackboneElement "placeOfBirthSweden" "Uppgifter om hemort i Sverige"
        * birthCountyCode 0..1 string "birthCountyCode" "birthCountyCode"
        * birthParish 0..1 string "birthParish" "birthParish"
      * birthAbroad 0..1 BackboneElement "birthAbroad" "Uppgifter om födelse i utlandet"
        * placeOfBirthAbroad 0..1 string "placeOfBirthAbroad" "placeOfBirthAbroad"
        * countryOfBirth 0..1 string "countryOfBirth" "countryOfBirth"
    * populationRegistrationLocality 0..1 BackboneElement "populationRegistrationLocality" "Uppgifter om folkbokföring"
      * populationRegistrationDate 0..1 BackboneElement "populationRegistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * countyCode 0..1 string "countyCode" "countyCode"
      * municipalityCode 0..1 string "municipalityCode" "municipalityCode"
      * parishCode 0..1 string "parishCode" "parishCode"
      * propertyDesignation 0..1 string "propertyDesignation" "propertyDesignation"
      * fictitiousPropertyNumber 0..1 integer "fictitiousPropertyNumber" "fictitiousPropertyNumber"
      * populationRegistrationType 0..1 string "populationRegistrationType" "populationRegistrationType"
      * localRegistrationTime 0..1 dateTime "localRegistrationTime" "localRegistrationTime"
      * localRegistrationEndTime 0..1 dateTime "localRegistrationEndTime" "localRegistrationEndTime"
    * populationRegistrationRecord 0..1 BackboneElement "populationRegistrationRecord" "Folkbokföringspost"
      * syncronizationTime 0..1 dateTime "syncronizationTime" "syncronizationTime"
      * notificationCase 0..1 BackboneElement "notificationCase" "Ärendeuppgifter"
        * recordId 0..1 string "recordId" "recordId"
        * notificationType 0..1 string "notificationType" "notificationType"
        * modificationTime 0..1 dateTime "modificationTime" "modificationTime"
        * totalRecord 0..1 boolean "totalRecord" "totalRecord"
        * notificationDate 0..1 BackboneElement "notificationDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * historicalRecords 0..1 BackboneElement "historicalRecords" "Grupp för historik"
        * populationRegistrationLocality 0..* BackboneElement "populationRegistrationLocality" "Uppgifter om folkbokföring"
          * populationRegistrationDate 0..1 BackboneElement "populationRegistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
            * format 1..1 code "format" "format"
            * format from DateTypeFormatVS (required)
            * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
          * countyCode 0..1 string "countyCode" "countyCode"
          * municipalityCode 0..1 string "municipalityCode" "municipalityCode"
          * parishCode 0..1 string "parishCode" "parishCode"
          * propertyDesignation 0..1 string "propertyDesignation" "propertyDesignation"
          * fictitiousPropertyNumber 0..1 integer "fictitiousPropertyNumber" "fictitiousPropertyNumber"
          * populationRegistrationType 0..1 string "populationRegistrationType" "populationRegistrationType"
          * localRegistrationTime 0..1 dateTime "localRegistrationTime" "localRegistrationTime"
          * localRegistrationEndTime 0..1 dateTime "localRegistrationEndTime" "localRegistrationEndTime"
        * historicalAddress 0..1 BackboneElement "historicalAddress" "Svensk adress"
          * careOf 0..1 string "careOf" "careOf"
          * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
          * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
          * postalCode 0..1 integer "postalCode" "postalCode"
          * city 0..1 string "city" "city"
    * addressInformation 0..1 BackboneElement "addressInformation" "Grupp för adressuppgifter"
      * residentialAddress 0..1 BackboneElement "residentialAddress" "Svensk adress"
        * careOf 0..1 string "careOf" "careOf"
        * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
        * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
        * postalCode 0..1 integer "postalCode" "postalCode"
        * city 0..1 string "city" "city"
      * nationalKeys 0..1 BackboneElement "nationalKeys" "Riksnycklar"
        * propertyId 0..1 string "propertyId" "propertyId"
        * addressPlaceId 0..1 string "addressPlaceId" "addressPlaceId"
        * apartmentId 0..1 string "apartmentId" "apartmentId"
      * district 0..1 BackboneElement "district" "Grupp för Distriktskod"
        * districtCode 0..1 string "districtCode" "districtCode"
      * specialPostalAddress 0..1 BackboneElement "specialPostalAddress" "Svensk adress"
        * careOf 0..1 string "careOf" "careOf"
        * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
        * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
        * postalCode 0..1 integer "postalCode" "postalCode"
        * city 0..1 string "city" "city"
      * addressAbroad 0..1 BackboneElement "addressAbroad" "Utlandsadress"
        * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
        * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
        * postalAddress3 0..1 string "postalAddress3" "postalAddress3"
        * countryCode 0..1 string "countryCode" "countryCode"
        * addressAbroadDate 0..1 BackboneElement "addressAbroadDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * votingDate 0..1 BackboneElement "votingDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * givenAddress 0..1 BackboneElement "givenAddress" "Svensk adress"
        * careOf 0..1 string "careOf" "careOf"
        * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
        * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
        * postalCode 0..1 integer "postalCode" "postalCode"
        * city 0..1 string "city" "city"
      * UUID 0..1 BackboneElement "UUID" "UUID för fastighet, aderess och lägenhet"
        * propertyId 0..1 string "propertyId" "propertyId"
        * addressPlaceId 0..1 string "addressPlaceId" "addressPlaceId"
        * apartmentId 0..1 string "apartmentId" "apartmentId"
    * contactInformation 0..* BackboneElement "contactInformation" "Klass för patientens egna angivna kontakuppgifter"
      * contactType 1..1 string "contactType" "contactType"
      * use 0..1 string "use" "use"
      * contactInformationValue 0..1 string "contactInformationValue" "contactInformationValue Heter value i schemat."
      * rank 0..1 integer "rank" "rank"
      * comment 0..1 string "comment" "comment"
      * period 0..1 BackboneElement "period" "period"
        * start 0..1 date "start" "start"
        * end 0..1 date "end" "end"
      * digitalNotification 0..1 boolean "digitalNotification" "digitalNotification"
    * contactPerson 0..* BackboneElement "contactPerson" "contactPerson"
      * contactRelationshipType 1..1 string "contactRelationshipType" "contactRelationshipType"
      * priorityOrder 0..1 integer "priorityOrder" "priorityOrder"
      * givenName 0..1 string "givenName" "givenName"
      * surName 0..1 string "surName" "surName"
      * middleName 0..1 string "middleName" "middleName"
      * contactPersonAddress 0..1 BackboneElement "contactPersonAddress" "Svensk adress"
        * careOf 0..1 string "careOf" "careOf"
        * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
        * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
        * postalCode 0..1 integer "postalCode" "postalCode"
        * city 0..1 string "city" "city"
      * contactPersonContactInformation 0..* BackboneElement "contactPersonContactInformation" "Klass för patientens egna angivna kontakuppgifter"
        * contactType 1..1 string "contactType" "contactType"
        * use 0..1 string "use" "use"
        * contactInformationValue 0..1 string "contactInformationValue" "contactInformationValue Heter value i schemat."
        * rank 0..1 integer "rank" "rank"
        * comment 0..1 string "comment" "comment"
        * period 0..1 BackboneElement "period" "period"
          * start 0..1 date "start" "start"
          * end 0..1 date "end" "end"
        * digitalNotification 0..1 boolean "digitalNotification" "digitalNotification"
    * confirmedIdentity 0..* BackboneElement "confirmedIdentity" "Klass för hur reservidentitetsuppgifter är styrkta."
      * typeOfIdentification 0..1 string "typeOfIdentification" "typeOfIdentification"
      * identificationNumber 0..1 string "identificationNumber" "identificationNumber"
      * issuersOfId 0..1 string "issuersOfId" "issuersOfId"
      * validDatePeriod 0..1 BackboneElement "validDatePeriod" "validDatePeriod"
        * start 0..1 date "start" "start"
        * end 0..1 date "end" "end"
      * attachmentId 0..* string "attachmentId" "attachmentId"
      * countryCode 0..1 string "countryCode" "countryCode"
    * administrativeInformation 0..1 BackboneElement "administrativeInformation" "Klass för administrativa tilläggsuppgifter. Normalt tilläggsuppgifter kring en person med en reservidentitet som registreras i samband med uttag av reservidentitet (LRID/NRID)."
      * categoryOfPerson 0..1 string "categoryOfPerson" "categoryOfPerson"
      * accountCode 0..1 string "accountCode" "accountCode"
      * comment 0..1 string "comment" "comment"
    * deregistration 0..1 BackboneElement "deregistration" "Uppgifter om avregistrering"
      * deregistrationReasonCode 0..1 string "deregistrationReasonCode" "deregistrationReasonCode"
      * deregistrationDate 0..1 BackboneElement "deregistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * foundDeadAtDate 0..1 BackboneElement "foundDeadAtDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
    * maritalStatus 0..1 BackboneElement "maritalStatus" "Civistånd"
      * maritalStatusCode 0..1 string "maritalStatusCode" "maritalStatusCode"
      * maritalStatusDate 0..1 BackboneElement "maritalStatusDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
    * immigration 0..1 BackboneElement "immigration" "Grupp för invandringsuppgifter"
      * immigrationDate 0..1 BackboneElement "immigrationDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * rightOfResidence 0..1 boolean "rightOfResidence" "rightOfResidence"
      * immigrationIdentity 0..* BackboneElement "immigrationIdentity" "Grupp för personnummer och vilket land det är knutet till. Motsvarar skatteverkets NordisktPnrDa, NordisktPnrFi, NordisktPnrFo, NordisktPnrIs och NordisktPnrNo"
        * personalIdentityNumber 1..1 string "personalIdentityNumber" "personalIdentityNumber"
        * country 1..1 string "country" "country"
    * citizenship 0..* BackboneElement "citizenship" "Grupp för medborgarskap"
      * citizenshipCountryCode 0..1 string "citizenshipCountryCode" "citizenshipCountryCode"
      * citizenshipDate 0..1 BackboneElement "citizenshipDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * citizenshipStatus 0..1 string "citizenshipStatus" "citizenshipStatus Heter status i schemat."
    * relationship 0..* BackboneElement "relationship" "Grupp för relation"
      * relationshipId 1..1 BackboneElement "relationshipId" "Grupp för relationspersons identitet Antingen får man personnummer eller datum då personen föddes."
        * personalIdentity 0..1 BackboneElement "personalIdentity" "En universellt unik identifierare."
          * root 1..1 string "root" "root"
          * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
        * dateOfBirth 0..1 BackboneElement "dateOfBirth" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * relationshipType 1..1 string "relationshipType" "relationshipType"
      * relationshipFromDate 0..1 BackboneElement "relationshipFromDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * relationshipToDate 0..1 BackboneElement "relationshipToDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * relationshipName 0..1 BackboneElement "relationshipName" "Namn Heter name i schemat."
        * givenNameIndicator 0..1 integer "givenNameIndicator" "givenNameIndicator"
        * givenName 0..1 string "givenName" "givenName"
        * middleName 0..1 string "middleName" "middleName"
        * surname 0..1 string "surname" "surname"
        * notificationName 0..1 string "notificationName" "notificationName"
      * deregistration 0..1 BackboneElement "deregistration" "Uppgifter om avregistrering"
        * deregistrationReasonCode 0..1 string "deregistrationReasonCode" "deregistrationReasonCode"
        * deregistrationDate 0..1 BackboneElement "deregistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
        * foundDeadAtDate 0..1 BackboneElement "foundDeadAtDate" "Kan beskriva ett datum med variabel noggrannhet."
          * format 1..1 code "format" "format"
          * format from DateTypeFormatVS (required)
          * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * relationshipStatus 0..1 string "relationshipStatus" "relationshipStatus Heter status i schemat."
    * coOrdinationNumberData 0..1 BackboneElement "coOrdinationNumberData" "Grupp för de personer som ej är folkbokförda men som har tilldelats ett samordningsnummer för identifiering av personen. Syftet med samordningsnummer är att myndigheter och andra samhällsfunktioner ska kunna identifiera personer även om de inte är folkbokförda i Sverige."
      * allocationDate 0..1 BackboneElement "allocationDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * preliminaryTransferDate 0..1 BackboneElement "preliminaryTransferDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * renewalDate 0..1 BackboneElement "renewalDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * deceasedDate 0..1 BackboneElement "deceasedDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
    * personalIdentityStatus 0..1 BackboneElement "personalIdentityStatus" "Klass som beskriver status för ett samordningsnummer. Status, datum och orsak ska vara obligatoriska uppgifter, när de finns, för aviseringar innehållande samordningsnummer."
      * identityStatus 0..1 string "identityStatus" "identityStatus"
      * identityStatusDate 0..1 BackboneElement "identityStatusDate" "Kan beskriva ett datum med variabel noggrannhet."
        * format 1..1 code "format" "format"
        * format from DateTypeFormatVS (required)
        * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
      * identityStatusCause 0..1 string "identityStatusCause" "identityStatusCause"
    * updatePersonActor 0..1 BackboneElement "updatePersonActor" "Datatyp som identifierar en aktör."
      * actorId 1..1 BackboneElement "actorId" "En universellt unik identifierare. Heter id i schemat."
        * root 1..1 string "root" "root"
        * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * professional 0..1 BackboneElement "professional" "Datatyp som identifierar en aktör inom en profession."
        * organizationId 1..1 BackboneElement "organizationId" "En universellt unik identifierare."
          * root 1..1 string "root" "root"
          * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * updateTime 0..1 string "updateTime" "updateTime"
    * updatePersonContactInformationActor 0..1 BackboneElement "updatePersonContactInformationActor" "Datatyp som identifierar en aktör."
      * actorId 1..1 BackboneElement "actorId" "En universellt unik identifierare. Heter id i schemat."
        * root 1..1 string "root" "root"
        * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * professional 0..1 BackboneElement "professional" "Datatyp som identifierar en aktör inom en profession."
        * organizationId 1..1 BackboneElement "organizationId" "En universellt unik identifierare."
          * root 1..1 string "root" "root"
          * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
      * updateTime 0..1 string "updateTime" "updateTime"
    * attachment 0..* BackboneElement "attachment" "Datatyp som beskriver en multimediatyp. Data kan förekomma som inbäddat element eller hänvisas via en referens URL."
      * multimediaId 0..1 string "multimediaId" "multimediaId Heter id i schemat."
      * mediaType 1..1 string "mediaType" "mediaType"
      * multimediaValue 0..1 base64Binary "multimediaValue" "multimediaValue Heter value i schemat."
      * reference 0..1 uri "reference" "reference"
    * optoutPaperNotification 0..1 boolean "optoutPaperNotification" "optoutPaperNotification"
    * protectedPopulationRecord 0..1 boolean "protectedPopulationRecord" "protectedPopulationRecord"
