// Genererad från XSD för strategicresourcemanagement.persons.person v5.1 (Genererat ur domänens XSD (tagg 5.1).; scripts/xsd_to_ig.py)
// Kontrakt: GetPersonContactInformation v4.0
// Genererad: 2026-09-26

Logical: GetPersonContactInformation
Id: getpersoncontactinformation
Title: "GetPersonContactInformation — Response"
Description: """
  Logisk modell för svaret i GetPersonContactInformation
  (urn:riv:strategicresourcemanagement:persons:person:GetPersonContactInformationResponder:4, GetPersonContactInformationResponseType).
"""
Characteristics: #can-be-target
* ^version = "4.0"
* contactInformationRecord 0..1 BackboneElement "contactInformationRecord" "Uppgifter om personens kontaktuppgifter och kontaktpersoner"
  * contactInformationRecordVersion 1..1 string "contactInformationRecordVersion" "contactInformationRecordVersion Heter version i schemat."
  * personId 1..1 BackboneElement "personId" "En universellt unik identifierare."
    * root 1..1 string "root" "root"
    * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
  * contactInformation 0..* BackboneElement "contactInformation" "Klass för patientens egna angivna kontakuppgifter"
    * contactType 1..1 string "contactType" "contactType"
    * use 0..1 string "use" "use"
    * contactInformationValue 0..1 string "contactInformationValue" "contactInformationValue Heter value i schemat."
    * rank 0..1 integer "rank" "rank"
    * comment 0..1 string "comment" "comment"
    * period 0..1 BackboneElement "period" "period"
      * start 0..1 date "start" "start"
      * end 0..1 date "end" "end"
    * digitalNotification 0..1 boolean "digitalNotification" "digitalNotification"
  * contactPerson 0..* BackboneElement "contactPerson" "contactPerson"
    * contactRelationshipType 1..1 string "contactRelationshipType" "contactRelationshipType"
    * priorityOrder 0..1 integer "priorityOrder" "priorityOrder"
    * givenName 0..1 string "givenName" "givenName"
    * surName 0..1 string "surName" "surName"
    * middleName 0..1 string "middleName" "middleName"
    * contactPersonAddress 0..1 BackboneElement "contactPersonAddress" "Svensk adress"
      * careOf 0..1 string "careOf" "careOf"
      * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
      * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
      * postalCode 0..1 integer "postalCode" "postalCode"
      * city 0..1 string "city" "city"
    * contactPersonContactInformation 0..* BackboneElement "contactPersonContactInformation" "Klass för patientens egna angivna kontakuppgifter"
      * contactType 1..1 string "contactType" "contactType"
      * use 0..1 string "use" "use"
      * contactInformationValue 0..1 string "contactInformationValue" "contactInformationValue Heter value i schemat."
      * rank 0..1 integer "rank" "rank"
      * comment 0..1 string "comment" "comment"
      * period 0..1 BackboneElement "period" "period"
        * start 0..1 date "start" "start"
        * end 0..1 date "end" "end"
      * digitalNotification 0..1 boolean "digitalNotification" "digitalNotification"
  * protectedPersonIndicator 1..1 boolean "protectedPersonIndicator" "protectedPersonIndicator"
  * protectedPopulationRecord 0..1 boolean "protectedPopulationRecord" "protectedPopulationRecord"
  * optoutPaperNotification 0..1 boolean "optoutPaperNotification" "optoutPaperNotification"
  * updatePersonContactInformationActor 0..1 BackboneElement "updatePersonContactInformationActor" "Datatyp som identifierar en aktör."
    * actorId 1..1 BackboneElement "actorId" "En universellt unik identifierare. Heter id i schemat."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * professional 0..1 BackboneElement "professional" "Datatyp som identifierar en aktör inom en profession."
      * organizationId 1..1 BackboneElement "organizationId" "En universellt unik identifierare."
        * root 1..1 string "root" "root"
        * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * updateTime 0..1 string "updateTime" "updateTime"
