// Genererad från XSD för strategicresourcemanagement.persons.person v5.1 (Genererat ur domänens XSD (tagg 5.1).; scripts/xsd_to_ig.py)
// Kontrakt: UpdatePerson v5.0
// Genererad: 2026-09-26

Logical: UpdatePersonRequest
Id: updateperson-request
Title: "UpdatePerson — Request"
Description: """
  Logisk modell för begäran i UpdatePerson
  (urn:riv:strategicresourcemanagement:persons:person:UpdatePersonResponder:5, UpdatePersonType), inklusive SOAP-huvuden enligt WSDL.
"""
Characteristics: #can-be-target
* logicalAddress 1..1 string "logicalAddress" "SOAP-huvud LogicalAddress. http://tempuri.org"
* actor 1..1 BackboneElement "actor" "Datatyp som identifierar en aktör."
  * actorId 1..1 BackboneElement "actorId" "En universellt unik identifierare. Heter id i schemat."
    * root 1..1 string "root" "root"
    * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
  * professional 0..1 BackboneElement "professional" "Datatyp som identifierar en aktör inom en profession."
    * organizationId 1..1 BackboneElement "organizationId" "En universellt unik identifierare."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
  * updateTime 0..1 string "updateTime" "updateTime"
* personId 0..1 BackboneElement "personId" "En universellt unik identifierare."
  * root 1..1 string "root" "root"
  * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
* gender 0..1 string "gender" "gender"
* versionToUpdate 0..1 string "versionToUpdate" "versionToUpdate"
* updatePersonName 0..1 BackboneElement "updatePersonName" "Namn Heter name i schemat."
  * givenNameIndicator 0..1 integer "givenNameIndicator" "givenNameIndicator"
  * givenName 0..1 string "givenName" "givenName"
  * middleName 0..1 string "middleName" "middleName"
  * surname 0..1 string "surname" "surname"
  * notificationName 0..1 string "notificationName" "notificationName"
* birth 0..1 BackboneElement "birth" "Uppgifter om födelse"
  * dateOfBirth 0..1 BackboneElement "dateOfBirth" "Kan beskriva ett datum med variabel noggrannhet."
    * format 1..1 code "format" "format"
    * format from DateTypeFormatVS (required)
    * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
  * placeOfBirthSweden 0..1 BackboneElement "placeOfBirthSweden" "Uppgifter om hemort i Sverige"
    * birthCountyCode 0..1 string "birthCountyCode" "birthCountyCode"
    * birthParish 0..1 string "birthParish" "birthParish"
  * birthAbroad 0..1 BackboneElement "birthAbroad" "Uppgifter om födelse i utlandet"
    * placeOfBirthAbroad 0..1 string "placeOfBirthAbroad" "placeOfBirthAbroad"
    * countryOfBirth 0..1 string "countryOfBirth" "countryOfBirth"
* relationship 0..* BackboneElement "relationship" "Grupp för relation"
  * relationshipId 1..1 BackboneElement "relationshipId" "Grupp för relationspersons identitet Antingen får man personnummer eller datum då personen föddes."
    * personalIdentity 0..1 BackboneElement "personalIdentity" "En universellt unik identifierare."
      * root 1..1 string "root" "root"
      * iiExtension 0..1 string "iiExtension" "iiExtension Heter extension i schemat."
    * dateOfBirth 0..1 BackboneElement "dateOfBirth" "Kan beskriva ett datum med variabel noggrannhet."
      * format 1..1 code "format" "format"
      * format from DateTypeFormatVS (required)
      * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
  * relationshipType 1..1 string "relationshipType" "relationshipType"
  * relationshipFromDate 0..1 BackboneElement "relationshipFromDate" "Kan beskriva ett datum med variabel noggrannhet."
    * format 1..1 code "format" "format"
    * format from DateTypeFormatVS (required)
    * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
  * relationshipToDate 0..1 BackboneElement "relationshipToDate" "Kan beskriva ett datum med variabel noggrannhet."
    * format 1..1 code "format" "format"
    * format from DateTypeFormatVS (required)
    * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
  * relationshipName 0..1 BackboneElement "relationshipName" "Namn Heter name i schemat."
    * givenNameIndicator 0..1 integer "givenNameIndicator" "givenNameIndicator"
    * givenName 0..1 string "givenName" "givenName"
    * middleName 0..1 string "middleName" "middleName"
    * surname 0..1 string "surname" "surname"
    * notificationName 0..1 string "notificationName" "notificationName"
  * deregistration 0..1 BackboneElement "deregistration" "Uppgifter om avregistrering"
    * deregistrationReasonCode 0..1 string "deregistrationReasonCode" "deregistrationReasonCode"
    * deregistrationDate 0..1 BackboneElement "deregistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
      * format 1..1 code "format" "format"
      * format from DateTypeFormatVS (required)
      * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
    * foundDeadAtDate 0..1 BackboneElement "foundDeadAtDate" "Kan beskriva ett datum med variabel noggrannhet."
      * format 1..1 code "format" "format"
      * format from DateTypeFormatVS (required)
      * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
  * relationshipStatus 0..1 string "relationshipStatus" "relationshipStatus Heter status i schemat."
* givenAddress 0..1 BackboneElement "givenAddress" "Svensk adress"
  * careOf 0..1 string "careOf" "careOf"
  * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
  * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
  * postalCode 0..1 integer "postalCode" "postalCode"
  * city 0..1 string "city" "city"
* deregistration 0..1 BackboneElement "deregistration" "Uppgifter om avregistrering"
  * deregistrationReasonCode 0..1 string "deregistrationReasonCode" "deregistrationReasonCode"
  * deregistrationDate 0..1 BackboneElement "deregistrationDate" "Kan beskriva ett datum med variabel noggrannhet."
    * format 1..1 code "format" "format"
    * format from DateTypeFormatVS (required)
    * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
  * foundDeadAtDate 0..1 BackboneElement "foundDeadAtDate" "Kan beskriva ett datum med variabel noggrannhet."
    * format 1..1 code "format" "format"
    * format from DateTypeFormatVS (required)
    * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
* administrativeInformation 0..1 BackboneElement "administrativeInformation" "Klass för administrativa tilläggsuppgifter. Normalt tilläggsuppgifter kring en person med en reservidentitet som registreras i samband med uttag av reservidentitet (LRID/NRID)."
  * categoryOfPerson 0..1 string "categoryOfPerson" "categoryOfPerson"
  * accountCode 0..1 string "accountCode" "accountCode"
  * comment 0..1 string "comment" "comment"
* confirmedIdentity 0..* BackboneElement "confirmedIdentity" "Klass för hur reservidentitetsuppgifter är styrkta."
  * typeOfIdentification 0..1 string "typeOfIdentification" "typeOfIdentification"
  * identificationNumber 0..1 string "identificationNumber" "identificationNumber"
  * issuersOfId 0..1 string "issuersOfId" "issuersOfId"
  * validDatePeriod 0..1 BackboneElement "validDatePeriod" "validDatePeriod"
    * start 0..1 date "start" "start"
    * end 0..1 date "end" "end"
  * attachmentId 0..* string "attachmentId" "attachmentId"
  * countryCode 0..1 string "countryCode" "countryCode"
* addressAbroad 0..1 BackboneElement "addressAbroad" "Utlandsadress"
  * postalAddress1 0..1 string "postalAddress1" "postalAddress1"
  * postalAddress2 0..1 string "postalAddress2" "postalAddress2"
  * postalAddress3 0..1 string "postalAddress3" "postalAddress3"
  * countryCode 0..1 string "countryCode" "countryCode"
  * addressAbroadDate 0..1 BackboneElement "addressAbroadDate" "Kan beskriva ett datum med variabel noggrannhet."
    * format 1..1 code "format" "format"
    * format from DateTypeFormatVS (required)
    * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
  * votingDate 0..1 BackboneElement "votingDate" "Kan beskriva ett datum med variabel noggrannhet."
    * format 1..1 code "format" "format"
    * format from DateTypeFormatVS (required)
    * partialDateValue 1..1 string "partialDateValue" "partialDateValue Heter value i schemat."
